// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.core.JsonValue
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BetaExternalPlanIdCreatePlanVersionParamsTest {

    @Test
    fun create() {
        BetaExternalPlanIdCreatePlanVersionParams.builder()
            .externalPlanId("external_plan_id")
            .version(0L)
            .addAddAdjustment(
                BetaExternalPlanIdCreatePlanVersionParams.AddAdjustment.builder()
                    .adjustment(
                        NewPercentageDiscount.builder()
                            .adjustmentType(
                                NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                            )
                            .percentageDiscount(0.0)
                            .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                            .addAppliesToItemId("item_1")
                            .addAppliesToItemId("item_2")
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .currency("currency")
                            .addFilter(
                                TransformPriceFilter.builder()
                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                    .operator(TransformPriceFilter.Operator.INCLUDES)
                                    .addValue("string")
                                    .build()
                            )
                            .isInvoiceLevel(true)
                            .priceType(NewPercentageDiscount.PriceType.USAGE)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .build()
            )
            .addAddPrice(
                BetaExternalPlanIdCreatePlanVersionParams.AddPrice.builder()
                    .allocationPrice(
                        NewAllocationPrice.builder()
                            .amount("10.00")
                            .cadence(NewAllocationPrice.Cadence.MONTHLY)
                            .currency("USD")
                            .customExpiration(
                                CustomExpiration.builder()
                                    .duration(0L)
                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        NewPlanUnitPrice.builder()
                            .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                            .itemId("item_id")
                            .modelType(NewPlanUnitPrice.ModelType.UNIT)
                            .name("Annual fee")
                            .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .conversionRate(0.0)
                            .unitConversionRateConfig(
                                NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                NewDimensionalPriceConfiguration.builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .metadata(
                                NewPlanUnitPrice.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .addRemoveAdjustment(
                BetaExternalPlanIdCreatePlanVersionParams.RemoveAdjustment.builder()
                    .adjustmentId("adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addRemovePrice(
                BetaExternalPlanIdCreatePlanVersionParams.RemovePrice.builder()
                    .priceId("price_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addReplaceAdjustment(
                BetaExternalPlanIdCreatePlanVersionParams.ReplaceAdjustment.builder()
                    .adjustment(
                        NewPercentageDiscount.builder()
                            .adjustmentType(
                                NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                            )
                            .percentageDiscount(0.0)
                            .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                            .addAppliesToItemId("item_1")
                            .addAppliesToItemId("item_2")
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .currency("currency")
                            .addFilter(
                                TransformPriceFilter.builder()
                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                    .operator(TransformPriceFilter.Operator.INCLUDES)
                                    .addValue("string")
                                    .build()
                            )
                            .isInvoiceLevel(true)
                            .priceType(NewPercentageDiscount.PriceType.USAGE)
                            .build()
                    )
                    .replacesAdjustmentId("replaces_adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addReplacePrice(
                BetaExternalPlanIdCreatePlanVersionParams.ReplacePrice.builder()
                    .replacesPriceId("replaces_price_id")
                    .allocationPrice(
                        NewAllocationPrice.builder()
                            .amount("10.00")
                            .cadence(NewAllocationPrice.Cadence.MONTHLY)
                            .currency("USD")
                            .customExpiration(
                                CustomExpiration.builder()
                                    .duration(0L)
                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        NewPlanUnitPrice.builder()
                            .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                            .itemId("item_id")
                            .modelType(NewPlanUnitPrice.ModelType.UNIT)
                            .name("Annual fee")
                            .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .conversionRate(0.0)
                            .unitConversionRateConfig(
                                NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                NewDimensionalPriceConfiguration.builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .metadata(
                                NewPlanUnitPrice.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .setAsDefault(true)
            .build()
    }

    @Test
    fun pathParams() {
        val params =
            BetaExternalPlanIdCreatePlanVersionParams.builder()
                .externalPlanId("external_plan_id")
                .version(0L)
                .build()

        assertThat(params._pathParam(0)).isEqualTo("external_plan_id")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            BetaExternalPlanIdCreatePlanVersionParams.builder()
                .externalPlanId("external_plan_id")
                .version(0L)
                .addAddAdjustment(
                    BetaExternalPlanIdCreatePlanVersionParams.AddAdjustment.builder()
                        .adjustment(
                            NewPercentageDiscount.builder()
                                .adjustmentType(
                                    NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                                )
                                .percentageDiscount(0.0)
                                .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                                .addAppliesToItemId("item_1")
                                .addAppliesToItemId("item_2")
                                .addAppliesToPriceId("price_1")
                                .addAppliesToPriceId("price_2")
                                .currency("currency")
                                .addFilter(
                                    TransformPriceFilter.builder()
                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                        .operator(TransformPriceFilter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .isInvoiceLevel(true)
                                .priceType(NewPercentageDiscount.PriceType.USAGE)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .build()
                )
                .addAddPrice(
                    BetaExternalPlanIdCreatePlanVersionParams.AddPrice.builder()
                        .allocationPrice(
                            NewAllocationPrice.builder()
                                .amount("10.00")
                                .cadence(NewAllocationPrice.Cadence.MONTHLY)
                                .currency("USD")
                                .customExpiration(
                                    CustomExpiration.builder()
                                        .duration(0L)
                                        .durationUnit(CustomExpiration.DurationUnit.DAY)
                                        .build()
                                )
                                .expiresAtEndOfCadence(true)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .price(
                            NewPlanUnitPrice.builder()
                                .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                                .itemId("item_id")
                                .modelType(NewPlanUnitPrice.ModelType.UNIT)
                                .name("Annual fee")
                                .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                                .billableMetricId("billable_metric_id")
                                .billedInAdvance(true)
                                .billingCycleConfiguration(
                                    NewBillingCycleConfiguration.builder()
                                        .duration(0L)
                                        .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                        .build()
                                )
                                .conversionRate(0.0)
                                .unitConversionRateConfig(
                                    NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                        .unitAmount("unit_amount")
                                        .build()
                                )
                                .currency("currency")
                                .dimensionalPriceConfiguration(
                                    NewDimensionalPriceConfiguration.builder()
                                        .addDimensionValue("string")
                                        .dimensionalPriceGroupId("dimensional_price_group_id")
                                        .externalDimensionalPriceGroupId(
                                            "external_dimensional_price_group_id"
                                        )
                                        .build()
                                )
                                .externalPriceId("external_price_id")
                                .fixedPriceQuantity(0.0)
                                .invoiceGroupingKey("x")
                                .invoicingCycleConfiguration(
                                    NewBillingCycleConfiguration.builder()
                                        .duration(0L)
                                        .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                        .build()
                                )
                                .metadata(
                                    NewPlanUnitPrice.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addRemoveAdjustment(
                    BetaExternalPlanIdCreatePlanVersionParams.RemoveAdjustment.builder()
                        .adjustmentId("adjustment_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addRemovePrice(
                    BetaExternalPlanIdCreatePlanVersionParams.RemovePrice.builder()
                        .priceId("price_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addReplaceAdjustment(
                    BetaExternalPlanIdCreatePlanVersionParams.ReplaceAdjustment.builder()
                        .adjustment(
                            NewPercentageDiscount.builder()
                                .adjustmentType(
                                    NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                                )
                                .percentageDiscount(0.0)
                                .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                                .addAppliesToItemId("item_1")
                                .addAppliesToItemId("item_2")
                                .addAppliesToPriceId("price_1")
                                .addAppliesToPriceId("price_2")
                                .currency("currency")
                                .addFilter(
                                    TransformPriceFilter.builder()
                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                        .operator(TransformPriceFilter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .isInvoiceLevel(true)
                                .priceType(NewPercentageDiscount.PriceType.USAGE)
                                .build()
                        )
                        .replacesAdjustmentId("replaces_adjustment_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addReplacePrice(
                    BetaExternalPlanIdCreatePlanVersionParams.ReplacePrice.builder()
                        .replacesPriceId("replaces_price_id")
                        .allocationPrice(
                            NewAllocationPrice.builder()
                                .amount("10.00")
                                .cadence(NewAllocationPrice.Cadence.MONTHLY)
                                .currency("USD")
                                .customExpiration(
                                    CustomExpiration.builder()
                                        .duration(0L)
                                        .durationUnit(CustomExpiration.DurationUnit.DAY)
                                        .build()
                                )
                                .expiresAtEndOfCadence(true)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .price(
                            NewPlanUnitPrice.builder()
                                .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                                .itemId("item_id")
                                .modelType(NewPlanUnitPrice.ModelType.UNIT)
                                .name("Annual fee")
                                .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                                .billableMetricId("billable_metric_id")
                                .billedInAdvance(true)
                                .billingCycleConfiguration(
                                    NewBillingCycleConfiguration.builder()
                                        .duration(0L)
                                        .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                        .build()
                                )
                                .conversionRate(0.0)
                                .unitConversionRateConfig(
                                    NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                        .unitAmount("unit_amount")
                                        .build()
                                )
                                .currency("currency")
                                .dimensionalPriceConfiguration(
                                    NewDimensionalPriceConfiguration.builder()
                                        .addDimensionValue("string")
                                        .dimensionalPriceGroupId("dimensional_price_group_id")
                                        .externalDimensionalPriceGroupId(
                                            "external_dimensional_price_group_id"
                                        )
                                        .build()
                                )
                                .externalPriceId("external_price_id")
                                .fixedPriceQuantity(0.0)
                                .invoiceGroupingKey("x")
                                .invoicingCycleConfiguration(
                                    NewBillingCycleConfiguration.builder()
                                        .duration(0L)
                                        .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                        .build()
                                )
                                .metadata(
                                    NewPlanUnitPrice.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .setAsDefault(true)
                .build()

        val body = params._body()

        assertThat(body.version()).isEqualTo(0L)
        assertThat(body.addAdjustments().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.AddAdjustment.builder()
                    .adjustment(
                        NewPercentageDiscount.builder()
                            .adjustmentType(
                                NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                            )
                            .percentageDiscount(0.0)
                            .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                            .addAppliesToItemId("item_1")
                            .addAppliesToItemId("item_2")
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .currency("currency")
                            .addFilter(
                                TransformPriceFilter.builder()
                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                    .operator(TransformPriceFilter.Operator.INCLUDES)
                                    .addValue("string")
                                    .build()
                            )
                            .isInvoiceLevel(true)
                            .priceType(NewPercentageDiscount.PriceType.USAGE)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.addPrices().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.AddPrice.builder()
                    .allocationPrice(
                        NewAllocationPrice.builder()
                            .amount("10.00")
                            .cadence(NewAllocationPrice.Cadence.MONTHLY)
                            .currency("USD")
                            .customExpiration(
                                CustomExpiration.builder()
                                    .duration(0L)
                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        NewPlanUnitPrice.builder()
                            .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                            .itemId("item_id")
                            .modelType(NewPlanUnitPrice.ModelType.UNIT)
                            .name("Annual fee")
                            .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .conversionRate(0.0)
                            .unitConversionRateConfig(
                                NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                NewDimensionalPriceConfiguration.builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .metadata(
                                NewPlanUnitPrice.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.removeAdjustments().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.RemoveAdjustment.builder()
                    .adjustmentId("adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.removePrices().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.RemovePrice.builder()
                    .priceId("price_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.replaceAdjustments().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.ReplaceAdjustment.builder()
                    .adjustment(
                        NewPercentageDiscount.builder()
                            .adjustmentType(
                                NewPercentageDiscount.AdjustmentType.PERCENTAGE_DISCOUNT
                            )
                            .percentageDiscount(0.0)
                            .appliesToAll(NewPercentageDiscount.AppliesToAll.TRUE)
                            .addAppliesToItemId("item_1")
                            .addAppliesToItemId("item_2")
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .currency("currency")
                            .addFilter(
                                TransformPriceFilter.builder()
                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                    .operator(TransformPriceFilter.Operator.INCLUDES)
                                    .addValue("string")
                                    .build()
                            )
                            .isInvoiceLevel(true)
                            .priceType(NewPercentageDiscount.PriceType.USAGE)
                            .build()
                    )
                    .replacesAdjustmentId("replaces_adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.replacePrices().getOrNull())
            .containsExactly(
                BetaExternalPlanIdCreatePlanVersionParams.ReplacePrice.builder()
                    .replacesPriceId("replaces_price_id")
                    .allocationPrice(
                        NewAllocationPrice.builder()
                            .amount("10.00")
                            .cadence(NewAllocationPrice.Cadence.MONTHLY)
                            .currency("USD")
                            .customExpiration(
                                CustomExpiration.builder()
                                    .duration(0L)
                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        NewPlanUnitPrice.builder()
                            .cadence(NewPlanUnitPrice.Cadence.ANNUAL)
                            .itemId("item_id")
                            .modelType(NewPlanUnitPrice.ModelType.UNIT)
                            .name("Annual fee")
                            .unitConfig(UnitConfig.builder().unitAmount("unit_amount").build())
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .conversionRate(0.0)
                            .unitConversionRateConfig(
                                NewPlanUnitPrice.ConversionRateConfig.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                NewDimensionalPriceConfiguration.builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                NewBillingCycleConfiguration.builder()
                                    .duration(0L)
                                    .durationUnit(NewBillingCycleConfiguration.DurationUnit.DAY)
                                    .build()
                            )
                            .metadata(
                                NewPlanUnitPrice.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.setAsDefault()).contains(true)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            BetaExternalPlanIdCreatePlanVersionParams.builder()
                .externalPlanId("external_plan_id")
                .version(0L)
                .build()

        val body = params._body()

        assertThat(body.version()).isEqualTo(0L)
    }
}
