// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.core.JsonValue
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BetaCreatePlanVersionParamsTest {

    @Test
    fun create() {
        BetaCreatePlanVersionParams.builder()
            .planId("plan_id")
            .version(0L)
            .addAddAdjustment(
                BetaCreatePlanVersionParams.AddAdjustment.builder()
                    .adjustment(
                        BetaCreatePlanVersionParams.AddAdjustment.Adjustment.PercentageDiscount
                            .builder()
                            .percentageDiscount(0.0)
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .isInvoiceLevel(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .build()
            )
            .addAddPrice(
                BetaCreatePlanVersionParams.AddPrice.builder()
                    .allocationPrice(
                        BetaCreatePlanVersionParams.AddPrice.AllocationPrice.builder()
                            .amount("10.00")
                            .cadence(
                                BetaCreatePlanVersionParams.AddPrice.AllocationPrice.Cadence.MONTHLY
                            )
                            .currency("USD")
                            .customExpiration(
                                BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                    .CustomExpiration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                            .CustomExpiration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        BetaCreatePlanVersionParams.AddPrice.Price.Unit.builder()
                            .cadence(BetaCreatePlanVersionParams.AddPrice.Price.Unit.Cadence.ANNUAL)
                            .itemId("item_id")
                            .name("Annual fee")
                            .unitConfig(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .BillingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                            .BillingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .conversionRate(0.0)
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .DimensionalPriceConfiguration
                                    .builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .InvoicingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                            .InvoicingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .metadata(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .addRemoveAdjustment(
                BetaCreatePlanVersionParams.RemoveAdjustment.builder()
                    .adjustmentId("adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addRemovePrice(
                BetaCreatePlanVersionParams.RemovePrice.builder()
                    .priceId("price_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addReplaceAdjustment(
                BetaCreatePlanVersionParams.ReplaceAdjustment.builder()
                    .adjustment(
                        BetaCreatePlanVersionParams.ReplaceAdjustment.Adjustment.PercentageDiscount
                            .builder()
                            .percentageDiscount(0.0)
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .isInvoiceLevel(true)
                            .build()
                    )
                    .replacesAdjustmentId("replaces_adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
            .addReplacePrice(
                BetaCreatePlanVersionParams.ReplacePrice.builder()
                    .replacesPriceId("replaces_price_id")
                    .allocationPrice(
                        BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.builder()
                            .amount("10.00")
                            .cadence(
                                BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.Cadence
                                    .MONTHLY
                            )
                            .currency("USD")
                            .customExpiration(
                                BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                    .CustomExpiration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                            .CustomExpiration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.builder()
                            .cadence(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Cadence.ANNUAL
                            )
                            .itemId("item_id")
                            .name("Annual fee")
                            .unitConfig(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.UnitConfig
                                    .builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .BillingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                            .BillingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .conversionRate(0.0)
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .DimensionalPriceConfiguration
                                    .builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .InvoicingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                            .InvoicingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .metadata(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Metadata
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .setAsDefault(true)
            .build()
    }

    @Test
    fun pathParams() {
        val params = BetaCreatePlanVersionParams.builder().planId("plan_id").version(0L).build()

        assertThat(params._pathParam(0)).isEqualTo("plan_id")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            BetaCreatePlanVersionParams.builder()
                .planId("plan_id")
                .version(0L)
                .addAddAdjustment(
                    BetaCreatePlanVersionParams.AddAdjustment.builder()
                        .adjustment(
                            BetaCreatePlanVersionParams.AddAdjustment.Adjustment.PercentageDiscount
                                .builder()
                                .percentageDiscount(0.0)
                                .addAppliesToPriceId("price_1")
                                .addAppliesToPriceId("price_2")
                                .isInvoiceLevel(true)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .build()
                )
                .addAddPrice(
                    BetaCreatePlanVersionParams.AddPrice.builder()
                        .allocationPrice(
                            BetaCreatePlanVersionParams.AddPrice.AllocationPrice.builder()
                                .amount("10.00")
                                .cadence(
                                    BetaCreatePlanVersionParams.AddPrice.AllocationPrice.Cadence
                                        .MONTHLY
                                )
                                .currency("USD")
                                .customExpiration(
                                    BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                        .CustomExpiration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                                .CustomExpiration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .expiresAtEndOfCadence(true)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .price(
                            BetaCreatePlanVersionParams.AddPrice.Price.Unit.builder()
                                .cadence(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit.Cadence.ANNUAL
                                )
                                .itemId("item_id")
                                .name("Annual fee")
                                .unitConfig(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit.UnitConfig
                                        .builder()
                                        .unitAmount("unit_amount")
                                        .build()
                                )
                                .billableMetricId("billable_metric_id")
                                .billedInAdvance(true)
                                .billingCycleConfiguration(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                        .BillingCycleConfiguration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                                .BillingCycleConfiguration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .conversionRate(0.0)
                                .currency("currency")
                                .dimensionalPriceConfiguration(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                        .DimensionalPriceConfiguration
                                        .builder()
                                        .addDimensionValue("string")
                                        .dimensionalPriceGroupId("dimensional_price_group_id")
                                        .externalDimensionalPriceGroupId(
                                            "external_dimensional_price_group_id"
                                        )
                                        .build()
                                )
                                .externalPriceId("external_price_id")
                                .fixedPriceQuantity(0.0)
                                .invoiceGroupingKey("x")
                                .invoicingCycleConfiguration(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                        .InvoicingCycleConfiguration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                                .InvoicingCycleConfiguration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .metadata(
                                    BetaCreatePlanVersionParams.AddPrice.Price.Unit.Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addRemoveAdjustment(
                    BetaCreatePlanVersionParams.RemoveAdjustment.builder()
                        .adjustmentId("adjustment_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addRemovePrice(
                    BetaCreatePlanVersionParams.RemovePrice.builder()
                        .priceId("price_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addReplaceAdjustment(
                    BetaCreatePlanVersionParams.ReplaceAdjustment.builder()
                        .adjustment(
                            BetaCreatePlanVersionParams.ReplaceAdjustment.Adjustment
                                .PercentageDiscount
                                .builder()
                                .percentageDiscount(0.0)
                                .addAppliesToPriceId("price_1")
                                .addAppliesToPriceId("price_2")
                                .isInvoiceLevel(true)
                                .build()
                        )
                        .replacesAdjustmentId("replaces_adjustment_id")
                        .planPhaseOrder(0L)
                        .build()
                )
                .addReplacePrice(
                    BetaCreatePlanVersionParams.ReplacePrice.builder()
                        .replacesPriceId("replaces_price_id")
                        .allocationPrice(
                            BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.builder()
                                .amount("10.00")
                                .cadence(
                                    BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.Cadence
                                        .MONTHLY
                                )
                                .currency("USD")
                                .customExpiration(
                                    BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                        .CustomExpiration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                                .CustomExpiration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .expiresAtEndOfCadence(true)
                                .build()
                        )
                        .planPhaseOrder(0L)
                        .price(
                            BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.builder()
                                .cadence(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Cadence
                                        .ANNUAL
                                )
                                .itemId("item_id")
                                .name("Annual fee")
                                .unitConfig(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.UnitConfig
                                        .builder()
                                        .unitAmount("unit_amount")
                                        .build()
                                )
                                .billableMetricId("billable_metric_id")
                                .billedInAdvance(true)
                                .billingCycleConfiguration(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                        .BillingCycleConfiguration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                                .BillingCycleConfiguration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .conversionRate(0.0)
                                .currency("currency")
                                .dimensionalPriceConfiguration(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                        .DimensionalPriceConfiguration
                                        .builder()
                                        .addDimensionValue("string")
                                        .dimensionalPriceGroupId("dimensional_price_group_id")
                                        .externalDimensionalPriceGroupId(
                                            "external_dimensional_price_group_id"
                                        )
                                        .build()
                                )
                                .externalPriceId("external_price_id")
                                .fixedPriceQuantity(0.0)
                                .invoiceGroupingKey("x")
                                .invoicingCycleConfiguration(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                        .InvoicingCycleConfiguration
                                        .builder()
                                        .duration(0L)
                                        .durationUnit(
                                            BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                                .InvoicingCycleConfiguration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .metadata(
                                    BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .setAsDefault(true)
                .build()

        val body = params._body()

        assertThat(body.version()).isEqualTo(0L)
        assertThat(body.addAdjustments().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.AddAdjustment.builder()
                    .adjustment(
                        BetaCreatePlanVersionParams.AddAdjustment.Adjustment.PercentageDiscount
                            .builder()
                            .percentageDiscount(0.0)
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .isInvoiceLevel(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.addPrices().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.AddPrice.builder()
                    .allocationPrice(
                        BetaCreatePlanVersionParams.AddPrice.AllocationPrice.builder()
                            .amount("10.00")
                            .cadence(
                                BetaCreatePlanVersionParams.AddPrice.AllocationPrice.Cadence.MONTHLY
                            )
                            .currency("USD")
                            .customExpiration(
                                BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                    .CustomExpiration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.AllocationPrice
                                            .CustomExpiration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        BetaCreatePlanVersionParams.AddPrice.Price.Unit.builder()
                            .cadence(BetaCreatePlanVersionParams.AddPrice.Price.Unit.Cadence.ANNUAL)
                            .itemId("item_id")
                            .name("Annual fee")
                            .unitConfig(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit.UnitConfig.builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .BillingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                            .BillingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .conversionRate(0.0)
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .DimensionalPriceConfiguration
                                    .builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                    .InvoicingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.AddPrice.Price.Unit
                                            .InvoicingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .metadata(
                                BetaCreatePlanVersionParams.AddPrice.Price.Unit.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.removeAdjustments().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.RemoveAdjustment.builder()
                    .adjustmentId("adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.removePrices().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.RemovePrice.builder()
                    .priceId("price_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.replaceAdjustments().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.ReplaceAdjustment.builder()
                    .adjustment(
                        BetaCreatePlanVersionParams.ReplaceAdjustment.Adjustment.PercentageDiscount
                            .builder()
                            .percentageDiscount(0.0)
                            .addAppliesToPriceId("price_1")
                            .addAppliesToPriceId("price_2")
                            .isInvoiceLevel(true)
                            .build()
                    )
                    .replacesAdjustmentId("replaces_adjustment_id")
                    .planPhaseOrder(0L)
                    .build()
            )
        assertThat(body.replacePrices().getOrNull())
            .containsExactly(
                BetaCreatePlanVersionParams.ReplacePrice.builder()
                    .replacesPriceId("replaces_price_id")
                    .allocationPrice(
                        BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.builder()
                            .amount("10.00")
                            .cadence(
                                BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice.Cadence
                                    .MONTHLY
                            )
                            .currency("USD")
                            .customExpiration(
                                BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                    .CustomExpiration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.AllocationPrice
                                            .CustomExpiration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .expiresAtEndOfCadence(true)
                            .build()
                    )
                    .planPhaseOrder(0L)
                    .price(
                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.builder()
                            .cadence(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Cadence.ANNUAL
                            )
                            .itemId("item_id")
                            .name("Annual fee")
                            .unitConfig(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.UnitConfig
                                    .builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .billableMetricId("billable_metric_id")
                            .billedInAdvance(true)
                            .billingCycleConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .BillingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                            .BillingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .conversionRate(0.0)
                            .currency("currency")
                            .dimensionalPriceConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .DimensionalPriceConfiguration
                                    .builder()
                                    .addDimensionValue("string")
                                    .dimensionalPriceGroupId("dimensional_price_group_id")
                                    .externalDimensionalPriceGroupId(
                                        "external_dimensional_price_group_id"
                                    )
                                    .build()
                            )
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(0.0)
                            .invoiceGroupingKey("x")
                            .invoicingCycleConfiguration(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                    .InvoicingCycleConfiguration
                                    .builder()
                                    .duration(0L)
                                    .durationUnit(
                                        BetaCreatePlanVersionParams.ReplacePrice.Price.Unit
                                            .InvoicingCycleConfiguration
                                            .DurationUnit
                                            .DAY
                                    )
                                    .build()
                            )
                            .metadata(
                                BetaCreatePlanVersionParams.ReplacePrice.Price.Unit.Metadata
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.setAsDefault()).contains(true)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = BetaCreatePlanVersionParams.builder().planId("plan_id").version(0L).build()

        val body = params._body()

        assertThat(body.version()).isEqualTo(0L)
    }
}
