// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CreditNoteAccountingSyncSucceededWebhookEventTest {

    @Test
    fun create() {
        val creditNoteAccountingSyncSucceededWebhookEvent =
            CreditNoteAccountingSyncSucceededWebhookEvent.builder()
                .id("id")
                .accountingSyncRecord(
                    CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                        .id("id")
                        .customerId("customer_id")
                        .recordType(
                            CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .RecordType
                                .CUSTOMER
                        )
                        .creditNoteId("credit_note_id")
                        .errorDetails(
                            CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .ErrorDetails
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .providerCustomerId("provider_customer_id")
                        .status("status")
                        .syncAction("sync_action")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditNote(
                    CreditNote.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .creditNoteNumber("credit_note_number")
                        .creditNotePdf("credit_note_pdf")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .invoiceId("invoice_id")
                        .addLineItem(
                            CreditNote.LineItem.builder()
                                .id("id")
                                .amount("amount")
                                .itemId("item_id")
                                .name("name")
                                .quantity(0.0)
                                .subtotal("subtotal")
                                .addTaxAmount(
                                    TaxAmount.builder()
                                        .amount("amount")
                                        .taxRateDescription("tax_rate_description")
                                        .taxRatePercentage("tax_rate_percentage")
                                        .build()
                                )
                                .addDiscount(
                                    CreditNote.LineItem.Discount.builder()
                                        .id("id")
                                        .amountApplied("amount_applied")
                                        .addAppliesToPriceId("string")
                                        .discountType(
                                            CreditNote.LineItem.Discount.DiscountType.PERCENTAGE
                                        )
                                        .percentageDiscount(0.0)
                                        .amountDiscount("amount_discount")
                                        .reason("reason")
                                        .build()
                                )
                                .endTimeExclusive(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startTimeInclusive(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .maximumAmountAdjustment(
                            CreditNote.MaximumAmountAdjustment.builder()
                                .amountApplied("amount_applied")
                                .discountType(
                                    CreditNote.MaximumAmountAdjustment.DiscountType.PERCENTAGE
                                )
                                .percentageDiscount(0.0)
                                .addAppliesToPrice(
                                    CreditNote.MaximumAmountAdjustment.AppliesToPrice.builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .memo("memo")
                        .minimumAmountRefunded("minimum_amount_refunded")
                        .reason(CreditNote.Reason.DUPLICATE)
                        .subtotal("subtotal")
                        .total("total")
                        .type(CreditNote.Type.REFUND)
                        .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDiscount(
                            CreditNote.Discount.builder()
                                .amountApplied("amount_applied")
                                .discountType(CreditNote.Discount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.0)
                                .addAppliesToPrice(
                                    CreditNote.Discount.AppliesToPrice.builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .build()
                )
                .properties(
                    CreditNoteAccountingSyncSucceededWebhookEvent.Properties.builder()
                        .connectionType("connection_type")
                        .build()
                )
                .type(
                    CreditNoteAccountingSyncSucceededWebhookEvent.Type
                        .CREDIT_NOTE_ACCOUNTING_SYNC_SUCCEEDED
                )
                .build()

        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.id()).isEqualTo("id")
        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.accountingSyncRecord())
            .isEqualTo(
                CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                    .id("id")
                    .customerId("customer_id")
                    .recordType(
                        CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                            .RecordType
                            .CUSTOMER
                    )
                    .creditNoteId("credit_note_id")
                    .errorDetails(
                        CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                            .ErrorDetails
                            .builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .providerCustomerId("provider_customer_id")
                    .status("status")
                    .syncAction("sync_action")
                    .build()
            )
        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.creditNote())
            .isEqualTo(
                CreditNote.builder()
                    .id("id")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditNoteNumber("credit_note_number")
                    .creditNotePdf("credit_note_pdf")
                    .customer(
                        CustomerMinified.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .invoiceId("invoice_id")
                    .addLineItem(
                        CreditNote.LineItem.builder()
                            .id("id")
                            .amount("amount")
                            .itemId("item_id")
                            .name("name")
                            .quantity(0.0)
                            .subtotal("subtotal")
                            .addTaxAmount(
                                TaxAmount.builder()
                                    .amount("amount")
                                    .taxRateDescription("tax_rate_description")
                                    .taxRatePercentage("tax_rate_percentage")
                                    .build()
                            )
                            .addDiscount(
                                CreditNote.LineItem.Discount.builder()
                                    .id("id")
                                    .amountApplied("amount_applied")
                                    .addAppliesToPriceId("string")
                                    .discountType(
                                        CreditNote.LineItem.Discount.DiscountType.PERCENTAGE
                                    )
                                    .percentageDiscount(0.0)
                                    .amountDiscount("amount_discount")
                                    .reason("reason")
                                    .build()
                            )
                            .endTimeExclusive(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .startTimeInclusive(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .maximumAmountAdjustment(
                        CreditNote.MaximumAmountAdjustment.builder()
                            .amountApplied("amount_applied")
                            .discountType(
                                CreditNote.MaximumAmountAdjustment.DiscountType.PERCENTAGE
                            )
                            .percentageDiscount(0.0)
                            .addAppliesToPrice(
                                CreditNote.MaximumAmountAdjustment.AppliesToPrice.builder()
                                    .id("id")
                                    .name("name")
                                    .build()
                            )
                            .reason("reason")
                            .build()
                    )
                    .memo("memo")
                    .minimumAmountRefunded("minimum_amount_refunded")
                    .reason(CreditNote.Reason.DUPLICATE)
                    .subtotal("subtotal")
                    .total("total")
                    .type(CreditNote.Type.REFUND)
                    .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addDiscount(
                        CreditNote.Discount.builder()
                            .amountApplied("amount_applied")
                            .discountType(CreditNote.Discount.DiscountType.PERCENTAGE)
                            .percentageDiscount(0.0)
                            .addAppliesToPrice(
                                CreditNote.Discount.AppliesToPrice.builder()
                                    .id("id")
                                    .name("name")
                                    .build()
                            )
                            .reason("reason")
                            .build()
                    )
                    .build()
            )
        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.properties())
            .isEqualTo(
                CreditNoteAccountingSyncSucceededWebhookEvent.Properties.builder()
                    .connectionType("connection_type")
                    .build()
            )
        assertThat(creditNoteAccountingSyncSucceededWebhookEvent.type())
            .isEqualTo(
                CreditNoteAccountingSyncSucceededWebhookEvent.Type
                    .CREDIT_NOTE_ACCOUNTING_SYNC_SUCCEEDED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val creditNoteAccountingSyncSucceededWebhookEvent =
            CreditNoteAccountingSyncSucceededWebhookEvent.builder()
                .id("id")
                .accountingSyncRecord(
                    CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                        .id("id")
                        .customerId("customer_id")
                        .recordType(
                            CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .RecordType
                                .CUSTOMER
                        )
                        .creditNoteId("credit_note_id")
                        .errorDetails(
                            CreditNoteAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .ErrorDetails
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .providerCustomerId("provider_customer_id")
                        .status("status")
                        .syncAction("sync_action")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditNote(
                    CreditNote.builder()
                        .id("id")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .creditNoteNumber("credit_note_number")
                        .creditNotePdf("credit_note_pdf")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .invoiceId("invoice_id")
                        .addLineItem(
                            CreditNote.LineItem.builder()
                                .id("id")
                                .amount("amount")
                                .itemId("item_id")
                                .name("name")
                                .quantity(0.0)
                                .subtotal("subtotal")
                                .addTaxAmount(
                                    TaxAmount.builder()
                                        .amount("amount")
                                        .taxRateDescription("tax_rate_description")
                                        .taxRatePercentage("tax_rate_percentage")
                                        .build()
                                )
                                .addDiscount(
                                    CreditNote.LineItem.Discount.builder()
                                        .id("id")
                                        .amountApplied("amount_applied")
                                        .addAppliesToPriceId("string")
                                        .discountType(
                                            CreditNote.LineItem.Discount.DiscountType.PERCENTAGE
                                        )
                                        .percentageDiscount(0.0)
                                        .amountDiscount("amount_discount")
                                        .reason("reason")
                                        .build()
                                )
                                .endTimeExclusive(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .startTimeInclusive(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .maximumAmountAdjustment(
                            CreditNote.MaximumAmountAdjustment.builder()
                                .amountApplied("amount_applied")
                                .discountType(
                                    CreditNote.MaximumAmountAdjustment.DiscountType.PERCENTAGE
                                )
                                .percentageDiscount(0.0)
                                .addAppliesToPrice(
                                    CreditNote.MaximumAmountAdjustment.AppliesToPrice.builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .memo("memo")
                        .minimumAmountRefunded("minimum_amount_refunded")
                        .reason(CreditNote.Reason.DUPLICATE)
                        .subtotal("subtotal")
                        .total("total")
                        .type(CreditNote.Type.REFUND)
                        .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addDiscount(
                            CreditNote.Discount.builder()
                                .amountApplied("amount_applied")
                                .discountType(CreditNote.Discount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.0)
                                .addAppliesToPrice(
                                    CreditNote.Discount.AppliesToPrice.builder()
                                        .id("id")
                                        .name("name")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .build()
                )
                .properties(
                    CreditNoteAccountingSyncSucceededWebhookEvent.Properties.builder()
                        .connectionType("connection_type")
                        .build()
                )
                .type(
                    CreditNoteAccountingSyncSucceededWebhookEvent.Type
                        .CREDIT_NOTE_ACCOUNTING_SYNC_SUCCEEDED
                )
                .build()

        val roundtrippedCreditNoteAccountingSyncSucceededWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(creditNoteAccountingSyncSucceededWebhookEvent),
                jacksonTypeRef<CreditNoteAccountingSyncSucceededWebhookEvent>(),
            )

        assertThat(roundtrippedCreditNoteAccountingSyncSucceededWebhookEvent)
            .isEqualTo(creditNoteAccountingSyncSucceededWebhookEvent)
    }
}
