// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CreditNoteModelTest {

    @Test
    fun createCreditNoteModel() {
        val creditNoteModel =
            CreditNoteModel.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditNoteNumber("credit_note_number")
                .creditNotePdf("credit_note_pdf")
                .customer(
                    CustomerMinifiedModel.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .invoiceId("invoice_id")
                .addLineItem(
                    CreditNoteModel.LineItem.builder()
                        .id("id")
                        .amount("amount")
                        .itemId("item_id")
                        .name("name")
                        .quantity(0.0)
                        .subtotal("subtotal")
                        .addTaxAmount(
                            TaxAmountModel.builder()
                                .amount("amount")
                                .taxRateDescription("tax_rate_description")
                                .taxRatePercentage("tax_rate_percentage")
                                .build()
                        )
                        .addDiscount(
                            CreditNoteModel.LineItem.Discount.builder()
                                .id("id")
                                .amountApplied("amount_applied")
                                .addAppliesToPriceId("string")
                                .discountType(
                                    CreditNoteModel.LineItem.Discount.DiscountType.PERCENTAGE
                                )
                                .percentageDiscount(0.0)
                                .amountDiscount("amount_discount")
                                .reason("reason")
                                .build()
                        )
                        .build()
                )
                .maximumAmountAdjustment(
                    CreditNoteDiscountModel.builder()
                        .amountApplied("amount_applied")
                        .discountType(CreditNoteDiscountModel.DiscountType.PERCENTAGE)
                        .percentageDiscount(0.0)
                        .addAppliesToPrice(
                            CreditNoteDiscountModel.AppliesToPrice.builder()
                                .id("id")
                                .name("name")
                                .build()
                        )
                        .reason("reason")
                        .build()
                )
                .memo("memo")
                .minimumAmountRefunded("minimum_amount_refunded")
                .reason(CreditNoteModel.Reason.DUPLICATE)
                .subtotal("subtotal")
                .total("total")
                .type(CreditNoteModel.Type.REFUND)
                .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addDiscount(
                    CreditNoteDiscountModel.builder()
                        .amountApplied("amount_applied")
                        .discountType(CreditNoteDiscountModel.DiscountType.PERCENTAGE)
                        .percentageDiscount(0.0)
                        .addAppliesToPrice(
                            CreditNoteDiscountModel.AppliesToPrice.builder()
                                .id("id")
                                .name("name")
                                .build()
                        )
                        .reason("reason")
                        .build()
                )
                .build()
        assertThat(creditNoteModel).isNotNull
        assertThat(creditNoteModel.id()).isEqualTo("id")
        assertThat(creditNoteModel.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(creditNoteModel.creditNoteNumber()).isEqualTo("credit_note_number")
        assertThat(creditNoteModel.creditNotePdf()).contains("credit_note_pdf")
        assertThat(creditNoteModel.customer())
            .isEqualTo(
                CustomerMinifiedModel.builder()
                    .id("id")
                    .externalCustomerId("external_customer_id")
                    .build()
            )
        assertThat(creditNoteModel.invoiceId()).isEqualTo("invoice_id")
        assertThat(creditNoteModel.lineItems())
            .containsExactly(
                CreditNoteModel.LineItem.builder()
                    .id("id")
                    .amount("amount")
                    .itemId("item_id")
                    .name("name")
                    .quantity(0.0)
                    .subtotal("subtotal")
                    .addTaxAmount(
                        TaxAmountModel.builder()
                            .amount("amount")
                            .taxRateDescription("tax_rate_description")
                            .taxRatePercentage("tax_rate_percentage")
                            .build()
                    )
                    .addDiscount(
                        CreditNoteModel.LineItem.Discount.builder()
                            .id("id")
                            .amountApplied("amount_applied")
                            .addAppliesToPriceId("string")
                            .discountType(CreditNoteModel.LineItem.Discount.DiscountType.PERCENTAGE)
                            .percentageDiscount(0.0)
                            .amountDiscount("amount_discount")
                            .reason("reason")
                            .build()
                    )
                    .build()
            )
        assertThat(creditNoteModel.maximumAmountAdjustment())
            .contains(
                CreditNoteDiscountModel.builder()
                    .amountApplied("amount_applied")
                    .discountType(CreditNoteDiscountModel.DiscountType.PERCENTAGE)
                    .percentageDiscount(0.0)
                    .addAppliesToPrice(
                        CreditNoteDiscountModel.AppliesToPrice.builder()
                            .id("id")
                            .name("name")
                            .build()
                    )
                    .reason("reason")
                    .build()
            )
        assertThat(creditNoteModel.memo()).contains("memo")
        assertThat(creditNoteModel.minimumAmountRefunded()).contains("minimum_amount_refunded")
        assertThat(creditNoteModel.reason()).contains(CreditNoteModel.Reason.DUPLICATE)
        assertThat(creditNoteModel.subtotal()).isEqualTo("subtotal")
        assertThat(creditNoteModel.total()).isEqualTo("total")
        assertThat(creditNoteModel.type()).isEqualTo(CreditNoteModel.Type.REFUND)
        assertThat(creditNoteModel.voidedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(creditNoteModel.discounts().get())
            .containsExactly(
                CreditNoteDiscountModel.builder()
                    .amountApplied("amount_applied")
                    .discountType(CreditNoteDiscountModel.DiscountType.PERCENTAGE)
                    .percentageDiscount(0.0)
                    .addAppliesToPrice(
                        CreditNoteDiscountModel.AppliesToPrice.builder()
                            .id("id")
                            .name("name")
                            .build()
                    )
                    .reason("reason")
                    .build()
            )
    }
}
