// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerCostListByExternalIdResponseTest {

    @Test
    fun create() {
        val customerCostListByExternalIdResponse =
            CustomerCostListByExternalIdResponse.builder()
                .addData(
                    AggregatedCost.builder()
                        .addPerPriceCost(
                            PerPriceCost.builder()
                                .price(
                                    Price.Unit.builder()
                                        .id("id")
                                        .billableMetric(
                                            BillableMetricTiny.builder().id("id").build()
                                        )
                                        .billingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .cadence(Price.Unit.Cadence.ONE_TIME)
                                        .addCompositePriceFilter(
                                            TransformPriceFilter.builder()
                                                .field(TransformPriceFilter.Field.PRICE_ID)
                                                .operator(TransformPriceFilter.Operator.INCLUDES)
                                                .addValue("string")
                                                .build()
                                        )
                                        .conversionRate(0.0)
                                        .unitConversionRateConfig(
                                            ConversionRateUnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .creditAllocation(
                                            Allocation.builder()
                                                .allowsRollover(true)
                                                .currency("currency")
                                                .customExpiration(
                                                    CustomExpiration.builder()
                                                        .duration(0L)
                                                        .durationUnit(
                                                            CustomExpiration.DurationUnit.DAY
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .currency("currency")
                                        .discount(
                                            PercentageDiscount.builder()
                                                .discountType(
                                                    PercentageDiscount.DiscountType.PERCENTAGE
                                                )
                                                .percentageDiscount(0.15)
                                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .reason("reason")
                                                .build()
                                        )
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(0.0)
                                        .invoicingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .item(ItemSlim.builder().id("id").name("name").build())
                                        .maximum(
                                            Maximum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .maximumAmount("maximum_amount")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .metadata(
                                            Price.Unit.Metadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .minimum(
                                            Minimum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .minimumAmount("minimum_amount")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .name("name")
                                        .planPhaseOrder(0L)
                                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                                        .replacesPriceId("replaces_price_id")
                                        .unitConfig(
                                            UnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .scalingFactor(0.0)
                                                .build()
                                        )
                                        .dimensionalPriceConfiguration(
                                            DimensionalPriceConfiguration.builder()
                                                .addDimensionValue("string")
                                                .dimensionalPriceGroupId(
                                                    "dimensional_price_group_id"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .priceId("price_id")
                                .subtotal("subtotal")
                                .total("total")
                                .quantity(0.0)
                                .build()
                        )
                        .subtotal("subtotal")
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("total")
                        .build()
                )
                .build()

        assertThat(customerCostListByExternalIdResponse.data())
            .containsExactly(
                AggregatedCost.builder()
                    .addPerPriceCost(
                        PerPriceCost.builder()
                            .price(
                                Price.Unit.builder()
                                    .id("id")
                                    .billableMetric(BillableMetricTiny.builder().id("id").build())
                                    .billingCycleConfiguration(
                                        BillingCycleConfiguration.builder()
                                            .duration(0L)
                                            .durationUnit(
                                                BillingCycleConfiguration.DurationUnit.DAY
                                            )
                                            .build()
                                    )
                                    .cadence(Price.Unit.Cadence.ONE_TIME)
                                    .addCompositePriceFilter(
                                        TransformPriceFilter.builder()
                                            .field(TransformPriceFilter.Field.PRICE_ID)
                                            .operator(TransformPriceFilter.Operator.INCLUDES)
                                            .addValue("string")
                                            .build()
                                    )
                                    .conversionRate(0.0)
                                    .unitConversionRateConfig(
                                        ConversionRateUnitConfig.builder()
                                            .unitAmount("unit_amount")
                                            .build()
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .creditAllocation(
                                        Allocation.builder()
                                            .allowsRollover(true)
                                            .currency("currency")
                                            .customExpiration(
                                                CustomExpiration.builder()
                                                    .duration(0L)
                                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .currency("currency")
                                    .discount(
                                        PercentageDiscount.builder()
                                            .discountType(
                                                PercentageDiscount.DiscountType.PERCENTAGE
                                            )
                                            .percentageDiscount(0.15)
                                            .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                            .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                            .addFilter(
                                                TransformPriceFilter.builder()
                                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                                    .operator(
                                                        TransformPriceFilter.Operator.INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .reason("reason")
                                            .build()
                                    )
                                    .externalPriceId("external_price_id")
                                    .fixedPriceQuantity(0.0)
                                    .invoicingCycleConfiguration(
                                        BillingCycleConfiguration.builder()
                                            .duration(0L)
                                            .durationUnit(
                                                BillingCycleConfiguration.DurationUnit.DAY
                                            )
                                            .build()
                                    )
                                    .item(ItemSlim.builder().id("id").name("name").build())
                                    .maximum(
                                        Maximum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                TransformPriceFilter.builder()
                                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                                    .operator(
                                                        TransformPriceFilter.Operator.INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .maximumAmount("maximum_amount")
                                            .build()
                                    )
                                    .maximumAmount("maximum_amount")
                                    .metadata(
                                        Price.Unit.Metadata.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .minimum(
                                        Minimum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                TransformPriceFilter.builder()
                                                    .field(TransformPriceFilter.Field.PRICE_ID)
                                                    .operator(
                                                        TransformPriceFilter.Operator.INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .minimumAmount("minimum_amount")
                                            .build()
                                    )
                                    .minimumAmount("minimum_amount")
                                    .name("name")
                                    .planPhaseOrder(0L)
                                    .priceType(Price.Unit.PriceType.USAGE_PRICE)
                                    .replacesPriceId("replaces_price_id")
                                    .unitConfig(
                                        UnitConfig.builder()
                                            .unitAmount("unit_amount")
                                            .scalingFactor(0.0)
                                            .build()
                                    )
                                    .dimensionalPriceConfiguration(
                                        DimensionalPriceConfiguration.builder()
                                            .addDimensionValue("string")
                                            .dimensionalPriceGroupId("dimensional_price_group_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .priceId("price_id")
                            .subtotal("subtotal")
                            .total("total")
                            .quantity(0.0)
                            .build()
                    )
                    .subtotal("subtotal")
                    .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .total("total")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerCostListByExternalIdResponse =
            CustomerCostListByExternalIdResponse.builder()
                .addData(
                    AggregatedCost.builder()
                        .addPerPriceCost(
                            PerPriceCost.builder()
                                .price(
                                    Price.Unit.builder()
                                        .id("id")
                                        .billableMetric(
                                            BillableMetricTiny.builder().id("id").build()
                                        )
                                        .billingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .cadence(Price.Unit.Cadence.ONE_TIME)
                                        .addCompositePriceFilter(
                                            TransformPriceFilter.builder()
                                                .field(TransformPriceFilter.Field.PRICE_ID)
                                                .operator(TransformPriceFilter.Operator.INCLUDES)
                                                .addValue("string")
                                                .build()
                                        )
                                        .conversionRate(0.0)
                                        .unitConversionRateConfig(
                                            ConversionRateUnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .creditAllocation(
                                            Allocation.builder()
                                                .allowsRollover(true)
                                                .currency("currency")
                                                .customExpiration(
                                                    CustomExpiration.builder()
                                                        .duration(0L)
                                                        .durationUnit(
                                                            CustomExpiration.DurationUnit.DAY
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .currency("currency")
                                        .discount(
                                            PercentageDiscount.builder()
                                                .discountType(
                                                    PercentageDiscount.DiscountType.PERCENTAGE
                                                )
                                                .percentageDiscount(0.15)
                                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .reason("reason")
                                                .build()
                                        )
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(0.0)
                                        .invoicingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .item(ItemSlim.builder().id("id").name("name").build())
                                        .maximum(
                                            Maximum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .maximumAmount("maximum_amount")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .metadata(
                                            Price.Unit.Metadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .minimum(
                                            Minimum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    TransformPriceFilter.builder()
                                                        .field(TransformPriceFilter.Field.PRICE_ID)
                                                        .operator(
                                                            TransformPriceFilter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .minimumAmount("minimum_amount")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .name("name")
                                        .planPhaseOrder(0L)
                                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                                        .replacesPriceId("replaces_price_id")
                                        .unitConfig(
                                            UnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .scalingFactor(0.0)
                                                .build()
                                        )
                                        .dimensionalPriceConfiguration(
                                            DimensionalPriceConfiguration.builder()
                                                .addDimensionValue("string")
                                                .dimensionalPriceGroupId(
                                                    "dimensional_price_group_id"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .priceId("price_id")
                                .subtotal("subtotal")
                                .total("total")
                                .quantity(0.0)
                                .build()
                        )
                        .subtotal("subtotal")
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("total")
                        .build()
                )
                .build()

        val roundtrippedCustomerCostListByExternalIdResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCostListByExternalIdResponse),
                jacksonTypeRef<CustomerCostListByExternalIdResponse>(),
            )

        assertThat(roundtrippedCustomerCostListByExternalIdResponse)
            .isEqualTo(customerCostListByExternalIdResponse)
    }
}
