// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerCreditLedgerIncrementedWebhookEventTest {

    @Test
    fun create() {
        val customerCreditLedgerIncrementedWebhookEvent =
            CustomerCreditLedgerIncrementedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.builder()
                        .block(
                            CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block.builder()
                                .id("id")
                                .balance("balance")
                                .creditBlockSource(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditBlockSource
                                        .ALLOCATION
                                )
                                .effectiveDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addFilter(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Filter
                                        .builder()
                                        .field(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .Filter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .Filter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .maximumInitialBalance("maximum_initial_balance")
                                .metadata(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .perUnitCostBasis("per_unit_cost_basis")
                                .status(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Status
                                        .ACTIVE
                                )
                                .creditAllocation(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditAllocation
                                        .builder()
                                        .allowsRollover(true)
                                        .currency("currency")
                                        .customExpiration(
                                            CustomExpiration.builder()
                                                .duration(0L)
                                                .durationUnit(CustomExpiration.DurationUnit.DAY)
                                                .build()
                                        )
                                        .itemId("item_id")
                                        .addFilter(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .CreditAllocation
                                                .Filter
                                                .builder()
                                                .field(
                                                    CustomerCreditLedgerIncrementedWebhookEvent
                                                        .Properties
                                                        .Block
                                                        .CreditAllocation
                                                        .Filter
                                                        .Field
                                                        .PRICE_ID
                                                )
                                                .operator(
                                                    CustomerCreditLedgerIncrementedWebhookEvent
                                                        .Properties
                                                        .Block
                                                        .CreditAllocation
                                                        .Filter
                                                        .Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .licenseTypeId("license_type_id")
                                        .build()
                                )
                                .creditCommitment(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditCommitment
                                        .builder()
                                        .id("id")
                                        .subscriptionId("subscription_id")
                                        .build()
                                )
                                .build()
                        )
                        .pricingUnit(
                            CustomerCreditLedgerIncrementedWebhookEvent.Properties.PricingUnit
                                .builder()
                                .id("id")
                                .displayName("display_name")
                                .name("name")
                                .symbol("symbol")
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerCreditLedgerIncrementedWebhookEvent.Type
                        .CUSTOMER_CREDIT_LEDGER_INCREMENTED
                )
                .build()

        assertThat(customerCreditLedgerIncrementedWebhookEvent.id()).isEqualTo("id")
        assertThat(customerCreditLedgerIncrementedWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(customerCreditLedgerIncrementedWebhookEvent.customer())
            .isEqualTo(
                Customer.builder()
                    .id("id")
                    .addAdditionalEmail("string")
                    .autoCollection(true)
                    .autoIssuance(true)
                    .balance("balance")
                    .billingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .email("email")
                    .emailDelivery(true)
                    .exemptFromAutomatedTax(true)
                    .externalCustomerId("external_customer_id")
                    .hierarchy(
                        Customer.Hierarchy.builder()
                            .addChild(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .parent(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .build()
                    )
                    .metadata(
                        Customer.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                    .paymentProviderId("payment_provider_id")
                    .portalUrl("portal_url")
                    .shippingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .taxId(
                        CustomerTaxId.builder()
                            .country(CustomerTaxId.Country.AD)
                            .type(CustomerTaxId.Type.AD_NRT)
                            .value("value")
                            .build()
                    )
                    .timezone("timezone")
                    .accountingSyncConfiguration(
                        Customer.AccountingSyncConfiguration.builder()
                            .addAccountingProvider(
                                Customer.AccountingSyncConfiguration.AccountingProvider.builder()
                                    .externalProviderId("external_provider_id")
                                    .providerType(
                                        Customer.AccountingSyncConfiguration.AccountingProvider
                                            .ProviderType
                                            .QUICKBOOKS
                                    )
                                    .build()
                            )
                            .excluded(true)
                            .build()
                    )
                    .automaticTaxEnabled(true)
                    .defaultPaymentMethod(
                        Customer.DefaultPaymentMethod.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customer_id")
                            .default_(true)
                            .externalPaymentMethodId("external_payment_method_id")
                            .paymentMethodType(Customer.DefaultPaymentMethod.PaymentMethodType.CARD)
                            .providerType("provider_type")
                            .build()
                    )
                    .paymentConfiguration(
                        Customer.PaymentConfiguration.builder()
                            .addPaymentProvider(
                                Customer.PaymentConfiguration.PaymentProvider.builder()
                                    .providerType(
                                        Customer.PaymentConfiguration.PaymentProvider.ProviderType
                                            .STRIPE
                                    )
                                    .defaultSharedPaymentToken("default_shared_payment_token")
                                    .addExcludedPaymentMethodType("string")
                                    .build()
                            )
                            .build()
                    )
                    .reportingConfiguration(
                        Customer.ReportingConfiguration.builder().exempt(true).build()
                    )
                    .build()
            )
        assertThat(customerCreditLedgerIncrementedWebhookEvent.properties())
            .isEqualTo(
                CustomerCreditLedgerIncrementedWebhookEvent.Properties.builder()
                    .block(
                        CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block.builder()
                            .id("id")
                            .balance("balance")
                            .creditBlockSource(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                    .CreditBlockSource
                                    .ALLOCATION
                            )
                            .effectiveDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addFilter(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block.Filter
                                    .builder()
                                    .field(
                                        CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                            .Filter
                                            .Field
                                            .PRICE_ID
                                    )
                                    .operator(
                                        CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                            .Filter
                                            .Operator
                                            .INCLUDES
                                    )
                                    .addValue("string")
                                    .build()
                            )
                            .maximumInitialBalance("maximum_initial_balance")
                            .metadata(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                    .Metadata
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .perUnitCostBasis("per_unit_cost_basis")
                            .status(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block.Status
                                    .ACTIVE
                            )
                            .creditAllocation(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                    .CreditAllocation
                                    .builder()
                                    .allowsRollover(true)
                                    .currency("currency")
                                    .customExpiration(
                                        CustomExpiration.builder()
                                            .duration(0L)
                                            .durationUnit(CustomExpiration.DurationUnit.DAY)
                                            .build()
                                    )
                                    .itemId("item_id")
                                    .addFilter(
                                        CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                            .CreditAllocation
                                            .Filter
                                            .builder()
                                            .field(
                                                CustomerCreditLedgerIncrementedWebhookEvent
                                                    .Properties
                                                    .Block
                                                    .CreditAllocation
                                                    .Filter
                                                    .Field
                                                    .PRICE_ID
                                            )
                                            .operator(
                                                CustomerCreditLedgerIncrementedWebhookEvent
                                                    .Properties
                                                    .Block
                                                    .CreditAllocation
                                                    .Filter
                                                    .Operator
                                                    .INCLUDES
                                            )
                                            .addValue("string")
                                            .build()
                                    )
                                    .licenseTypeId("license_type_id")
                                    .build()
                            )
                            .creditCommitment(
                                CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                    .CreditCommitment
                                    .builder()
                                    .id("id")
                                    .subscriptionId("subscription_id")
                                    .build()
                            )
                            .build()
                    )
                    .pricingUnit(
                        CustomerCreditLedgerIncrementedWebhookEvent.Properties.PricingUnit.builder()
                            .id("id")
                            .displayName("display_name")
                            .name("name")
                            .symbol("symbol")
                            .build()
                    )
                    .build()
            )
        assertThat(customerCreditLedgerIncrementedWebhookEvent.type())
            .isEqualTo(
                CustomerCreditLedgerIncrementedWebhookEvent.Type.CUSTOMER_CREDIT_LEDGER_INCREMENTED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerIncrementedWebhookEvent =
            CustomerCreditLedgerIncrementedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.builder()
                        .block(
                            CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block.builder()
                                .id("id")
                                .balance("balance")
                                .creditBlockSource(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditBlockSource
                                        .ALLOCATION
                                )
                                .effectiveDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addFilter(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Filter
                                        .builder()
                                        .field(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .Filter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .Filter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .maximumInitialBalance("maximum_initial_balance")
                                .metadata(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .perUnitCostBasis("per_unit_cost_basis")
                                .status(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .Status
                                        .ACTIVE
                                )
                                .creditAllocation(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditAllocation
                                        .builder()
                                        .allowsRollover(true)
                                        .currency("currency")
                                        .customExpiration(
                                            CustomExpiration.builder()
                                                .duration(0L)
                                                .durationUnit(CustomExpiration.DurationUnit.DAY)
                                                .build()
                                        )
                                        .itemId("item_id")
                                        .addFilter(
                                            CustomerCreditLedgerIncrementedWebhookEvent.Properties
                                                .Block
                                                .CreditAllocation
                                                .Filter
                                                .builder()
                                                .field(
                                                    CustomerCreditLedgerIncrementedWebhookEvent
                                                        .Properties
                                                        .Block
                                                        .CreditAllocation
                                                        .Filter
                                                        .Field
                                                        .PRICE_ID
                                                )
                                                .operator(
                                                    CustomerCreditLedgerIncrementedWebhookEvent
                                                        .Properties
                                                        .Block
                                                        .CreditAllocation
                                                        .Filter
                                                        .Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .licenseTypeId("license_type_id")
                                        .build()
                                )
                                .creditCommitment(
                                    CustomerCreditLedgerIncrementedWebhookEvent.Properties.Block
                                        .CreditCommitment
                                        .builder()
                                        .id("id")
                                        .subscriptionId("subscription_id")
                                        .build()
                                )
                                .build()
                        )
                        .pricingUnit(
                            CustomerCreditLedgerIncrementedWebhookEvent.Properties.PricingUnit
                                .builder()
                                .id("id")
                                .displayName("display_name")
                                .name("name")
                                .symbol("symbol")
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerCreditLedgerIncrementedWebhookEvent.Type
                        .CUSTOMER_CREDIT_LEDGER_INCREMENTED
                )
                .build()

        val roundtrippedCustomerCreditLedgerIncrementedWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerIncrementedWebhookEvent),
                jacksonTypeRef<CustomerCreditLedgerIncrementedWebhookEvent>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerIncrementedWebhookEvent)
            .isEqualTo(customerCreditLedgerIncrementedWebhookEvent)
    }
}
