// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.core.JsonValue
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class CustomerModelTest {

    @Test
    fun createCustomerModel() {
        val customerModel =
            CustomerModel.builder()
                .id("id")
                .addAdditionalEmail("string")
                .autoCollection(true)
                .balance("balance")
                .billingAddress(
                    AddressModel.builder()
                        .city("city")
                        .country("country")
                        .line1("line1")
                        .line2("line2")
                        .postalCode("postal_code")
                        .state("state")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .currency("currency")
                .email("email")
                .emailDelivery(true)
                .exemptFromAutomatedTax(true)
                .externalCustomerId("external_customer_id")
                .hierarchy(
                    CustomerModel.Hierarchy.builder()
                        .addChild(
                            CustomerMinifiedModel.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .parent(
                            CustomerMinifiedModel.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .build()
                )
                .metadata(
                    CustomerModel.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .name("name")
                .paymentProvider(CustomerModel.PaymentProvider.QUICKBOOKS)
                .paymentProviderId("payment_provider_id")
                .portalUrl("portal_url")
                .shippingAddress(
                    AddressModel.builder()
                        .city("city")
                        .country("country")
                        .line1("line1")
                        .line2("line2")
                        .postalCode("postal_code")
                        .state("state")
                        .build()
                )
                .taxId(
                    CustomerTaxIdModel.builder()
                        .country(CustomerTaxIdModel.Country.AD)
                        .type(CustomerTaxIdModel.Type.AD_NRT)
                        .value("value")
                        .build()
                )
                .timezone("timezone")
                .accountingSyncConfiguration(
                    CustomerModel.AccountingSyncConfiguration.builder()
                        .addAccountingProvider(
                            CustomerModel.AccountingSyncConfiguration.AccountingProvider.builder()
                                .externalProviderId("external_provider_id")
                                .providerType(
                                    CustomerModel.AccountingSyncConfiguration.AccountingProvider
                                        .ProviderType
                                        .QUICKBOOKS
                                )
                                .build()
                        )
                        .excluded(true)
                        .build()
                )
                .reportingConfiguration(
                    CustomerModel.ReportingConfiguration.builder().exempt(true).build()
                )
                .build()
        assertThat(customerModel).isNotNull
        assertThat(customerModel.id()).isEqualTo("id")
        assertThat(customerModel.additionalEmails()).containsExactly("string")
        assertThat(customerModel.autoCollection()).isEqualTo(true)
        assertThat(customerModel.balance()).isEqualTo("balance")
        assertThat(customerModel.billingAddress())
            .contains(
                AddressModel.builder()
                    .city("city")
                    .country("country")
                    .line1("line1")
                    .line2("line2")
                    .postalCode("postal_code")
                    .state("state")
                    .build()
            )
        assertThat(customerModel.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(customerModel.currency()).contains("currency")
        assertThat(customerModel.email()).isEqualTo("email")
        assertThat(customerModel.emailDelivery()).isEqualTo(true)
        assertThat(customerModel.exemptFromAutomatedTax()).contains(true)
        assertThat(customerModel.externalCustomerId()).contains("external_customer_id")
        assertThat(customerModel.hierarchy())
            .isEqualTo(
                CustomerModel.Hierarchy.builder()
                    .addChild(
                        CustomerMinifiedModel.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .parent(
                        CustomerMinifiedModel.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .build()
            )
        assertThat(customerModel.metadata())
            .isEqualTo(
                CustomerModel.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(customerModel.name()).isEqualTo("name")
        assertThat(customerModel.paymentProvider())
            .contains(CustomerModel.PaymentProvider.QUICKBOOKS)
        assertThat(customerModel.paymentProviderId()).contains("payment_provider_id")
        assertThat(customerModel.portalUrl()).contains("portal_url")
        assertThat(customerModel.shippingAddress())
            .contains(
                AddressModel.builder()
                    .city("city")
                    .country("country")
                    .line1("line1")
                    .line2("line2")
                    .postalCode("postal_code")
                    .state("state")
                    .build()
            )
        assertThat(customerModel.taxId())
            .contains(
                CustomerTaxIdModel.builder()
                    .country(CustomerTaxIdModel.Country.AD)
                    .type(CustomerTaxIdModel.Type.AD_NRT)
                    .value("value")
                    .build()
            )
        assertThat(customerModel.timezone()).isEqualTo("timezone")
        assertThat(customerModel.accountingSyncConfiguration())
            .contains(
                CustomerModel.AccountingSyncConfiguration.builder()
                    .addAccountingProvider(
                        CustomerModel.AccountingSyncConfiguration.AccountingProvider.builder()
                            .externalProviderId("external_provider_id")
                            .providerType(
                                CustomerModel.AccountingSyncConfiguration.AccountingProvider
                                    .ProviderType
                                    .QUICKBOOKS
                            )
                            .build()
                    )
                    .excluded(true)
                    .build()
            )
        assertThat(customerModel.reportingConfiguration())
            .contains(CustomerModel.ReportingConfiguration.builder().exempt(true).build())
    }
}
