// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerBalanceTransactionCreatedWebhookEventTest {

    @Test
    fun create() {
        val customerBalanceTransactionCreatedWebhookEvent =
            CustomerBalanceTransactionCreatedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerBalanceTransactionCreatedWebhookEvent.Properties.builder()
                        .balanceTransaction(
                            CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                .BalanceTransaction
                                .builder()
                                .id("cgZa3SXcsPTVyC4Y")
                                .action(
                                    CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                        .BalanceTransaction
                                        .Action
                                        .APPLIED_TO_INVOICE
                                )
                                .amount("11.00")
                                .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .creditNote(CreditNoteTiny.builder().id("id").build())
                                .description("An optional description")
                                .endingBalance("22.00")
                                .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                                .startingBalance("33.00")
                                .type(
                                    CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                        .BalanceTransaction
                                        .Type
                                        .INCREMENT
                                )
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerBalanceTransactionCreatedWebhookEvent.Type
                        .CUSTOMER_BALANCE_TRANSACTION_CREATED
                )
                .build()

        assertThat(customerBalanceTransactionCreatedWebhookEvent.id()).isEqualTo("id")
        assertThat(customerBalanceTransactionCreatedWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(customerBalanceTransactionCreatedWebhookEvent.customer())
            .isEqualTo(
                Customer.builder()
                    .id("id")
                    .addAdditionalEmail("string")
                    .autoCollection(true)
                    .autoIssuance(true)
                    .balance("balance")
                    .billingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .email("email")
                    .emailDelivery(true)
                    .exemptFromAutomatedTax(true)
                    .externalCustomerId("external_customer_id")
                    .hierarchy(
                        Customer.Hierarchy.builder()
                            .addChild(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .parent(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .build()
                    )
                    .metadata(
                        Customer.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                    .paymentProviderId("payment_provider_id")
                    .portalUrl("portal_url")
                    .shippingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .taxId(
                        CustomerTaxId.builder()
                            .country(CustomerTaxId.Country.AD)
                            .type(CustomerTaxId.Type.AD_NRT)
                            .value("value")
                            .build()
                    )
                    .timezone("timezone")
                    .accountingSyncConfiguration(
                        Customer.AccountingSyncConfiguration.builder()
                            .addAccountingProvider(
                                Customer.AccountingSyncConfiguration.AccountingProvider.builder()
                                    .externalProviderId("external_provider_id")
                                    .providerType(
                                        Customer.AccountingSyncConfiguration.AccountingProvider
                                            .ProviderType
                                            .QUICKBOOKS
                                    )
                                    .build()
                            )
                            .excluded(true)
                            .build()
                    )
                    .automaticTaxEnabled(true)
                    .defaultPaymentMethod(
                        Customer.DefaultPaymentMethod.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customer_id")
                            .default_(true)
                            .externalPaymentMethodId("external_payment_method_id")
                            .paymentMethodType(Customer.DefaultPaymentMethod.PaymentMethodType.CARD)
                            .providerType("provider_type")
                            .build()
                    )
                    .paymentConfiguration(
                        Customer.PaymentConfiguration.builder()
                            .addPaymentProvider(
                                Customer.PaymentConfiguration.PaymentProvider.builder()
                                    .providerType(
                                        Customer.PaymentConfiguration.PaymentProvider.ProviderType
                                            .STRIPE
                                    )
                                    .defaultSharedPaymentToken("default_shared_payment_token")
                                    .addExcludedPaymentMethodType("string")
                                    .build()
                            )
                            .build()
                    )
                    .reportingConfiguration(
                        Customer.ReportingConfiguration.builder().exempt(true).build()
                    )
                    .build()
            )
        assertThat(customerBalanceTransactionCreatedWebhookEvent.properties())
            .isEqualTo(
                CustomerBalanceTransactionCreatedWebhookEvent.Properties.builder()
                    .balanceTransaction(
                        CustomerBalanceTransactionCreatedWebhookEvent.Properties.BalanceTransaction
                            .builder()
                            .id("cgZa3SXcsPTVyC4Y")
                            .action(
                                CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                    .BalanceTransaction
                                    .Action
                                    .APPLIED_TO_INVOICE
                            )
                            .amount("11.00")
                            .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                            .creditNote(CreditNoteTiny.builder().id("id").build())
                            .description("An optional description")
                            .endingBalance("22.00")
                            .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                            .startingBalance("33.00")
                            .type(
                                CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                    .BalanceTransaction
                                    .Type
                                    .INCREMENT
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(customerBalanceTransactionCreatedWebhookEvent.type())
            .isEqualTo(
                CustomerBalanceTransactionCreatedWebhookEvent.Type
                    .CUSTOMER_BALANCE_TRANSACTION_CREATED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerBalanceTransactionCreatedWebhookEvent =
            CustomerBalanceTransactionCreatedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerBalanceTransactionCreatedWebhookEvent.Properties.builder()
                        .balanceTransaction(
                            CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                .BalanceTransaction
                                .builder()
                                .id("cgZa3SXcsPTVyC4Y")
                                .action(
                                    CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                        .BalanceTransaction
                                        .Action
                                        .APPLIED_TO_INVOICE
                                )
                                .amount("11.00")
                                .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .creditNote(CreditNoteTiny.builder().id("id").build())
                                .description("An optional description")
                                .endingBalance("22.00")
                                .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                                .startingBalance("33.00")
                                .type(
                                    CustomerBalanceTransactionCreatedWebhookEvent.Properties
                                        .BalanceTransaction
                                        .Type
                                        .INCREMENT
                                )
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerBalanceTransactionCreatedWebhookEvent.Type
                        .CUSTOMER_BALANCE_TRANSACTION_CREATED
                )
                .build()

        val roundtrippedCustomerBalanceTransactionCreatedWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerBalanceTransactionCreatedWebhookEvent),
                jacksonTypeRef<CustomerBalanceTransactionCreatedWebhookEvent>(),
            )

        assertThat(roundtrippedCustomerBalanceTransactionCreatedWebhookEvent)
            .isEqualTo(customerBalanceTransactionCreatedWebhookEvent)
    }
}
