// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerCostListResponseTest {

    @Test
    fun create() {
        val customerCostListResponse =
            CustomerCostListResponse.builder()
                .addData(
                    AggregatedCost.builder()
                        .addPerPriceCost(
                            PerPriceCost.builder()
                                .price(
                                    Price.UnitPrice.builder()
                                        .id("id")
                                        .billableMetric(
                                            BillableMetricTiny.builder().id("id").build()
                                        )
                                        .billingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .billingMode(Price.UnitPrice.BillingMode.IN_ADVANCE)
                                        .cadence(Price.UnitPrice.Cadence.ONE_TIME)
                                        .addCompositePriceFilter(
                                            Price.UnitPrice.CompositePriceFilter.builder()
                                                .field(
                                                    Price.UnitPrice.CompositePriceFilter.Field
                                                        .PRICE_ID
                                                )
                                                .operator(
                                                    Price.UnitPrice.CompositePriceFilter.Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .conversionRate(0.0)
                                        .unitConversionRateConfig(
                                            ConversionRateUnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .creditAllocation(
                                            Allocation.builder()
                                                .allowsRollover(true)
                                                .currency("currency")
                                                .customExpiration(
                                                    CustomExpiration.builder()
                                                        .duration(0L)
                                                        .durationUnit(
                                                            CustomExpiration.DurationUnit.DAY
                                                        )
                                                        .build()
                                                )
                                                .addFilter(
                                                    Allocation.Filter.builder()
                                                        .field(Allocation.Filter.Field.PRICE_ID)
                                                        .operator(
                                                            Allocation.Filter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .currency("currency")
                                        .discount(
                                            PercentageDiscount.builder()
                                                .discountType(
                                                    PercentageDiscount.DiscountType.PERCENTAGE
                                                )
                                                .percentageDiscount(0.15)
                                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                .addFilter(
                                                    PercentageDiscount.Filter.builder()
                                                        .field(
                                                            PercentageDiscount.Filter.Field.PRICE_ID
                                                        )
                                                        .operator(
                                                            PercentageDiscount.Filter.Operator
                                                                .INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .reason("reason")
                                                .build()
                                        )
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(0.0)
                                        .invoicingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .item(ItemSlim.builder().id("id").name("name").build())
                                        .maximum(
                                            Maximum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Maximum.Filter.builder()
                                                        .field(Maximum.Filter.Field.PRICE_ID)
                                                        .operator(Maximum.Filter.Operator.INCLUDES)
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .maximumAmount("maximum_amount")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .metadata(
                                            Price.UnitPrice.Metadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .minimum(
                                            Minimum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Minimum.Filter.builder()
                                                        .field(Minimum.Filter.Field.PRICE_ID)
                                                        .operator(Minimum.Filter.Operator.INCLUDES)
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .minimumAmount("minimum_amount")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .name("name")
                                        .planPhaseOrder(0L)
                                        .priceType(Price.UnitPrice.PriceType.USAGE_PRICE)
                                        .replacesPriceId("replaces_price_id")
                                        .unitConfig(
                                            UnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .prorated(true)
                                                .build()
                                        )
                                        .dimensionalPriceConfiguration(
                                            DimensionalPriceConfiguration.builder()
                                                .addDimensionValue("string")
                                                .dimensionalPriceGroupId(
                                                    "dimensional_price_group_id"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .priceId("price_id")
                                .subtotal("subtotal")
                                .total("total")
                                .quantity(0.0)
                                .build()
                        )
                        .subtotal("subtotal")
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("total")
                        .build()
                )
                .build()

        assertThat(customerCostListResponse.data())
            .containsExactly(
                AggregatedCost.builder()
                    .addPerPriceCost(
                        PerPriceCost.builder()
                            .price(
                                Price.UnitPrice.builder()
                                    .id("id")
                                    .billableMetric(BillableMetricTiny.builder().id("id").build())
                                    .billingCycleConfiguration(
                                        BillingCycleConfiguration.builder()
                                            .duration(0L)
                                            .durationUnit(
                                                BillingCycleConfiguration.DurationUnit.DAY
                                            )
                                            .build()
                                    )
                                    .billingMode(Price.UnitPrice.BillingMode.IN_ADVANCE)
                                    .cadence(Price.UnitPrice.Cadence.ONE_TIME)
                                    .addCompositePriceFilter(
                                        Price.UnitPrice.CompositePriceFilter.builder()
                                            .field(
                                                Price.UnitPrice.CompositePriceFilter.Field.PRICE_ID
                                            )
                                            .operator(
                                                Price.UnitPrice.CompositePriceFilter.Operator
                                                    .INCLUDES
                                            )
                                            .addValue("string")
                                            .build()
                                    )
                                    .conversionRate(0.0)
                                    .unitConversionRateConfig(
                                        ConversionRateUnitConfig.builder()
                                            .unitAmount("unit_amount")
                                            .build()
                                    )
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .creditAllocation(
                                        Allocation.builder()
                                            .allowsRollover(true)
                                            .currency("currency")
                                            .customExpiration(
                                                CustomExpiration.builder()
                                                    .duration(0L)
                                                    .durationUnit(CustomExpiration.DurationUnit.DAY)
                                                    .build()
                                            )
                                            .addFilter(
                                                Allocation.Filter.builder()
                                                    .field(Allocation.Filter.Field.PRICE_ID)
                                                    .operator(Allocation.Filter.Operator.INCLUDES)
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .currency("currency")
                                    .discount(
                                        PercentageDiscount.builder()
                                            .discountType(
                                                PercentageDiscount.DiscountType.PERCENTAGE
                                            )
                                            .percentageDiscount(0.15)
                                            .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                            .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                            .addFilter(
                                                PercentageDiscount.Filter.builder()
                                                    .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                                    .operator(
                                                        PercentageDiscount.Filter.Operator.INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .reason("reason")
                                            .build()
                                    )
                                    .externalPriceId("external_price_id")
                                    .fixedPriceQuantity(0.0)
                                    .invoicingCycleConfiguration(
                                        BillingCycleConfiguration.builder()
                                            .duration(0L)
                                            .durationUnit(
                                                BillingCycleConfiguration.DurationUnit.DAY
                                            )
                                            .build()
                                    )
                                    .item(ItemSlim.builder().id("id").name("name").build())
                                    .maximum(
                                        Maximum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                Maximum.Filter.builder()
                                                    .field(Maximum.Filter.Field.PRICE_ID)
                                                    .operator(Maximum.Filter.Operator.INCLUDES)
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .maximumAmount("maximum_amount")
                                            .build()
                                    )
                                    .maximumAmount("maximum_amount")
                                    .metadata(
                                        Price.UnitPrice.Metadata.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("string"))
                                            .build()
                                    )
                                    .minimum(
                                        Minimum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                Minimum.Filter.builder()
                                                    .field(Minimum.Filter.Field.PRICE_ID)
                                                    .operator(Minimum.Filter.Operator.INCLUDES)
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .minimumAmount("minimum_amount")
                                            .build()
                                    )
                                    .minimumAmount("minimum_amount")
                                    .name("name")
                                    .planPhaseOrder(0L)
                                    .priceType(Price.UnitPrice.PriceType.USAGE_PRICE)
                                    .replacesPriceId("replaces_price_id")
                                    .unitConfig(
                                        UnitConfig.builder()
                                            .unitAmount("unit_amount")
                                            .prorated(true)
                                            .build()
                                    )
                                    .dimensionalPriceConfiguration(
                                        DimensionalPriceConfiguration.builder()
                                            .addDimensionValue("string")
                                            .dimensionalPriceGroupId("dimensional_price_group_id")
                                            .build()
                                    )
                                    .build()
                            )
                            .priceId("price_id")
                            .subtotal("subtotal")
                            .total("total")
                            .quantity(0.0)
                            .build()
                    )
                    .subtotal("subtotal")
                    .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .total("total")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerCostListResponse =
            CustomerCostListResponse.builder()
                .addData(
                    AggregatedCost.builder()
                        .addPerPriceCost(
                            PerPriceCost.builder()
                                .price(
                                    Price.UnitPrice.builder()
                                        .id("id")
                                        .billableMetric(
                                            BillableMetricTiny.builder().id("id").build()
                                        )
                                        .billingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .billingMode(Price.UnitPrice.BillingMode.IN_ADVANCE)
                                        .cadence(Price.UnitPrice.Cadence.ONE_TIME)
                                        .addCompositePriceFilter(
                                            Price.UnitPrice.CompositePriceFilter.builder()
                                                .field(
                                                    Price.UnitPrice.CompositePriceFilter.Field
                                                        .PRICE_ID
                                                )
                                                .operator(
                                                    Price.UnitPrice.CompositePriceFilter.Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .conversionRate(0.0)
                                        .unitConversionRateConfig(
                                            ConversionRateUnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .creditAllocation(
                                            Allocation.builder()
                                                .allowsRollover(true)
                                                .currency("currency")
                                                .customExpiration(
                                                    CustomExpiration.builder()
                                                        .duration(0L)
                                                        .durationUnit(
                                                            CustomExpiration.DurationUnit.DAY
                                                        )
                                                        .build()
                                                )
                                                .addFilter(
                                                    Allocation.Filter.builder()
                                                        .field(Allocation.Filter.Field.PRICE_ID)
                                                        .operator(
                                                            Allocation.Filter.Operator.INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .currency("currency")
                                        .discount(
                                            PercentageDiscount.builder()
                                                .discountType(
                                                    PercentageDiscount.DiscountType.PERCENTAGE
                                                )
                                                .percentageDiscount(0.15)
                                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                .addFilter(
                                                    PercentageDiscount.Filter.builder()
                                                        .field(
                                                            PercentageDiscount.Filter.Field.PRICE_ID
                                                        )
                                                        .operator(
                                                            PercentageDiscount.Filter.Operator
                                                                .INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .reason("reason")
                                                .build()
                                        )
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(0.0)
                                        .invoicingCycleConfiguration(
                                            BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    BillingCycleConfiguration.DurationUnit.DAY
                                                )
                                                .build()
                                        )
                                        .item(ItemSlim.builder().id("id").name("name").build())
                                        .maximum(
                                            Maximum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Maximum.Filter.builder()
                                                        .field(Maximum.Filter.Field.PRICE_ID)
                                                        .operator(Maximum.Filter.Operator.INCLUDES)
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .maximumAmount("maximum_amount")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .metadata(
                                            Price.UnitPrice.Metadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .minimum(
                                            Minimum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Minimum.Filter.builder()
                                                        .field(Minimum.Filter.Field.PRICE_ID)
                                                        .operator(Minimum.Filter.Operator.INCLUDES)
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .minimumAmount("minimum_amount")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .name("name")
                                        .planPhaseOrder(0L)
                                        .priceType(Price.UnitPrice.PriceType.USAGE_PRICE)
                                        .replacesPriceId("replaces_price_id")
                                        .unitConfig(
                                            UnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .prorated(true)
                                                .build()
                                        )
                                        .dimensionalPriceConfiguration(
                                            DimensionalPriceConfiguration.builder()
                                                .addDimensionValue("string")
                                                .dimensionalPriceGroupId(
                                                    "dimensional_price_group_id"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .priceId("price_id")
                                .subtotal("subtotal")
                                .total("total")
                                .quantity(0.0)
                                .build()
                        )
                        .subtotal("subtotal")
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("total")
                        .build()
                )
                .build()

        val roundtrippedCustomerCostListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCostListResponse),
                jacksonTypeRef<CustomerCostListResponse>(),
            )

        assertThat(roundtrippedCustomerCostListResponse).isEqualTo(customerCostListResponse)
    }
}
