// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerCreditBalanceDepletedWebhookEventTest {

    @Test
    fun create() {
        val customerCreditBalanceDepletedWebhookEvent =
            CustomerCreditBalanceDepletedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerCreditBalanceDepletedWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            CustomerCreditBalanceDepletedWebhookEvent.Properties.AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .pricingUnit(
                            CustomerCreditBalanceDepletedWebhookEvent.Properties.PricingUnit
                                .builder()
                                .id("id")
                                .displayName("display_name")
                                .name("name")
                                .symbol("symbol")
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerCreditBalanceDepletedWebhookEvent.Type.CUSTOMER_CREDIT_BALANCE_DEPLETED
                )
                .build()

        assertThat(customerCreditBalanceDepletedWebhookEvent.id()).isEqualTo("id")
        assertThat(customerCreditBalanceDepletedWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(customerCreditBalanceDepletedWebhookEvent.customer())
            .isEqualTo(
                Customer.builder()
                    .id("id")
                    .addAdditionalEmail("string")
                    .autoCollection(true)
                    .autoIssuance(true)
                    .balance("balance")
                    .billingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .email("email")
                    .emailDelivery(true)
                    .exemptFromAutomatedTax(true)
                    .externalCustomerId("external_customer_id")
                    .hierarchy(
                        Customer.Hierarchy.builder()
                            .addChild(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .parent(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .build()
                    )
                    .metadata(
                        Customer.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                    .paymentProviderId("payment_provider_id")
                    .portalUrl("portal_url")
                    .shippingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .taxId(
                        CustomerTaxId.builder()
                            .country(CustomerTaxId.Country.AD)
                            .type(CustomerTaxId.Type.AD_NRT)
                            .value("value")
                            .build()
                    )
                    .timezone("timezone")
                    .accountingSyncConfiguration(
                        Customer.AccountingSyncConfiguration.builder()
                            .addAccountingProvider(
                                Customer.AccountingSyncConfiguration.AccountingProvider.builder()
                                    .externalProviderId("external_provider_id")
                                    .providerType(
                                        Customer.AccountingSyncConfiguration.AccountingProvider
                                            .ProviderType
                                            .QUICKBOOKS
                                    )
                                    .build()
                            )
                            .excluded(true)
                            .build()
                    )
                    .automaticTaxEnabled(true)
                    .defaultPaymentMethod(
                        Customer.DefaultPaymentMethod.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customer_id")
                            .default_(true)
                            .externalPaymentMethodId("external_payment_method_id")
                            .paymentMethodType(Customer.DefaultPaymentMethod.PaymentMethodType.CARD)
                            .providerType("provider_type")
                            .build()
                    )
                    .paymentConfiguration(
                        Customer.PaymentConfiguration.builder()
                            .addPaymentProvider(
                                Customer.PaymentConfiguration.PaymentProvider.builder()
                                    .providerType(
                                        Customer.PaymentConfiguration.PaymentProvider.ProviderType
                                            .STRIPE
                                    )
                                    .defaultSharedPaymentToken("default_shared_payment_token")
                                    .addExcludedPaymentMethodType("string")
                                    .build()
                            )
                            .build()
                    )
                    .reportingConfiguration(
                        Customer.ReportingConfiguration.builder().exempt(true).build()
                    )
                    .build()
            )
        assertThat(customerCreditBalanceDepletedWebhookEvent.properties())
            .isEqualTo(
                CustomerCreditBalanceDepletedWebhookEvent.Properties.builder()
                    .alertConfiguration(
                        CustomerCreditBalanceDepletedWebhookEvent.Properties.AlertConfiguration
                            .builder()
                            .id("XuxCbt7x9L82yyeF")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .currency("currency")
                            .customer(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .enabled(true)
                            .metric(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Metric
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .plan(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Plan
                                    .builder()
                                    .id("m2t5akQeh2obwxeU")
                                    .externalPlanId("m2t5akQeh2obwxeU")
                                    .name("Example plan")
                                    .planVersion("plan_version")
                                    .build()
                            )
                            .subscription(
                                SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                            )
                            .addThreshold(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Threshold
                                    .builder()
                                    .value("value")
                                    .build()
                            )
                            .type(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Type
                                    .CREDIT_BALANCE_DEPLETED
                            )
                            .addBalanceAlertStatus(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .BalanceAlertStatus
                                    .builder()
                                    .inAlert(true)
                                    .thresholdValue("threshold_value")
                                    .build()
                            )
                            .addGroupingKey("string")
                            .licenseType(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .LicenseType
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .addPriceFilter(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .PriceFilter
                                    .builder()
                                    .field(
                                        CustomerCreditBalanceDepletedWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Field
                                            .PRICE_ID
                                    )
                                    .operator(
                                        CustomerCreditBalanceDepletedWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Operator
                                            .INCLUDES
                                    )
                                    .addValue("string")
                                    .build()
                            )
                            .addThresholdOverride(
                                CustomerCreditBalanceDepletedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .ThresholdOverride
                                    .builder()
                                    .addGroupValue("string")
                                    .addThreshold(
                                        CustomerCreditBalanceDepletedWebhookEvent.Properties
                                            .AlertConfiguration
                                            .ThresholdOverride
                                            .Threshold
                                            .builder()
                                            .value("value")
                                            .build()
                                    )
                                    .addGroupKey("string")
                                    .build()
                            )
                            .build()
                    )
                    .pricingUnit(
                        CustomerCreditBalanceDepletedWebhookEvent.Properties.PricingUnit.builder()
                            .id("id")
                            .displayName("display_name")
                            .name("name")
                            .symbol("symbol")
                            .build()
                    )
                    .build()
            )
        assertThat(customerCreditBalanceDepletedWebhookEvent.type())
            .isEqualTo(
                CustomerCreditBalanceDepletedWebhookEvent.Type.CUSTOMER_CREDIT_BALANCE_DEPLETED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditBalanceDepletedWebhookEvent =
            CustomerCreditBalanceDepletedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerCreditBalanceDepletedWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            CustomerCreditBalanceDepletedWebhookEvent.Properties.AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    CustomerCreditBalanceDepletedWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            CustomerCreditBalanceDepletedWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .pricingUnit(
                            CustomerCreditBalanceDepletedWebhookEvent.Properties.PricingUnit
                                .builder()
                                .id("id")
                                .displayName("display_name")
                                .name("name")
                                .symbol("symbol")
                                .build()
                        )
                        .build()
                )
                .type(
                    CustomerCreditBalanceDepletedWebhookEvent.Type.CUSTOMER_CREDIT_BALANCE_DEPLETED
                )
                .build()

        val roundtrippedCustomerCreditBalanceDepletedWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditBalanceDepletedWebhookEvent),
                jacksonTypeRef<CustomerCreditBalanceDepletedWebhookEvent>(),
            )

        assertThat(roundtrippedCustomerCreditBalanceDepletedWebhookEvent)
            .isEqualTo(customerCreditBalanceDepletedWebhookEvent)
    }
}
