// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import com.withorb.api.errors.OrbInvalidDataException
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.EnumSource

internal class CustomerCreditLedgerCreateEntryResponseTest {

    @Test
    fun ofIncrement() {
        val increment =
            CustomerCreditLedgerCreateEntryResponse.Increment.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.Increment.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.Increment.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.Increment.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.Increment.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .startingBalance(0.0)
                .addCreatedInvoice(
                    Invoice.builder()
                        .id("id")
                        .amountDue("8.00")
                        .autoCollection(
                            Invoice.AutoCollection.builder()
                                .enabled(true)
                                .nextAttemptAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .numAttempts(0L)
                                .previouslyAttemptedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .billingAddress(
                            Invoice.BillingAddress.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                        .addCreditNote(
                            Invoice.CreditNote.builder()
                                .id("id")
                                .creditNoteNumber("credit_note_number")
                                .memo("memo")
                                .reason("reason")
                                .total("total")
                                .type("type")
                                .voidedAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .build()
                        )
                        .currency("USD")
                        .customer(
                            Invoice.Customer.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .addCustomerBalanceTransaction(
                            Invoice.CustomerBalanceTransaction.builder()
                                .id("cgZa3SXcsPTVyC4Y")
                                .action(
                                    Invoice.CustomerBalanceTransaction.Action.APPLIED_TO_INVOICE
                                )
                                .amount("11.00")
                                .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .creditNote(
                                    Invoice.CustomerBalanceTransaction.CreditNote.builder()
                                        .id("id")
                                        .build()
                                )
                                .description("An optional description")
                                .endingBalance("22.00")
                                .invoice(
                                    Invoice.CustomerBalanceTransaction.InnerInvoice.builder()
                                        .id("gXcsPTVyC4YZa3Sc")
                                        .build()
                                )
                                .startingBalance("33.00")
                                .type(Invoice.CustomerBalanceTransaction.Type.INCREMENT)
                                .build()
                        )
                        .customerTaxId(
                            Invoice.CustomerTaxId.builder()
                                .country(Invoice.CustomerTaxId.Country.AD)
                                .type(Invoice.CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .discount(JsonValue.from(mapOf<String, Any>()))
                        .addDiscount(
                            PercentageDiscount.builder()
                                .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.15)
                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                .reason("reason")
                                .build()
                        )
                        .dueDate(OffsetDateTime.parse("2022-05-30T07:00:00+00:00"))
                        .eligibleToIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .hostedInvoiceUrl("hosted_invoice_url")
                        .invoiceDate(OffsetDateTime.parse("2022-05-01T07:00:00+00:00"))
                        .invoiceNumber("JYEFHK-00001")
                        .invoicePdf(
                            "https://assets.withorb.com/invoice/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                        )
                        .invoiceSource(Invoice.InvoiceSource.SUBSCRIPTION)
                        .issueFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addLineItem(
                            Invoice.LineItem.builder()
                                .id("id")
                                .adjustedSubtotal("5.00")
                                .addAdjustment(
                                    Invoice.LineItem.Adjustment.UsageDiscount.builder()
                                        .id("id")
                                        .amount("amount")
                                        .addAppliesToPriceId("string")
                                        .addFilter(
                                            Invoice.LineItem.Adjustment.UsageDiscount.Filter
                                                .builder()
                                                .field(
                                                    Invoice.LineItem.Adjustment.UsageDiscount.Filter
                                                        .Field
                                                        .PRICE_ID
                                                )
                                                .operator(
                                                    Invoice.LineItem.Adjustment.UsageDiscount.Filter
                                                        .Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .isInvoiceLevel(true)
                                        .reason("reason")
                                        .usageDiscount(0.0)
                                        .build()
                                )
                                .amount("7.00")
                                .creditsApplied("6.00")
                                .discount(
                                    PercentageDiscount.builder()
                                        .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                        .percentageDiscount(0.15)
                                        .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                        .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                        .reason("reason")
                                        .build()
                                )
                                .endDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                                .filter("filter")
                                .grouping("grouping")
                                .maximum(
                                    Invoice.LineItem.Maximum.builder()
                                        .addAppliesToPriceId("string")
                                        .addFilter(
                                            Invoice.LineItem.Maximum.Filter.builder()
                                                .field(
                                                    Invoice.LineItem.Maximum.Filter.Field.PRICE_ID
                                                )
                                                .operator(
                                                    Invoice.LineItem.Maximum.Filter.Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .build()
                                )
                                .maximumAmount("maximum_amount")
                                .minimum(
                                    Invoice.LineItem.Minimum.builder()
                                        .addAppliesToPriceId("string")
                                        .addFilter(
                                            Invoice.LineItem.Minimum.Filter.builder()
                                                .field(
                                                    Invoice.LineItem.Minimum.Filter.Field.PRICE_ID
                                                )
                                                .operator(
                                                    Invoice.LineItem.Minimum.Filter.Operator
                                                        .INCLUDES
                                                )
                                                .addValue("string")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .build()
                                )
                                .minimumAmount("minimum_amount")
                                .name("Fixed Fee")
                                .partiallyInvoicedAmount("4.00")
                                .price(
                                    Price.Unit.builder()
                                        .id("id")
                                        .billableMetric(
                                            Price.Unit.BillableMetric.builder().id("id").build()
                                        )
                                        .billingCycleConfiguration(
                                            Price.Unit.BillingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    Price.Unit.BillingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .cadence(Price.Unit.Cadence.ONE_TIME)
                                        .conversionRate(0.0)
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .creditAllocation(
                                            Price.Unit.CreditAllocation.builder()
                                                .allowsRollover(true)
                                                .currency("currency")
                                                .customExpiration(
                                                    Price.Unit.CreditAllocation.CustomExpiration
                                                        .builder()
                                                        .duration(0L)
                                                        .durationUnit(
                                                            Price.Unit.CreditAllocation
                                                                .CustomExpiration
                                                                .DurationUnit
                                                                .DAY
                                                        )
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .currency("currency")
                                        .discount(
                                            PercentageDiscount.builder()
                                                .discountType(
                                                    PercentageDiscount.DiscountType.PERCENTAGE
                                                )
                                                .percentageDiscount(0.15)
                                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                .reason("reason")
                                                .build()
                                        )
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(0.0)
                                        .invoicingCycleConfiguration(
                                            Price.Unit.InvoicingCycleConfiguration.builder()
                                                .duration(0L)
                                                .durationUnit(
                                                    Price.Unit.InvoicingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .item(
                                            Price.Unit.Item.builder().id("id").name("name").build()
                                        )
                                        .maximum(
                                            Price.Unit.Maximum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Price.Unit.Maximum.Filter.builder()
                                                        .field(
                                                            Price.Unit.Maximum.Filter.Field.PRICE_ID
                                                        )
                                                        .operator(
                                                            Price.Unit.Maximum.Filter.Operator
                                                                .INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .maximumAmount("maximum_amount")
                                                .build()
                                        )
                                        .maximumAmount("maximum_amount")
                                        .metadata(
                                            Price.Unit.Metadata.builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from("string"),
                                                )
                                                .build()
                                        )
                                        .minimum(
                                            Price.Unit.Minimum.builder()
                                                .addAppliesToPriceId("string")
                                                .addFilter(
                                                    Price.Unit.Minimum.Filter.builder()
                                                        .field(
                                                            Price.Unit.Minimum.Filter.Field.PRICE_ID
                                                        )
                                                        .operator(
                                                            Price.Unit.Minimum.Filter.Operator
                                                                .INCLUDES
                                                        )
                                                        .addValue("string")
                                                        .build()
                                                )
                                                .minimumAmount("minimum_amount")
                                                .build()
                                        )
                                        .minimumAmount("minimum_amount")
                                        .name("name")
                                        .planPhaseOrder(0L)
                                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                                        .unitConfig(
                                            Price.Unit.UnitConfig.builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .dimensionalPriceConfiguration(
                                            Price.Unit.DimensionalPriceConfiguration.builder()
                                                .addDimensionValue("string")
                                                .dimensionalPriceGroupId(
                                                    "dimensional_price_group_id"
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .quantity(1.0)
                                .startDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                                .addSubLineItem(
                                    Invoice.LineItem.SubLineItem.Matrix.builder()
                                        .amount("9.00")
                                        .grouping(
                                            Invoice.LineItem.SubLineItem.Matrix.Grouping.builder()
                                                .key("region")
                                                .value("west")
                                                .build()
                                        )
                                        .matrixConfig(
                                            Invoice.LineItem.SubLineItem.Matrix.MatrixConfig
                                                .builder()
                                                .addDimensionValue("string")
                                                .build()
                                        )
                                        .name("Tier One")
                                        .quantity(5.0)
                                        .build()
                                )
                                .subtotal("9.00")
                                .addTaxAmount(
                                    Invoice.LineItem.TaxAmount.builder()
                                        .amount("amount")
                                        .taxRateDescription("tax_rate_description")
                                        .taxRatePercentage("tax_rate_percentage")
                                        .build()
                                )
                                .addUsageCustomerId("string")
                                .build()
                        )
                        .maximum(
                            Invoice.Maximum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Invoice.Maximum.Filter.builder()
                                        .field(Invoice.Maximum.Filter.Field.PRICE_ID)
                                        .operator(Invoice.Maximum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .maximumAmount("maximum_amount")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .memo("memo")
                        .metadata(
                            Invoice.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimum(
                            Invoice.Minimum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Invoice.Minimum.Filter.builder()
                                        .field(Invoice.Minimum.Filter.Field.PRICE_ID)
                                        .operator(Invoice.Minimum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .minimumAmount("minimum_amount")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .paidAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addPaymentAttempt(
                            Invoice.PaymentAttempt.builder()
                                .id("id")
                                .amount("amount")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .paymentProvider(Invoice.PaymentAttempt.PaymentProvider.STRIPE)
                                .paymentProviderId("payment_provider_id")
                                .succeeded(true)
                                .build()
                        )
                        .paymentFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .paymentStartedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .scheduledIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .shippingAddress(
                            Invoice.ShippingAddress.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .status(Invoice.Status.ISSUED)
                        .subscription(Invoice.Subscription.builder().id("VDGsT23osdLb84KD").build())
                        .subtotal("8.00")
                        .syncFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("8.00")
                        .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .willAutoIssue(true)
                        .build()
                )
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofIncrement(increment)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).contains(increment)
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofIncrementRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofIncrement(
                CustomerCreditLedgerCreateEntryResponse.Increment.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.Increment.CreditBlock.builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.Increment.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.Increment.EntryStatus.COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.Increment.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .startingBalance(0.0)
                    .addCreatedInvoice(
                        Invoice.builder()
                            .id("id")
                            .amountDue("8.00")
                            .autoCollection(
                                Invoice.AutoCollection.builder()
                                    .enabled(true)
                                    .nextAttemptAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .numAttempts(0L)
                                    .previouslyAttemptedAt(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .build()
                            )
                            .billingAddress(
                                Invoice.BillingAddress.builder()
                                    .city("city")
                                    .country("country")
                                    .line1("line1")
                                    .line2("line2")
                                    .postalCode("postal_code")
                                    .state("state")
                                    .build()
                            )
                            .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                            .addCreditNote(
                                Invoice.CreditNote.builder()
                                    .id("id")
                                    .creditNoteNumber("credit_note_number")
                                    .memo("memo")
                                    .reason("reason")
                                    .total("total")
                                    .type("type")
                                    .voidedAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                    .build()
                            )
                            .currency("USD")
                            .customer(
                                Invoice.Customer.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .addCustomerBalanceTransaction(
                                Invoice.CustomerBalanceTransaction.builder()
                                    .id("cgZa3SXcsPTVyC4Y")
                                    .action(
                                        Invoice.CustomerBalanceTransaction.Action.APPLIED_TO_INVOICE
                                    )
                                    .amount("11.00")
                                    .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                    .creditNote(
                                        Invoice.CustomerBalanceTransaction.CreditNote.builder()
                                            .id("id")
                                            .build()
                                    )
                                    .description("An optional description")
                                    .endingBalance("22.00")
                                    .invoice(
                                        Invoice.CustomerBalanceTransaction.InnerInvoice.builder()
                                            .id("gXcsPTVyC4YZa3Sc")
                                            .build()
                                    )
                                    .startingBalance("33.00")
                                    .type(Invoice.CustomerBalanceTransaction.Type.INCREMENT)
                                    .build()
                            )
                            .customerTaxId(
                                Invoice.CustomerTaxId.builder()
                                    .country(Invoice.CustomerTaxId.Country.AD)
                                    .type(Invoice.CustomerTaxId.Type.AD_NRT)
                                    .value("value")
                                    .build()
                            )
                            .discount(JsonValue.from(mapOf<String, Any>()))
                            .addDiscount(
                                PercentageDiscount.builder()
                                    .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                    .percentageDiscount(0.15)
                                    .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                    .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                    .reason("reason")
                                    .build()
                            )
                            .dueDate(OffsetDateTime.parse("2022-05-30T07:00:00+00:00"))
                            .eligibleToIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .hostedInvoiceUrl("hosted_invoice_url")
                            .invoiceDate(OffsetDateTime.parse("2022-05-01T07:00:00+00:00"))
                            .invoiceNumber("JYEFHK-00001")
                            .invoicePdf(
                                "https://assets.withorb.com/invoice/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                            )
                            .invoiceSource(Invoice.InvoiceSource.SUBSCRIPTION)
                            .issueFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addLineItem(
                                Invoice.LineItem.builder()
                                    .id("id")
                                    .adjustedSubtotal("5.00")
                                    .addAdjustment(
                                        Invoice.LineItem.Adjustment.UsageDiscount.builder()
                                            .id("id")
                                            .amount("amount")
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                Invoice.LineItem.Adjustment.UsageDiscount.Filter
                                                    .builder()
                                                    .field(
                                                        Invoice.LineItem.Adjustment.UsageDiscount
                                                            .Filter
                                                            .Field
                                                            .PRICE_ID
                                                    )
                                                    .operator(
                                                        Invoice.LineItem.Adjustment.UsageDiscount
                                                            .Filter
                                                            .Operator
                                                            .INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .isInvoiceLevel(true)
                                            .reason("reason")
                                            .usageDiscount(0.0)
                                            .build()
                                    )
                                    .amount("7.00")
                                    .creditsApplied("6.00")
                                    .discount(
                                        PercentageDiscount.builder()
                                            .discountType(
                                                PercentageDiscount.DiscountType.PERCENTAGE
                                            )
                                            .percentageDiscount(0.15)
                                            .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                            .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                            .reason("reason")
                                            .build()
                                    )
                                    .endDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                                    .filter("filter")
                                    .grouping("grouping")
                                    .maximum(
                                        Invoice.LineItem.Maximum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                Invoice.LineItem.Maximum.Filter.builder()
                                                    .field(
                                                        Invoice.LineItem.Maximum.Filter.Field
                                                            .PRICE_ID
                                                    )
                                                    .operator(
                                                        Invoice.LineItem.Maximum.Filter.Operator
                                                            .INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .maximumAmount("maximum_amount")
                                            .build()
                                    )
                                    .maximumAmount("maximum_amount")
                                    .minimum(
                                        Invoice.LineItem.Minimum.builder()
                                            .addAppliesToPriceId("string")
                                            .addFilter(
                                                Invoice.LineItem.Minimum.Filter.builder()
                                                    .field(
                                                        Invoice.LineItem.Minimum.Filter.Field
                                                            .PRICE_ID
                                                    )
                                                    .operator(
                                                        Invoice.LineItem.Minimum.Filter.Operator
                                                            .INCLUDES
                                                    )
                                                    .addValue("string")
                                                    .build()
                                            )
                                            .minimumAmount("minimum_amount")
                                            .build()
                                    )
                                    .minimumAmount("minimum_amount")
                                    .name("Fixed Fee")
                                    .partiallyInvoicedAmount("4.00")
                                    .price(
                                        Price.Unit.builder()
                                            .id("id")
                                            .billableMetric(
                                                Price.Unit.BillableMetric.builder().id("id").build()
                                            )
                                            .billingCycleConfiguration(
                                                Price.Unit.BillingCycleConfiguration.builder()
                                                    .duration(0L)
                                                    .durationUnit(
                                                        Price.Unit.BillingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .cadence(Price.Unit.Cadence.ONE_TIME)
                                            .conversionRate(0.0)
                                            .createdAt(
                                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                            )
                                            .creditAllocation(
                                                Price.Unit.CreditAllocation.builder()
                                                    .allowsRollover(true)
                                                    .currency("currency")
                                                    .customExpiration(
                                                        Price.Unit.CreditAllocation.CustomExpiration
                                                            .builder()
                                                            .duration(0L)
                                                            .durationUnit(
                                                                Price.Unit.CreditAllocation
                                                                    .CustomExpiration
                                                                    .DurationUnit
                                                                    .DAY
                                                            )
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                            .currency("currency")
                                            .discount(
                                                PercentageDiscount.builder()
                                                    .discountType(
                                                        PercentageDiscount.DiscountType.PERCENTAGE
                                                    )
                                                    .percentageDiscount(0.15)
                                                    .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                                    .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                                    .reason("reason")
                                                    .build()
                                            )
                                            .externalPriceId("external_price_id")
                                            .fixedPriceQuantity(0.0)
                                            .invoicingCycleConfiguration(
                                                Price.Unit.InvoicingCycleConfiguration.builder()
                                                    .duration(0L)
                                                    .durationUnit(
                                                        Price.Unit.InvoicingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .item(
                                                Price.Unit.Item.builder()
                                                    .id("id")
                                                    .name("name")
                                                    .build()
                                            )
                                            .maximum(
                                                Price.Unit.Maximum.builder()
                                                    .addAppliesToPriceId("string")
                                                    .addFilter(
                                                        Price.Unit.Maximum.Filter.builder()
                                                            .field(
                                                                Price.Unit.Maximum.Filter.Field
                                                                    .PRICE_ID
                                                            )
                                                            .operator(
                                                                Price.Unit.Maximum.Filter.Operator
                                                                    .INCLUDES
                                                            )
                                                            .addValue("string")
                                                            .build()
                                                    )
                                                    .maximumAmount("maximum_amount")
                                                    .build()
                                            )
                                            .maximumAmount("maximum_amount")
                                            .metadata(
                                                Price.Unit.Metadata.builder()
                                                    .putAdditionalProperty(
                                                        "foo",
                                                        JsonValue.from("string"),
                                                    )
                                                    .build()
                                            )
                                            .minimum(
                                                Price.Unit.Minimum.builder()
                                                    .addAppliesToPriceId("string")
                                                    .addFilter(
                                                        Price.Unit.Minimum.Filter.builder()
                                                            .field(
                                                                Price.Unit.Minimum.Filter.Field
                                                                    .PRICE_ID
                                                            )
                                                            .operator(
                                                                Price.Unit.Minimum.Filter.Operator
                                                                    .INCLUDES
                                                            )
                                                            .addValue("string")
                                                            .build()
                                                    )
                                                    .minimumAmount("minimum_amount")
                                                    .build()
                                            )
                                            .minimumAmount("minimum_amount")
                                            .name("name")
                                            .planPhaseOrder(0L)
                                            .priceType(Price.Unit.PriceType.USAGE_PRICE)
                                            .unitConfig(
                                                Price.Unit.UnitConfig.builder()
                                                    .unitAmount("unit_amount")
                                                    .build()
                                            )
                                            .dimensionalPriceConfiguration(
                                                Price.Unit.DimensionalPriceConfiguration.builder()
                                                    .addDimensionValue("string")
                                                    .dimensionalPriceGroupId(
                                                        "dimensional_price_group_id"
                                                    )
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .quantity(1.0)
                                    .startDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                                    .addSubLineItem(
                                        Invoice.LineItem.SubLineItem.Matrix.builder()
                                            .amount("9.00")
                                            .grouping(
                                                Invoice.LineItem.SubLineItem.Matrix.Grouping
                                                    .builder()
                                                    .key("region")
                                                    .value("west")
                                                    .build()
                                            )
                                            .matrixConfig(
                                                Invoice.LineItem.SubLineItem.Matrix.MatrixConfig
                                                    .builder()
                                                    .addDimensionValue("string")
                                                    .build()
                                            )
                                            .name("Tier One")
                                            .quantity(5.0)
                                            .build()
                                    )
                                    .subtotal("9.00")
                                    .addTaxAmount(
                                        Invoice.LineItem.TaxAmount.builder()
                                            .amount("amount")
                                            .taxRateDescription("tax_rate_description")
                                            .taxRatePercentage("tax_rate_percentage")
                                            .build()
                                    )
                                    .addUsageCustomerId("string")
                                    .build()
                            )
                            .maximum(
                                Invoice.Maximum.builder()
                                    .addAppliesToPriceId("string")
                                    .addFilter(
                                        Invoice.Maximum.Filter.builder()
                                            .field(Invoice.Maximum.Filter.Field.PRICE_ID)
                                            .operator(Invoice.Maximum.Filter.Operator.INCLUDES)
                                            .addValue("string")
                                            .build()
                                    )
                                    .maximumAmount("maximum_amount")
                                    .build()
                            )
                            .maximumAmount("maximum_amount")
                            .memo("memo")
                            .metadata(
                                Invoice.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .minimum(
                                Invoice.Minimum.builder()
                                    .addAppliesToPriceId("string")
                                    .addFilter(
                                        Invoice.Minimum.Filter.builder()
                                            .field(Invoice.Minimum.Filter.Field.PRICE_ID)
                                            .operator(Invoice.Minimum.Filter.Operator.INCLUDES)
                                            .addValue("string")
                                            .build()
                                    )
                                    .minimumAmount("minimum_amount")
                                    .build()
                            )
                            .minimumAmount("minimum_amount")
                            .paidAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addPaymentAttempt(
                                Invoice.PaymentAttempt.builder()
                                    .id("id")
                                    .amount("amount")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .paymentProvider(Invoice.PaymentAttempt.PaymentProvider.STRIPE)
                                    .paymentProviderId("payment_provider_id")
                                    .succeeded(true)
                                    .build()
                            )
                            .paymentFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .paymentStartedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .scheduledIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .shippingAddress(
                                Invoice.ShippingAddress.builder()
                                    .city("city")
                                    .country("country")
                                    .line1("line1")
                                    .line2("line2")
                                    .postalCode("postal_code")
                                    .state("state")
                                    .build()
                            )
                            .status(Invoice.Status.ISSUED)
                            .subscription(
                                Invoice.Subscription.builder().id("VDGsT23osdLb84KD").build()
                            )
                            .subtotal("8.00")
                            .syncFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .total("8.00")
                            .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .willAutoIssue(true)
                            .build()
                    )
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofDecrement() {
        val decrement =
            CustomerCreditLedgerCreateEntryResponse.Decrement.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.Decrement.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.Decrement.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.Decrement.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.Decrement.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .startingBalance(0.0)
                .eventId("event_id")
                .invoiceId("invoice_id")
                .priceId("price_id")
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofDecrement(decrement)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).contains(decrement)
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofDecrementRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofDecrement(
                CustomerCreditLedgerCreateEntryResponse.Decrement.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.Decrement.CreditBlock.builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.Decrement.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.Decrement.EntryStatus.COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.Decrement.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .startingBalance(0.0)
                    .eventId("event_id")
                    .invoiceId("invoice_id")
                    .priceId("price_id")
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofExpirationChange() {
        val expirationChange =
            CustomerCreditLedgerCreateEntryResponse.ExpirationChange.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.ExpirationChange.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.ExpirationChange.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.ExpirationChange.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.ExpirationChange.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .newBlockExpiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .startingBalance(0.0)
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofExpirationChange(expirationChange)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange())
            .contains(expirationChange)
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofExpirationChangeRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofExpirationChange(
                CustomerCreditLedgerCreateEntryResponse.ExpirationChange.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.ExpirationChange.CreditBlock
                            .builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.ExpirationChange.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.ExpirationChange.EntryStatus
                            .COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.ExpirationChange.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .newBlockExpiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .startingBalance(0.0)
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofCreditBlockExpiry() {
        val creditBlockExpiry =
            CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .startingBalance(0.0)
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofCreditBlockExpiry(creditBlockExpiry)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry())
            .contains(creditBlockExpiry)
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofCreditBlockExpiryRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofCreditBlockExpiry(
                CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.CreditBlock
                            .builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.EntryStatus
                            .COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.CreditBlockExpiry.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .startingBalance(0.0)
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofVoid() {
        val void_ =
            CustomerCreditLedgerCreateEntryResponse.Void.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.Void.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.Void.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(CustomerCreditLedgerCreateEntryResponse.Void.EntryStatus.COMMITTED)
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.Void.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .startingBalance(0.0)
                .voidAmount(0.0)
                .voidReason("void_reason")
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofVoid(void_)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).contains(void_)
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofVoidRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofVoid(
                CustomerCreditLedgerCreateEntryResponse.Void.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.Void.CreditBlock.builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.Void.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(CustomerCreditLedgerCreateEntryResponse.Void.EntryStatus.COMMITTED)
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.Void.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .startingBalance(0.0)
                    .voidAmount(0.0)
                    .voidReason("void_reason")
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofVoidInitiated() {
        val voidInitiated =
            CustomerCreditLedgerCreateEntryResponse.VoidInitiated.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.VoidInitiated.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.VoidInitiated.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.VoidInitiated.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.VoidInitiated.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .newBlockExpiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .startingBalance(0.0)
                .voidAmount(0.0)
                .voidReason("void_reason")
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofVoidInitiated(voidInitiated)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).contains(voidInitiated)
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).isEmpty
    }

    @Test
    fun ofVoidInitiatedRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofVoidInitiated(
                CustomerCreditLedgerCreateEntryResponse.VoidInitiated.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.VoidInitiated.CreditBlock.builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.VoidInitiated.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.VoidInitiated.EntryStatus.COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.VoidInitiated.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .newBlockExpiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .startingBalance(0.0)
                    .voidAmount(0.0)
                    .voidReason("void_reason")
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    @Test
    fun ofAmendment() {
        val amendment =
            CustomerCreditLedgerCreateEntryResponse.Amendment.builder()
                .id("id")
                .amount(0.0)
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .creditBlock(
                    CustomerCreditLedgerCreateEntryResponse.Amendment.CreditBlock.builder()
                        .id("id")
                        .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .perUnitCostBasis("per_unit_cost_basis")
                        .build()
                )
                .currency("currency")
                .customer(
                    CustomerCreditLedgerCreateEntryResponse.Amendment.Customer.builder()
                        .id("id")
                        .externalCustomerId("external_customer_id")
                        .build()
                )
                .description("description")
                .endingBalance(0.0)
                .entryStatus(
                    CustomerCreditLedgerCreateEntryResponse.Amendment.EntryStatus.COMMITTED
                )
                .ledgerSequenceNumber(0L)
                .metadata(
                    CustomerCreditLedgerCreateEntryResponse.Amendment.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .startingBalance(0.0)
                .build()

        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofAmendment(amendment)

        assertThat(customerCreditLedgerCreateEntryResponse.increment()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.decrement()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.expirationChange()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.creditBlockExpiry()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.void_()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.voidInitiated()).isEmpty
        assertThat(customerCreditLedgerCreateEntryResponse.amendment()).contains(amendment)
    }

    @Test
    fun ofAmendmentRoundtrip() {
        val jsonMapper = jsonMapper()
        val customerCreditLedgerCreateEntryResponse =
            CustomerCreditLedgerCreateEntryResponse.ofAmendment(
                CustomerCreditLedgerCreateEntryResponse.Amendment.builder()
                    .id("id")
                    .amount(0.0)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .creditBlock(
                        CustomerCreditLedgerCreateEntryResponse.Amendment.CreditBlock.builder()
                            .id("id")
                            .expiryDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .perUnitCostBasis("per_unit_cost_basis")
                            .build()
                    )
                    .currency("currency")
                    .customer(
                        CustomerCreditLedgerCreateEntryResponse.Amendment.Customer.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .description("description")
                    .endingBalance(0.0)
                    .entryStatus(
                        CustomerCreditLedgerCreateEntryResponse.Amendment.EntryStatus.COMMITTED
                    )
                    .ledgerSequenceNumber(0L)
                    .metadata(
                        CustomerCreditLedgerCreateEntryResponse.Amendment.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .startingBalance(0.0)
                    .build()
            )

        val roundtrippedCustomerCreditLedgerCreateEntryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerCreditLedgerCreateEntryResponse),
                jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
            )

        assertThat(roundtrippedCustomerCreditLedgerCreateEntryResponse)
            .isEqualTo(customerCreditLedgerCreateEntryResponse)
    }

    enum class IncompatibleJsonShapeTestCase(val value: JsonValue) {
        BOOLEAN(JsonValue.from(false)),
        STRING(JsonValue.from("invalid")),
        INTEGER(JsonValue.from(-1)),
        FLOAT(JsonValue.from(3.14)),
        ARRAY(JsonValue.from(listOf("invalid", "array"))),
    }

    @ParameterizedTest
    @EnumSource
    fun incompatibleJsonShapeDeserializesToUnknown(testCase: IncompatibleJsonShapeTestCase) {
        val customerCreditLedgerCreateEntryResponse =
            jsonMapper()
                .convertValue(
                    testCase.value,
                    jacksonTypeRef<CustomerCreditLedgerCreateEntryResponse>(),
                )

        val e =
            assertThrows<OrbInvalidDataException> {
                customerCreditLedgerCreateEntryResponse.validate()
            }
        assertThat(e).hasMessageStartingWith("Unknown ")
    }
}
