// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CustomerAccountingSyncSucceededWebhookEventTest {

    @Test
    fun create() {
        val customerAccountingSyncSucceededWebhookEvent =
            CustomerAccountingSyncSucceededWebhookEvent.builder()
                .id("id")
                .accountingSyncRecord(
                    CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                        .id("id")
                        .customerId("customer_id")
                        .recordType(
                            CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .RecordType
                                .CUSTOMER
                        )
                        .errorDetails(
                            CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .ErrorDetails
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .providerCustomerId("provider_customer_id")
                        .status("status")
                        .syncAction("sync_action")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerAccountingSyncSucceededWebhookEvent.Properties.builder()
                        .connectionType("connection_type")
                        .build()
                )
                .type(
                    CustomerAccountingSyncSucceededWebhookEvent.Type
                        .CUSTOMER_ACCOUNTING_SYNC_SUCCEEDED
                )
                .build()

        assertThat(customerAccountingSyncSucceededWebhookEvent.id()).isEqualTo("id")
        assertThat(customerAccountingSyncSucceededWebhookEvent.accountingSyncRecord())
            .isEqualTo(
                CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                    .id("id")
                    .customerId("customer_id")
                    .recordType(
                        CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.RecordType
                            .CUSTOMER
                    )
                    .errorDetails(
                        CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                            .ErrorDetails
                            .builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .providerCustomerId("provider_customer_id")
                    .status("status")
                    .syncAction("sync_action")
                    .build()
            )
        assertThat(customerAccountingSyncSucceededWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(customerAccountingSyncSucceededWebhookEvent.customer())
            .isEqualTo(
                Customer.builder()
                    .id("id")
                    .addAdditionalEmail("string")
                    .autoCollection(true)
                    .autoIssuance(true)
                    .balance("balance")
                    .billingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currency("currency")
                    .email("email")
                    .emailDelivery(true)
                    .exemptFromAutomatedTax(true)
                    .externalCustomerId("external_customer_id")
                    .hierarchy(
                        Customer.Hierarchy.builder()
                            .addChild(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .parent(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .build()
                    )
                    .metadata(
                        Customer.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .name("name")
                    .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                    .paymentProviderId("payment_provider_id")
                    .portalUrl("portal_url")
                    .shippingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .taxId(
                        CustomerTaxId.builder()
                            .country(CustomerTaxId.Country.AD)
                            .type(CustomerTaxId.Type.AD_NRT)
                            .value("value")
                            .build()
                    )
                    .timezone("timezone")
                    .accountingSyncConfiguration(
                        Customer.AccountingSyncConfiguration.builder()
                            .addAccountingProvider(
                                Customer.AccountingSyncConfiguration.AccountingProvider.builder()
                                    .externalProviderId("external_provider_id")
                                    .providerType(
                                        Customer.AccountingSyncConfiguration.AccountingProvider
                                            .ProviderType
                                            .QUICKBOOKS
                                    )
                                    .build()
                            )
                            .excluded(true)
                            .build()
                    )
                    .automaticTaxEnabled(true)
                    .defaultPaymentMethod(
                        Customer.DefaultPaymentMethod.builder()
                            .id("id")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customer_id")
                            .default_(true)
                            .externalPaymentMethodId("external_payment_method_id")
                            .paymentMethodType(Customer.DefaultPaymentMethod.PaymentMethodType.CARD)
                            .providerType("provider_type")
                            .build()
                    )
                    .paymentConfiguration(
                        Customer.PaymentConfiguration.builder()
                            .addPaymentProvider(
                                Customer.PaymentConfiguration.PaymentProvider.builder()
                                    .providerType(
                                        Customer.PaymentConfiguration.PaymentProvider.ProviderType
                                            .STRIPE
                                    )
                                    .defaultSharedPaymentToken("default_shared_payment_token")
                                    .addExcludedPaymentMethodType("string")
                                    .build()
                            )
                            .build()
                    )
                    .reportingConfiguration(
                        Customer.ReportingConfiguration.builder().exempt(true).build()
                    )
                    .build()
            )
        assertThat(customerAccountingSyncSucceededWebhookEvent.properties())
            .isEqualTo(
                CustomerAccountingSyncSucceededWebhookEvent.Properties.builder()
                    .connectionType("connection_type")
                    .build()
            )
        assertThat(customerAccountingSyncSucceededWebhookEvent.type())
            .isEqualTo(
                CustomerAccountingSyncSucceededWebhookEvent.Type.CUSTOMER_ACCOUNTING_SYNC_SUCCEEDED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val customerAccountingSyncSucceededWebhookEvent =
            CustomerAccountingSyncSucceededWebhookEvent.builder()
                .id("id")
                .accountingSyncRecord(
                    CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord.builder()
                        .id("id")
                        .customerId("customer_id")
                        .recordType(
                            CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .RecordType
                                .CUSTOMER
                        )
                        .errorDetails(
                            CustomerAccountingSyncSucceededWebhookEvent.AccountingSyncRecord
                                .ErrorDetails
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .providerCustomerId("provider_customer_id")
                        .status("status")
                        .syncAction("sync_action")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .customer(
                    Customer.builder()
                        .id("id")
                        .addAdditionalEmail("string")
                        .autoCollection(true)
                        .autoIssuance(true)
                        .balance("balance")
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currency("currency")
                        .email("email")
                        .emailDelivery(true)
                        .exemptFromAutomatedTax(true)
                        .externalCustomerId("external_customer_id")
                        .hierarchy(
                            Customer.Hierarchy.builder()
                                .addChild(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .parent(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .build()
                        )
                        .metadata(
                            Customer.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .name("name")
                        .paymentProvider(Customer.PaymentProvider.QUICKBOOKS)
                        .paymentProviderId("payment_provider_id")
                        .portalUrl("portal_url")
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .taxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .timezone("timezone")
                        .accountingSyncConfiguration(
                            Customer.AccountingSyncConfiguration.builder()
                                .addAccountingProvider(
                                    Customer.AccountingSyncConfiguration.AccountingProvider
                                        .builder()
                                        .externalProviderId("external_provider_id")
                                        .providerType(
                                            Customer.AccountingSyncConfiguration.AccountingProvider
                                                .ProviderType
                                                .QUICKBOOKS
                                        )
                                        .build()
                                )
                                .excluded(true)
                                .build()
                        )
                        .automaticTaxEnabled(true)
                        .defaultPaymentMethod(
                            Customer.DefaultPaymentMethod.builder()
                                .id("id")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customer_id")
                                .default_(true)
                                .externalPaymentMethodId("external_payment_method_id")
                                .paymentMethodType(
                                    Customer.DefaultPaymentMethod.PaymentMethodType.CARD
                                )
                                .providerType("provider_type")
                                .build()
                        )
                        .paymentConfiguration(
                            Customer.PaymentConfiguration.builder()
                                .addPaymentProvider(
                                    Customer.PaymentConfiguration.PaymentProvider.builder()
                                        .providerType(
                                            Customer.PaymentConfiguration.PaymentProvider
                                                .ProviderType
                                                .STRIPE
                                        )
                                        .defaultSharedPaymentToken("default_shared_payment_token")
                                        .addExcludedPaymentMethodType("string")
                                        .build()
                                )
                                .build()
                        )
                        .reportingConfiguration(
                            Customer.ReportingConfiguration.builder().exempt(true).build()
                        )
                        .build()
                )
                .properties(
                    CustomerAccountingSyncSucceededWebhookEvent.Properties.builder()
                        .connectionType("connection_type")
                        .build()
                )
                .type(
                    CustomerAccountingSyncSucceededWebhookEvent.Type
                        .CUSTOMER_ACCOUNTING_SYNC_SUCCEEDED
                )
                .build()

        val roundtrippedCustomerAccountingSyncSucceededWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(customerAccountingSyncSucceededWebhookEvent),
                jacksonTypeRef<CustomerAccountingSyncSucceededWebhookEvent>(),
            )

        assertThat(roundtrippedCustomerAccountingSyncSucceededWebhookEvent)
            .isEqualTo(customerAccountingSyncSucceededWebhookEvent)
    }
}
