// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InvoiceListSummaryPageResponseTest {

    @Test
    fun create() {
        val invoiceListSummaryPageResponse =
            InvoiceListSummaryPageResponse.builder()
                .addData(
                    InvoiceListSummaryResponse.builder()
                        .id("id")
                        .amountDue("8.00")
                        .autoCollection(
                            InvoiceListSummaryResponse.AutoCollection.builder()
                                .enabled(true)
                                .nextAttemptAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .numAttempts(0L)
                                .previouslyAttemptedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                        .addCreditNote(
                            InvoiceListSummaryResponse.CreditNote.builder()
                                .id("id")
                                .creditNoteNumber("credit_note_number")
                                .memo("memo")
                                .reason("reason")
                                .total("total")
                                .type("type")
                                .voidedAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .build()
                        )
                        .currency("USD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .addCustomerBalanceTransaction(
                            InvoiceListSummaryResponse.CustomerBalanceTransaction.builder()
                                .id("cgZa3SXcsPTVyC4Y")
                                .action(
                                    InvoiceListSummaryResponse.CustomerBalanceTransaction.Action
                                        .APPLIED_TO_INVOICE
                                )
                                .amount("11.00")
                                .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .creditNote(CreditNoteTiny.builder().id("id").build())
                                .description("An optional description")
                                .endingBalance("22.00")
                                .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                                .startingBalance("33.00")
                                .type(
                                    InvoiceListSummaryResponse.CustomerBalanceTransaction.Type
                                        .INCREMENT
                                )
                                .build()
                        )
                        .customerTaxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .dueDate(OffsetDateTime.parse("2022-05-30T07:00:00+00:00"))
                        .eligibleToIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .hostedInvoiceUrl("hosted_invoice_url")
                        .invoiceDate(OffsetDateTime.parse("2022-05-01T07:00:00+00:00"))
                        .invoiceNumber("JYEFHK-00001")
                        .invoicePdf(
                            "https://assets.withorb.com/invoice/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                        )
                        .invoiceSource(InvoiceListSummaryResponse.InvoiceSource.SUBSCRIPTION)
                        .issueFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .memo("memo")
                        .metadata(
                            InvoiceListSummaryResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .paidAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addPaymentAttempt(
                            InvoiceListSummaryResponse.PaymentAttempt.builder()
                                .id("id")
                                .amount("amount")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .paymentProvider(
                                    InvoiceListSummaryResponse.PaymentAttempt.PaymentProvider.STRIPE
                                )
                                .paymentProviderId("payment_provider_id")
                                .receiptPdf(
                                    "https://assets.withorb.com/receipt/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                                )
                                .succeeded(true)
                                .build()
                        )
                        .paymentFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .paymentStartedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .scheduledIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .status(InvoiceListSummaryResponse.Status.ISSUED)
                        .subscription(SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build())
                        .syncFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("8.00")
                        .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .willAutoIssue(true)
                        .build()
                )
                .paginationMetadata(
                    PaginationMetadata.builder().hasMore(true).nextCursor("next_cursor").build()
                )
                .build()

        assertThat(invoiceListSummaryPageResponse.data())
            .containsExactly(
                InvoiceListSummaryResponse.builder()
                    .id("id")
                    .amountDue("8.00")
                    .autoCollection(
                        InvoiceListSummaryResponse.AutoCollection.builder()
                            .enabled(true)
                            .nextAttemptAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .numAttempts(0L)
                            .previouslyAttemptedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .billingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                    .addCreditNote(
                        InvoiceListSummaryResponse.CreditNote.builder()
                            .id("id")
                            .creditNoteNumber("credit_note_number")
                            .memo("memo")
                            .reason("reason")
                            .total("total")
                            .type("type")
                            .voidedAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                            .build()
                    )
                    .currency("USD")
                    .customer(
                        CustomerMinified.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .addCustomerBalanceTransaction(
                        InvoiceListSummaryResponse.CustomerBalanceTransaction.builder()
                            .id("cgZa3SXcsPTVyC4Y")
                            .action(
                                InvoiceListSummaryResponse.CustomerBalanceTransaction.Action
                                    .APPLIED_TO_INVOICE
                            )
                            .amount("11.00")
                            .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                            .creditNote(CreditNoteTiny.builder().id("id").build())
                            .description("An optional description")
                            .endingBalance("22.00")
                            .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                            .startingBalance("33.00")
                            .type(
                                InvoiceListSummaryResponse.CustomerBalanceTransaction.Type.INCREMENT
                            )
                            .build()
                    )
                    .customerTaxId(
                        CustomerTaxId.builder()
                            .country(CustomerTaxId.Country.AD)
                            .type(CustomerTaxId.Type.AD_NRT)
                            .value("value")
                            .build()
                    )
                    .dueDate(OffsetDateTime.parse("2022-05-30T07:00:00+00:00"))
                    .eligibleToIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .hostedInvoiceUrl("hosted_invoice_url")
                    .invoiceDate(OffsetDateTime.parse("2022-05-01T07:00:00+00:00"))
                    .invoiceNumber("JYEFHK-00001")
                    .invoicePdf(
                        "https://assets.withorb.com/invoice/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                    )
                    .invoiceSource(InvoiceListSummaryResponse.InvoiceSource.SUBSCRIPTION)
                    .issueFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .memo("memo")
                    .metadata(
                        InvoiceListSummaryResponse.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .paidAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addPaymentAttempt(
                        InvoiceListSummaryResponse.PaymentAttempt.builder()
                            .id("id")
                            .amount("amount")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .paymentProvider(
                                InvoiceListSummaryResponse.PaymentAttempt.PaymentProvider.STRIPE
                            )
                            .paymentProviderId("payment_provider_id")
                            .receiptPdf(
                                "https://assets.withorb.com/receipt/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                            )
                            .succeeded(true)
                            .build()
                    )
                    .paymentFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .paymentStartedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .scheduledIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .shippingAddress(
                        Address.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postal_code")
                            .state("state")
                            .build()
                    )
                    .status(InvoiceListSummaryResponse.Status.ISSUED)
                    .subscription(SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build())
                    .syncFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .total("8.00")
                    .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .willAutoIssue(true)
                    .build()
            )
        assertThat(invoiceListSummaryPageResponse.paginationMetadata())
            .isEqualTo(PaginationMetadata.builder().hasMore(true).nextCursor("next_cursor").build())
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val invoiceListSummaryPageResponse =
            InvoiceListSummaryPageResponse.builder()
                .addData(
                    InvoiceListSummaryResponse.builder()
                        .id("id")
                        .amountDue("8.00")
                        .autoCollection(
                            InvoiceListSummaryResponse.AutoCollection.builder()
                                .enabled(true)
                                .nextAttemptAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .numAttempts(0L)
                                .previouslyAttemptedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .build()
                        )
                        .billingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                        .addCreditNote(
                            InvoiceListSummaryResponse.CreditNote.builder()
                                .id("id")
                                .creditNoteNumber("credit_note_number")
                                .memo("memo")
                                .reason("reason")
                                .total("total")
                                .type("type")
                                .voidedAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .build()
                        )
                        .currency("USD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .addCustomerBalanceTransaction(
                            InvoiceListSummaryResponse.CustomerBalanceTransaction.builder()
                                .id("cgZa3SXcsPTVyC4Y")
                                .action(
                                    InvoiceListSummaryResponse.CustomerBalanceTransaction.Action
                                        .APPLIED_TO_INVOICE
                                )
                                .amount("11.00")
                                .createdAt(OffsetDateTime.parse("2022-05-01T07:01:31+00:00"))
                                .creditNote(CreditNoteTiny.builder().id("id").build())
                                .description("An optional description")
                                .endingBalance("22.00")
                                .invoice(InvoiceTiny.builder().id("gXcsPTVyC4YZa3Sc").build())
                                .startingBalance("33.00")
                                .type(
                                    InvoiceListSummaryResponse.CustomerBalanceTransaction.Type
                                        .INCREMENT
                                )
                                .build()
                        )
                        .customerTaxId(
                            CustomerTaxId.builder()
                                .country(CustomerTaxId.Country.AD)
                                .type(CustomerTaxId.Type.AD_NRT)
                                .value("value")
                                .build()
                        )
                        .dueDate(OffsetDateTime.parse("2022-05-30T07:00:00+00:00"))
                        .eligibleToIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .hostedInvoiceUrl("hosted_invoice_url")
                        .invoiceDate(OffsetDateTime.parse("2022-05-01T07:00:00+00:00"))
                        .invoiceNumber("JYEFHK-00001")
                        .invoicePdf(
                            "https://assets.withorb.com/invoice/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                        )
                        .invoiceSource(InvoiceListSummaryResponse.InvoiceSource.SUBSCRIPTION)
                        .issueFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .issuedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .memo("memo")
                        .metadata(
                            InvoiceListSummaryResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .paidAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addPaymentAttempt(
                            InvoiceListSummaryResponse.PaymentAttempt.builder()
                                .id("id")
                                .amount("amount")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .paymentProvider(
                                    InvoiceListSummaryResponse.PaymentAttempt.PaymentProvider.STRIPE
                                )
                                .paymentProviderId("payment_provider_id")
                                .receiptPdf(
                                    "https://assets.withorb.com/receipt/rUHdhmg45vY45DX/qEAeuYePaphGMdFb"
                                )
                                .succeeded(true)
                                .build()
                        )
                        .paymentFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .paymentStartedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .scheduledIssueAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .shippingAddress(
                            Address.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postal_code")
                                .state("state")
                                .build()
                        )
                        .status(InvoiceListSummaryResponse.Status.ISSUED)
                        .subscription(SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build())
                        .syncFailedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .total("8.00")
                        .voidedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .willAutoIssue(true)
                        .build()
                )
                .paginationMetadata(
                    PaginationMetadata.builder().hasMore(true).nextCursor("next_cursor").build()
                )
                .build()

        val roundtrippedInvoiceListSummaryPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(invoiceListSummaryPageResponse),
                jacksonTypeRef<InvoiceListSummaryPageResponse>(),
            )

        assertThat(roundtrippedInvoiceListSummaryPageResponse)
            .isEqualTo(invoiceListSummaryPageResponse)
    }
}
