// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.JsonValue
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class InvoiceLineItemCreateResponseTest {

    @Test
    fun create() {
        val invoiceLineItemCreateResponse =
            InvoiceLineItemCreateResponse.builder()
                .id("id")
                .adjustedSubtotal("5.00")
                .addAdjustment(
                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.builder()
                        .id("id")
                        .amount("amount")
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter.builder()
                                .field(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Field
                                        .PRICE_ID
                                )
                                .operator(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Operator
                                        .INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .isInvoiceLevel(true)
                        .reason("reason")
                        .usageDiscount(0.0)
                        .build()
                )
                .amount("7.00")
                .creditsApplied("6.00")
                .discount(
                    PercentageDiscount.builder()
                        .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                        .percentageDiscount(0.15)
                        .addAppliesToPriceId("h74gfhdjvn7ujokd")
                        .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                        .addFilter(
                            PercentageDiscount.Filter.builder()
                                .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                .addValue("string")
                                .build()
                        )
                        .reason("reason")
                        .build()
                )
                .endDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                .filter("filter")
                .grouping("grouping")
                .maximum(
                    InvoiceLineItemCreateResponse.Maximum.builder()
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Maximum.Filter.builder()
                                .field(InvoiceLineItemCreateResponse.Maximum.Filter.Field.PRICE_ID)
                                .operator(
                                    InvoiceLineItemCreateResponse.Maximum.Filter.Operator.INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .build()
                )
                .maximumAmount("maximum_amount")
                .minimum(
                    InvoiceLineItemCreateResponse.Minimum.builder()
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Minimum.Filter.builder()
                                .field(InvoiceLineItemCreateResponse.Minimum.Filter.Field.PRICE_ID)
                                .operator(
                                    InvoiceLineItemCreateResponse.Minimum.Filter.Operator.INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .build()
                )
                .minimumAmount("minimum_amount")
                .name("Fixed Fee")
                .partiallyInvoicedAmount("4.00")
                .price(
                    Price.Unit.builder()
                        .id("id")
                        .billableMetric(Price.Unit.BillableMetric.builder().id("id").build())
                        .billingCycleConfiguration(
                            Price.Unit.BillingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(Price.Unit.BillingCycleConfiguration.DurationUnit.DAY)
                                .build()
                        )
                        .cadence(Price.Unit.Cadence.ONE_TIME)
                        .conversionRate(0.0)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .creditAllocation(
                            Price.Unit.CreditAllocation.builder()
                                .allowsRollover(true)
                                .currency("currency")
                                .customExpiration(
                                    Price.Unit.CreditAllocation.CustomExpiration.builder()
                                        .duration(0L)
                                        .durationUnit(
                                            Price.Unit.CreditAllocation.CustomExpiration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .currency("currency")
                        .discount(
                            PercentageDiscount.builder()
                                .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.15)
                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                .addFilter(
                                    PercentageDiscount.Filter.builder()
                                        .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                        .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(0.0)
                        .invoicingCycleConfiguration(
                            Price.Unit.InvoicingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(
                                    Price.Unit.InvoicingCycleConfiguration.DurationUnit.DAY
                                )
                                .build()
                        )
                        .item(Price.Unit.Item.builder().id("id").name("name").build())
                        .maximum(
                            Price.Unit.Maximum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Maximum.Filter.builder()
                                        .field(Price.Unit.Maximum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Maximum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .maximumAmount("maximum_amount")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .metadata(
                            Price.Unit.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimum(
                            Price.Unit.Minimum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Minimum.Filter.builder()
                                        .field(Price.Unit.Minimum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Minimum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .minimumAmount("minimum_amount")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .name("name")
                        .planPhaseOrder(0L)
                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                        .unitConfig(
                            Price.Unit.UnitConfig.builder().unitAmount("unit_amount").build()
                        )
                        .dimensionalPriceConfiguration(
                            Price.Unit.DimensionalPriceConfiguration.builder()
                                .addDimensionValue("string")
                                .dimensionalPriceGroupId("dimensional_price_group_id")
                                .build()
                        )
                        .build()
                )
                .quantity(1.0)
                .startDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                .addSubLineItem(
                    InvoiceLineItemCreateResponse.SubLineItem.Matrix.builder()
                        .amount("9.00")
                        .grouping(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.Grouping.builder()
                                .key("region")
                                .value("west")
                                .build()
                        )
                        .matrixConfig(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.MatrixConfig.builder()
                                .addDimensionValue("string")
                                .build()
                        )
                        .name("Tier One")
                        .quantity(5.0)
                        .build()
                )
                .subtotal("9.00")
                .addTaxAmount(
                    InvoiceLineItemCreateResponse.TaxAmount.builder()
                        .amount("amount")
                        .taxRateDescription("tax_rate_description")
                        .taxRatePercentage("tax_rate_percentage")
                        .build()
                )
                .addUsageCustomerId("string")
                .build()

        assertThat(invoiceLineItemCreateResponse.id()).isEqualTo("id")
        assertThat(invoiceLineItemCreateResponse.adjustedSubtotal()).isEqualTo("5.00")
        assertThat(invoiceLineItemCreateResponse.adjustments())
            .containsExactly(
                InvoiceLineItemCreateResponse.Adjustment.ofUsageDiscount(
                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.builder()
                        .id("id")
                        .amount("amount")
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter.builder()
                                .field(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Field
                                        .PRICE_ID
                                )
                                .operator(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Operator
                                        .INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .isInvoiceLevel(true)
                        .reason("reason")
                        .usageDiscount(0.0)
                        .build()
                )
            )
        assertThat(invoiceLineItemCreateResponse.amount()).isEqualTo("7.00")
        assertThat(invoiceLineItemCreateResponse.creditsApplied()).isEqualTo("6.00")
        assertThat(invoiceLineItemCreateResponse.discount())
            .contains(
                Discount.ofPercentage(
                    PercentageDiscount.builder()
                        .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                        .percentageDiscount(0.15)
                        .addAppliesToPriceId("h74gfhdjvn7ujokd")
                        .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                        .addFilter(
                            PercentageDiscount.Filter.builder()
                                .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                .addValue("string")
                                .build()
                        )
                        .reason("reason")
                        .build()
                )
            )
        assertThat(invoiceLineItemCreateResponse.endDate())
            .isEqualTo(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
        assertThat(invoiceLineItemCreateResponse.filter()).contains("filter")
        assertThat(invoiceLineItemCreateResponse.grouping()).contains("grouping")
        assertThat(invoiceLineItemCreateResponse.maximum())
            .contains(
                InvoiceLineItemCreateResponse.Maximum.builder()
                    .addAppliesToPriceId("string")
                    .addFilter(
                        InvoiceLineItemCreateResponse.Maximum.Filter.builder()
                            .field(InvoiceLineItemCreateResponse.Maximum.Filter.Field.PRICE_ID)
                            .operator(
                                InvoiceLineItemCreateResponse.Maximum.Filter.Operator.INCLUDES
                            )
                            .addValue("string")
                            .build()
                    )
                    .maximumAmount("maximum_amount")
                    .build()
            )
        assertThat(invoiceLineItemCreateResponse.maximumAmount()).contains("maximum_amount")
        assertThat(invoiceLineItemCreateResponse.minimum())
            .contains(
                InvoiceLineItemCreateResponse.Minimum.builder()
                    .addAppliesToPriceId("string")
                    .addFilter(
                        InvoiceLineItemCreateResponse.Minimum.Filter.builder()
                            .field(InvoiceLineItemCreateResponse.Minimum.Filter.Field.PRICE_ID)
                            .operator(
                                InvoiceLineItemCreateResponse.Minimum.Filter.Operator.INCLUDES
                            )
                            .addValue("string")
                            .build()
                    )
                    .minimumAmount("minimum_amount")
                    .build()
            )
        assertThat(invoiceLineItemCreateResponse.minimumAmount()).contains("minimum_amount")
        assertThat(invoiceLineItemCreateResponse.name()).isEqualTo("Fixed Fee")
        assertThat(invoiceLineItemCreateResponse.partiallyInvoicedAmount()).isEqualTo("4.00")
        assertThat(invoiceLineItemCreateResponse.price())
            .isEqualTo(
                Price.ofUnit(
                    Price.Unit.builder()
                        .id("id")
                        .billableMetric(Price.Unit.BillableMetric.builder().id("id").build())
                        .billingCycleConfiguration(
                            Price.Unit.BillingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(Price.Unit.BillingCycleConfiguration.DurationUnit.DAY)
                                .build()
                        )
                        .cadence(Price.Unit.Cadence.ONE_TIME)
                        .conversionRate(0.0)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .creditAllocation(
                            Price.Unit.CreditAllocation.builder()
                                .allowsRollover(true)
                                .currency("currency")
                                .customExpiration(
                                    Price.Unit.CreditAllocation.CustomExpiration.builder()
                                        .duration(0L)
                                        .durationUnit(
                                            Price.Unit.CreditAllocation.CustomExpiration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .currency("currency")
                        .discount(
                            PercentageDiscount.builder()
                                .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.15)
                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                .addFilter(
                                    PercentageDiscount.Filter.builder()
                                        .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                        .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(0.0)
                        .invoicingCycleConfiguration(
                            Price.Unit.InvoicingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(
                                    Price.Unit.InvoicingCycleConfiguration.DurationUnit.DAY
                                )
                                .build()
                        )
                        .item(Price.Unit.Item.builder().id("id").name("name").build())
                        .maximum(
                            Price.Unit.Maximum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Maximum.Filter.builder()
                                        .field(Price.Unit.Maximum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Maximum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .maximumAmount("maximum_amount")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .metadata(
                            Price.Unit.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimum(
                            Price.Unit.Minimum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Minimum.Filter.builder()
                                        .field(Price.Unit.Minimum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Minimum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .minimumAmount("minimum_amount")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .name("name")
                        .planPhaseOrder(0L)
                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                        .unitConfig(
                            Price.Unit.UnitConfig.builder().unitAmount("unit_amount").build()
                        )
                        .dimensionalPriceConfiguration(
                            Price.Unit.DimensionalPriceConfiguration.builder()
                                .addDimensionValue("string")
                                .dimensionalPriceGroupId("dimensional_price_group_id")
                                .build()
                        )
                        .build()
                )
            )
        assertThat(invoiceLineItemCreateResponse.quantity()).isEqualTo(1.0)
        assertThat(invoiceLineItemCreateResponse.startDate())
            .isEqualTo(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
        assertThat(invoiceLineItemCreateResponse.subLineItems())
            .containsExactly(
                InvoiceLineItemCreateResponse.SubLineItem.ofMatrix(
                    InvoiceLineItemCreateResponse.SubLineItem.Matrix.builder()
                        .amount("9.00")
                        .grouping(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.Grouping.builder()
                                .key("region")
                                .value("west")
                                .build()
                        )
                        .matrixConfig(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.MatrixConfig.builder()
                                .addDimensionValue("string")
                                .build()
                        )
                        .name("Tier One")
                        .quantity(5.0)
                        .build()
                )
            )
        assertThat(invoiceLineItemCreateResponse.subtotal()).isEqualTo("9.00")
        assertThat(invoiceLineItemCreateResponse.taxAmounts())
            .containsExactly(
                InvoiceLineItemCreateResponse.TaxAmount.builder()
                    .amount("amount")
                    .taxRateDescription("tax_rate_description")
                    .taxRatePercentage("tax_rate_percentage")
                    .build()
            )
        assertThat(invoiceLineItemCreateResponse.usageCustomerIds().getOrNull())
            .containsExactly("string")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val invoiceLineItemCreateResponse =
            InvoiceLineItemCreateResponse.builder()
                .id("id")
                .adjustedSubtotal("5.00")
                .addAdjustment(
                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.builder()
                        .id("id")
                        .amount("amount")
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter.builder()
                                .field(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Field
                                        .PRICE_ID
                                )
                                .operator(
                                    InvoiceLineItemCreateResponse.Adjustment.UsageDiscount.Filter
                                        .Operator
                                        .INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .isInvoiceLevel(true)
                        .reason("reason")
                        .usageDiscount(0.0)
                        .build()
                )
                .amount("7.00")
                .creditsApplied("6.00")
                .discount(
                    PercentageDiscount.builder()
                        .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                        .percentageDiscount(0.15)
                        .addAppliesToPriceId("h74gfhdjvn7ujokd")
                        .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                        .addFilter(
                            PercentageDiscount.Filter.builder()
                                .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                .addValue("string")
                                .build()
                        )
                        .reason("reason")
                        .build()
                )
                .endDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                .filter("filter")
                .grouping("grouping")
                .maximum(
                    InvoiceLineItemCreateResponse.Maximum.builder()
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Maximum.Filter.builder()
                                .field(InvoiceLineItemCreateResponse.Maximum.Filter.Field.PRICE_ID)
                                .operator(
                                    InvoiceLineItemCreateResponse.Maximum.Filter.Operator.INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .build()
                )
                .maximumAmount("maximum_amount")
                .minimum(
                    InvoiceLineItemCreateResponse.Minimum.builder()
                        .addAppliesToPriceId("string")
                        .addFilter(
                            InvoiceLineItemCreateResponse.Minimum.Filter.builder()
                                .field(InvoiceLineItemCreateResponse.Minimum.Filter.Field.PRICE_ID)
                                .operator(
                                    InvoiceLineItemCreateResponse.Minimum.Filter.Operator.INCLUDES
                                )
                                .addValue("string")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .build()
                )
                .minimumAmount("minimum_amount")
                .name("Fixed Fee")
                .partiallyInvoicedAmount("4.00")
                .price(
                    Price.Unit.builder()
                        .id("id")
                        .billableMetric(Price.Unit.BillableMetric.builder().id("id").build())
                        .billingCycleConfiguration(
                            Price.Unit.BillingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(Price.Unit.BillingCycleConfiguration.DurationUnit.DAY)
                                .build()
                        )
                        .cadence(Price.Unit.Cadence.ONE_TIME)
                        .conversionRate(0.0)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .creditAllocation(
                            Price.Unit.CreditAllocation.builder()
                                .allowsRollover(true)
                                .currency("currency")
                                .customExpiration(
                                    Price.Unit.CreditAllocation.CustomExpiration.builder()
                                        .duration(0L)
                                        .durationUnit(
                                            Price.Unit.CreditAllocation.CustomExpiration
                                                .DurationUnit
                                                .DAY
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .currency("currency")
                        .discount(
                            PercentageDiscount.builder()
                                .discountType(PercentageDiscount.DiscountType.PERCENTAGE)
                                .percentageDiscount(0.15)
                                .addAppliesToPriceId("h74gfhdjvn7ujokd")
                                .addAppliesToPriceId("7hfgtgjnbvc3ujkl")
                                .addFilter(
                                    PercentageDiscount.Filter.builder()
                                        .field(PercentageDiscount.Filter.Field.PRICE_ID)
                                        .operator(PercentageDiscount.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .reason("reason")
                                .build()
                        )
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(0.0)
                        .invoicingCycleConfiguration(
                            Price.Unit.InvoicingCycleConfiguration.builder()
                                .duration(0L)
                                .durationUnit(
                                    Price.Unit.InvoicingCycleConfiguration.DurationUnit.DAY
                                )
                                .build()
                        )
                        .item(Price.Unit.Item.builder().id("id").name("name").build())
                        .maximum(
                            Price.Unit.Maximum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Maximum.Filter.builder()
                                        .field(Price.Unit.Maximum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Maximum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .maximumAmount("maximum_amount")
                                .build()
                        )
                        .maximumAmount("maximum_amount")
                        .metadata(
                            Price.Unit.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimum(
                            Price.Unit.Minimum.builder()
                                .addAppliesToPriceId("string")
                                .addFilter(
                                    Price.Unit.Minimum.Filter.builder()
                                        .field(Price.Unit.Minimum.Filter.Field.PRICE_ID)
                                        .operator(Price.Unit.Minimum.Filter.Operator.INCLUDES)
                                        .addValue("string")
                                        .build()
                                )
                                .minimumAmount("minimum_amount")
                                .build()
                        )
                        .minimumAmount("minimum_amount")
                        .name("name")
                        .planPhaseOrder(0L)
                        .priceType(Price.Unit.PriceType.USAGE_PRICE)
                        .unitConfig(
                            Price.Unit.UnitConfig.builder().unitAmount("unit_amount").build()
                        )
                        .dimensionalPriceConfiguration(
                            Price.Unit.DimensionalPriceConfiguration.builder()
                                .addDimensionValue("string")
                                .dimensionalPriceGroupId("dimensional_price_group_id")
                                .build()
                        )
                        .build()
                )
                .quantity(1.0)
                .startDate(OffsetDateTime.parse("2022-02-01T08:00:00+00:00"))
                .addSubLineItem(
                    InvoiceLineItemCreateResponse.SubLineItem.Matrix.builder()
                        .amount("9.00")
                        .grouping(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.Grouping.builder()
                                .key("region")
                                .value("west")
                                .build()
                        )
                        .matrixConfig(
                            InvoiceLineItemCreateResponse.SubLineItem.Matrix.MatrixConfig.builder()
                                .addDimensionValue("string")
                                .build()
                        )
                        .name("Tier One")
                        .quantity(5.0)
                        .build()
                )
                .subtotal("9.00")
                .addTaxAmount(
                    InvoiceLineItemCreateResponse.TaxAmount.builder()
                        .amount("amount")
                        .taxRateDescription("tax_rate_description")
                        .taxRatePercentage("tax_rate_percentage")
                        .build()
                )
                .addUsageCustomerId("string")
                .build()

        val roundtrippedInvoiceLineItemCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(invoiceLineItemCreateResponse),
                jacksonTypeRef<InvoiceLineItemCreateResponse>(),
            )

        assertThat(roundtrippedInvoiceLineItemCreateResponse)
            .isEqualTo(invoiceLineItemCreateResponse)
    }
}
