// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.core.JsonValue
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ReplaceSubscriptionPriceParamsTest {

    @Test
    fun createReplaceSubscriptionPriceParams() {
        val replaceSubscriptionPriceParams =
            ReplaceSubscriptionPriceParams.builder()
                .replacesPriceId("replaces_price_id")
                .allocationPrice(
                    ReplaceSubscriptionPriceParams.AllocationPrice.builder()
                        .amount("10.00")
                        .cadence(ReplaceSubscriptionPriceParams.AllocationPrice.Cadence.ONE_TIME)
                        .currency("USD")
                        .expiresAtEndOfCadence(true)
                        .build()
                )
                .addDiscount(
                    ReplaceSubscriptionPriceParams.Discount.builder()
                        .discountType(
                            ReplaceSubscriptionPriceParams.Discount.DiscountType.PERCENTAGE
                        )
                        .amountDiscount("amount_discount")
                        .percentageDiscount(0.15)
                        .usageDiscount(0.0)
                        .build()
                )
                .externalPriceId("external_price_id")
                .fixedPriceQuantity(2.0)
                .maximumAmount("1.23")
                .minimumAmount("1.23")
                .price(
                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.builder()
                        .cadence(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.Cadence
                                .ANNUAL
                        )
                        .itemId("item_id")
                        .modelType(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.ModelType
                                .UNIT
                        )
                        .name("Annual fee")
                        .unitConfig(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.UnitConfig
                                .builder()
                                .unitAmount("unit_amount")
                                .build()
                        )
                        .billableMetricId("billable_metric_id")
                        .billedInAdvance(true)
                        .billingCycleConfiguration(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                .BillingCycleConfiguration
                                .builder()
                                .duration(0L)
                                .durationUnit(
                                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                        .BillingCycleConfiguration
                                        .DurationUnit
                                        .DAY
                                )
                                .build()
                        )
                        .conversionRate(0.0)
                        .currency("currency")
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(0.0)
                        .invoiceGroupingKey("invoice_grouping_key")
                        .invoicingCycleConfiguration(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                .InvoicingCycleConfiguration
                                .builder()
                                .duration(0L)
                                .durationUnit(
                                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                        .InvoicingCycleConfiguration
                                        .DurationUnit
                                        .DAY
                                )
                                .build()
                        )
                        .metadata(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.Metadata
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .referenceId("reference_id")
                        .build()
                )
                .priceId("h74gfhdjvn7ujokd")
                .build()
        assertThat(replaceSubscriptionPriceParams).isNotNull
        assertThat(replaceSubscriptionPriceParams.replacesPriceId()).isEqualTo("replaces_price_id")
        assertThat(replaceSubscriptionPriceParams.allocationPrice())
            .contains(
                ReplaceSubscriptionPriceParams.AllocationPrice.builder()
                    .amount("10.00")
                    .cadence(ReplaceSubscriptionPriceParams.AllocationPrice.Cadence.ONE_TIME)
                    .currency("USD")
                    .expiresAtEndOfCadence(true)
                    .build()
            )
        assertThat(replaceSubscriptionPriceParams.discounts().get())
            .containsExactly(
                ReplaceSubscriptionPriceParams.Discount.builder()
                    .discountType(ReplaceSubscriptionPriceParams.Discount.DiscountType.PERCENTAGE)
                    .amountDiscount("amount_discount")
                    .percentageDiscount(0.15)
                    .usageDiscount(0.0)
                    .build()
            )
        assertThat(replaceSubscriptionPriceParams.externalPriceId()).contains("external_price_id")
        assertThat(replaceSubscriptionPriceParams.fixedPriceQuantity()).contains(2.0)
        assertThat(replaceSubscriptionPriceParams.maximumAmount()).contains("1.23")
        assertThat(replaceSubscriptionPriceParams.minimumAmount()).contains("1.23")
        assertThat(replaceSubscriptionPriceParams.price())
            .contains(
                ReplaceSubscriptionPriceParams.Price.ofNewSubscriptionUnit(
                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.builder()
                        .cadence(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.Cadence
                                .ANNUAL
                        )
                        .itemId("item_id")
                        .modelType(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.ModelType
                                .UNIT
                        )
                        .name("Annual fee")
                        .unitConfig(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.UnitConfig
                                .builder()
                                .unitAmount("unit_amount")
                                .build()
                        )
                        .billableMetricId("billable_metric_id")
                        .billedInAdvance(true)
                        .billingCycleConfiguration(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                .BillingCycleConfiguration
                                .builder()
                                .duration(0L)
                                .durationUnit(
                                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                        .BillingCycleConfiguration
                                        .DurationUnit
                                        .DAY
                                )
                                .build()
                        )
                        .conversionRate(0.0)
                        .currency("currency")
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(0.0)
                        .invoiceGroupingKey("invoice_grouping_key")
                        .invoicingCycleConfiguration(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                .InvoicingCycleConfiguration
                                .builder()
                                .duration(0L)
                                .durationUnit(
                                    ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice
                                        .InvoicingCycleConfiguration
                                        .DurationUnit
                                        .DAY
                                )
                                .build()
                        )
                        .metadata(
                            ReplaceSubscriptionPriceParams.Price.NewSubscriptionUnitPrice.Metadata
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .referenceId("reference_id")
                        .build()
                )
            )
        assertThat(replaceSubscriptionPriceParams.priceId()).contains("h74gfhdjvn7ujokd")
    }
}
