// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionLicenseBalanceThresholdReachedWebhookEventTest {

    @Test
    fun create() {
        val subscriptionLicenseBalanceThresholdReachedWebhookEvent =
            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                .AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .addLicense(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                .License
                                .builder()
                                .externalLicenseId("external_license_id")
                                .licenseTypeId("license_type_id")
                                .thresholdPercentage("threshold_percentage")
                                .build()
                        )
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .subscription(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.Plan
                                .builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription
                                .Status
                                .ACTIVE
                        )
                        .build()
                )
                .type(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Type
                        .SUBSCRIPTION_LICENSE_BALANCE_THRESHOLD_REACHED
                )
                .build()

        assertThat(subscriptionLicenseBalanceThresholdReachedWebhookEvent.id()).isEqualTo("id")
        assertThat(subscriptionLicenseBalanceThresholdReachedWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(subscriptionLicenseBalanceThresholdReachedWebhookEvent.properties())
            .isEqualTo(
                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties.builder()
                    .alertConfiguration(
                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                            .AlertConfiguration
                            .builder()
                            .id("XuxCbt7x9L82yyeF")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .currency("currency")
                            .customer(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .enabled(true)
                            .metric(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Metric
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .plan(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Plan
                                    .builder()
                                    .id("m2t5akQeh2obwxeU")
                                    .externalPlanId("m2t5akQeh2obwxeU")
                                    .name("Example plan")
                                    .planVersion("plan_version")
                                    .build()
                            )
                            .subscription(
                                SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                            )
                            .addThreshold(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Threshold
                                    .builder()
                                    .value("value")
                                    .build()
                            )
                            .type(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Type
                                    .CREDIT_BALANCE_DEPLETED
                            )
                            .addBalanceAlertStatus(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .BalanceAlertStatus
                                    .builder()
                                    .inAlert(true)
                                    .thresholdValue("threshold_value")
                                    .build()
                            )
                            .addGroupingKey("string")
                            .licenseType(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .LicenseType
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .addPriceFilter(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .PriceFilter
                                    .builder()
                                    .field(
                                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                            .Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Field
                                            .PRICE_ID
                                    )
                                    .operator(
                                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                            .Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Operator
                                            .INCLUDES
                                    )
                                    .addValue("string")
                                    .build()
                            )
                            .addThresholdOverride(
                                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                    .AlertConfiguration
                                    .ThresholdOverride
                                    .builder()
                                    .addGroupValue("string")
                                    .addThreshold(
                                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                            .Properties
                                            .AlertConfiguration
                                            .ThresholdOverride
                                            .Threshold
                                            .builder()
                                            .value("value")
                                            .build()
                                    )
                                    .addGroupKey("string")
                                    .build()
                            )
                            .build()
                    )
                    .addLicense(
                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties.License
                            .builder()
                            .externalLicenseId("external_license_id")
                            .licenseTypeId("license_type_id")
                            .thresholdPercentage("threshold_percentage")
                            .build()
                    )
                    .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(subscriptionLicenseBalanceThresholdReachedWebhookEvent.subscription())
            .isEqualTo(
                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.builder()
                    .id("VDGsT23osdLb84KD")
                    .customer(
                        CustomerMinified.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .plan(
                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.Plan
                            .builder()
                            .id("m2t5akQeh2obwxeU")
                            .externalPlanId("m2t5akQeh2obwxeU")
                            .name("Example plan")
                            .build()
                    )
                    .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .status(
                        SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.Status
                            .ACTIVE
                    )
                    .build()
            )
        assertThat(subscriptionLicenseBalanceThresholdReachedWebhookEvent.type())
            .isEqualTo(
                SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Type
                    .SUBSCRIPTION_LICENSE_BALANCE_THRESHOLD_REACHED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionLicenseBalanceThresholdReachedWebhookEvent =
            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                .AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                        .Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent
                                                .Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .addLicense(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Properties
                                .License
                                .builder()
                                .externalLicenseId("external_license_id")
                                .licenseTypeId("license_type_id")
                                .thresholdPercentage("threshold_percentage")
                                .build()
                        )
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .subscription(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription.Plan
                                .builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(
                            SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Subscription
                                .Status
                                .ACTIVE
                        )
                        .build()
                )
                .type(
                    SubscriptionLicenseBalanceThresholdReachedWebhookEvent.Type
                        .SUBSCRIPTION_LICENSE_BALANCE_THRESHOLD_REACHED
                )
                .build()

        val roundtrippedSubscriptionLicenseBalanceThresholdReachedWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(
                    subscriptionLicenseBalanceThresholdReachedWebhookEvent
                ),
                jacksonTypeRef<SubscriptionLicenseBalanceThresholdReachedWebhookEvent>(),
            )

        assertThat(roundtrippedSubscriptionLicenseBalanceThresholdReachedWebhookEvent)
            .isEqualTo(subscriptionLicenseBalanceThresholdReachedWebhookEvent)
    }
}
