// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionAlertDisabledWebhookEventTest {

    @Test
    fun create() {
        val subscriptionAlertDisabledWebhookEvent =
            SubscriptionAlertDisabledWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionAlertDisabledWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .cardinality(0L)
                        .cardinalityLimit(0L)
                        .reason(SubscriptionAlertDisabledWebhookEvent.Properties.Reason.USER)
                        .build()
                )
                .subscription(
                    SubscriptionAlertDisabledWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionAlertDisabledWebhookEvent.Subscription.Plan.builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(SubscriptionAlertDisabledWebhookEvent.Subscription.Status.ACTIVE)
                        .build()
                )
                .type(SubscriptionAlertDisabledWebhookEvent.Type.SUBSCRIPTION_ALERT_DISABLED)
                .build()

        assertThat(subscriptionAlertDisabledWebhookEvent.id()).isEqualTo("id")
        assertThat(subscriptionAlertDisabledWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(subscriptionAlertDisabledWebhookEvent.properties())
            .isEqualTo(
                SubscriptionAlertDisabledWebhookEvent.Properties.builder()
                    .alertConfiguration(
                        SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                            .builder()
                            .id("XuxCbt7x9L82yyeF")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .currency("currency")
                            .customer(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .enabled(true)
                            .metric(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .Metric
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .plan(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .Plan
                                    .builder()
                                    .id("m2t5akQeh2obwxeU")
                                    .externalPlanId("m2t5akQeh2obwxeU")
                                    .name("Example plan")
                                    .planVersion("plan_version")
                                    .build()
                            )
                            .subscription(
                                SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                            )
                            .addThreshold(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .Threshold
                                    .builder()
                                    .value("value")
                                    .build()
                            )
                            .type(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .Type
                                    .CREDIT_BALANCE_DEPLETED
                            )
                            .addBalanceAlertStatus(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .BalanceAlertStatus
                                    .builder()
                                    .inAlert(true)
                                    .thresholdValue("threshold_value")
                                    .build()
                            )
                            .addGroupingKey("string")
                            .licenseType(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .LicenseType
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .addPriceFilter(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .PriceFilter
                                    .builder()
                                    .field(
                                        SubscriptionAlertDisabledWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Field
                                            .PRICE_ID
                                    )
                                    .operator(
                                        SubscriptionAlertDisabledWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Operator
                                            .INCLUDES
                                    )
                                    .addValue("string")
                                    .build()
                            )
                            .addThresholdOverride(
                                SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                    .ThresholdOverride
                                    .builder()
                                    .addGroupValue("string")
                                    .addThreshold(
                                        SubscriptionAlertDisabledWebhookEvent.Properties
                                            .AlertConfiguration
                                            .ThresholdOverride
                                            .Threshold
                                            .builder()
                                            .value("value")
                                            .build()
                                    )
                                    .addGroupKey("string")
                                    .build()
                            )
                            .build()
                    )
                    .cardinality(0L)
                    .cardinalityLimit(0L)
                    .reason(SubscriptionAlertDisabledWebhookEvent.Properties.Reason.USER)
                    .build()
            )
        assertThat(subscriptionAlertDisabledWebhookEvent.subscription())
            .isEqualTo(
                SubscriptionAlertDisabledWebhookEvent.Subscription.builder()
                    .id("VDGsT23osdLb84KD")
                    .customer(
                        CustomerMinified.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .plan(
                        SubscriptionAlertDisabledWebhookEvent.Subscription.Plan.builder()
                            .id("m2t5akQeh2obwxeU")
                            .externalPlanId("m2t5akQeh2obwxeU")
                            .name("Example plan")
                            .build()
                    )
                    .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .status(SubscriptionAlertDisabledWebhookEvent.Subscription.Status.ACTIVE)
                    .build()
            )
        assertThat(subscriptionAlertDisabledWebhookEvent.type())
            .isEqualTo(SubscriptionAlertDisabledWebhookEvent.Type.SUBSCRIPTION_ALERT_DISABLED)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionAlertDisabledWebhookEvent =
            SubscriptionAlertDisabledWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionAlertDisabledWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionAlertDisabledWebhookEvent.Properties.AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionAlertDisabledWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionAlertDisabledWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .cardinality(0L)
                        .cardinalityLimit(0L)
                        .reason(SubscriptionAlertDisabledWebhookEvent.Properties.Reason.USER)
                        .build()
                )
                .subscription(
                    SubscriptionAlertDisabledWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionAlertDisabledWebhookEvent.Subscription.Plan.builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(SubscriptionAlertDisabledWebhookEvent.Subscription.Status.ACTIVE)
                        .build()
                )
                .type(SubscriptionAlertDisabledWebhookEvent.Type.SUBSCRIPTION_ALERT_DISABLED)
                .build()

        val roundtrippedSubscriptionAlertDisabledWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionAlertDisabledWebhookEvent),
                jacksonTypeRef<SubscriptionAlertDisabledWebhookEvent>(),
            )

        assertThat(roundtrippedSubscriptionAlertDisabledWebhookEvent)
            .isEqualTo(subscriptionAlertDisabledWebhookEvent)
    }
}
