// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.withorb.api.models.*
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class SubscriptionSchedulePlanChangeParamsTest {

    @Test
    fun createSubscriptionSchedulePlanChangeParams() {
        SubscriptionSchedulePlanChangeParams.builder()
            .subscriptionId("subscription_id")
            .changeOption(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
            .addAdjustments(
                listOf(
                    SubscriptionSchedulePlanChangeParams.AddAdjustment.builder()
                        .adjustment(
                            SubscriptionSchedulePlanChangeParams.AddAdjustment.Adjustment
                                .ofNewPercentageDiscount(
                                    SubscriptionSchedulePlanChangeParams.AddAdjustment.Adjustment
                                        .NewPercentageDiscount
                                        .builder()
                                        .adjustmentType(
                                            SubscriptionSchedulePlanChangeParams.AddAdjustment
                                                .Adjustment
                                                .NewPercentageDiscount
                                                .AdjustmentType
                                                .PERCENTAGE_DISCOUNT
                                        )
                                        .appliesToPriceIds(listOf("string"))
                                        .percentageDiscount(42.23)
                                        .build()
                                )
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .planPhaseOrder(123L)
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
            .addPrices(
                listOf(
                    SubscriptionSchedulePlanChangeParams.AddPrice.builder()
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalPriceId("external_price_id")
                        .planPhaseOrder(123L)
                        .price(
                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                .ofNewSubscriptionUnitPrice(
                                    SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                        .NewSubscriptionUnitPrice
                                        .builder()
                                        .cadence(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Cadence
                                                .ANNUAL
                                        )
                                        .itemId("item_id")
                                        .modelType(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .ModelType
                                                .UNIT
                                        )
                                        .name("Annual fee")
                                        .unitConfig(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .UnitConfig
                                                .builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .billableMetricId("billable_metric_id")
                                        .billedInAdvance(true)
                                        .billingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .BillingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams.AddPrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .BillingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .conversionRate(42.23)
                                        .currency("currency")
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(42.23)
                                        .invoiceGroupingKey("invoice_grouping_key")
                                        .invoicingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .InvoicingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams.AddPrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .InvoicingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .referenceId("reference_id")
                                        .build()
                                )
                        )
                        .priceId("h74gfhdjvn7ujokd")
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
            .alignBillingWithPlanChangeDate(true)
            .autoCollection(true)
            .billingCycleAlignment(
                SubscriptionSchedulePlanChangeParams.BillingCycleAlignment.UNCHANGED
            )
            .changeDate(OffsetDateTime.parse("2017-07-21T17:32:28Z"))
            .couponRedemptionCode("coupon_redemption_code")
            .creditsOverageRate(42.23)
            .defaultInvoiceMemo("default_invoice_memo")
            .externalPlanId("ZMwNQefe7J3ecf7W")
            .initialPhaseOrder(123L)
            .invoicingThreshold("10.00")
            .netTerms(123L)
            .perCreditOverageAmount(42.23)
            .planId("ZMwNQefe7J3ecf7W")
            .priceOverrides(
                listOf(
                    SubscriptionSchedulePlanChangeParams.PriceOverride.ofOverrideUnitPrice(
                        SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                            .builder()
                            .id("id")
                            .modelType(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .ModelType
                                    .UNIT
                            )
                            .unitConfig(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .UnitConfig
                                    .builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .conversionRate(42.23)
                            .currency("currency")
                            .discount(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .Discount
                                    .builder()
                                    .discountType(
                                        SubscriptionSchedulePlanChangeParams.PriceOverride
                                            .OverrideUnitPrice
                                            .Discount
                                            .DiscountType
                                            .PERCENTAGE
                                    )
                                    .amountDiscount("amount_discount")
                                    .appliesToPriceIds(listOf("string"))
                                    .percentageDiscount(42.23)
                                    .trialAmountDiscount("trial_amount_discount")
                                    .usageDiscount(42.23)
                                    .build()
                            )
                            .fixedPriceQuantity(42.23)
                            .maximumAmount("1.23")
                            .minimumAmount("1.23")
                            .build()
                    )
                )
            )
            .removeAdjustments(
                listOf(
                    SubscriptionSchedulePlanChangeParams.RemoveAdjustment.builder()
                        .adjustmentId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
            .removePrices(
                listOf(
                    SubscriptionSchedulePlanChangeParams.RemovePrice.builder()
                        .externalPriceId("external_price_id")
                        .priceId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
            .replaceAdjustments(
                listOf(
                    SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.builder()
                        .adjustment(
                            SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.Adjustment
                                .ofNewPercentageDiscount(
                                    SubscriptionSchedulePlanChangeParams.ReplaceAdjustment
                                        .Adjustment
                                        .NewPercentageDiscount
                                        .builder()
                                        .adjustmentType(
                                            SubscriptionSchedulePlanChangeParams.ReplaceAdjustment
                                                .Adjustment
                                                .NewPercentageDiscount
                                                .AdjustmentType
                                                .PERCENTAGE_DISCOUNT
                                        )
                                        .appliesToPriceIds(listOf("string"))
                                        .percentageDiscount(42.23)
                                        .build()
                                )
                        )
                        .replacesAdjustmentId("replaces_adjustment_id")
                        .build()
                )
            )
            .replacePrices(
                listOf(
                    SubscriptionSchedulePlanChangeParams.ReplacePrice.builder()
                        .replacesPriceId("replaces_price_id")
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(42.23)
                        .price(
                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                .ofNewSubscriptionUnitPrice(
                                    SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                        .NewSubscriptionUnitPrice
                                        .builder()
                                        .cadence(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Cadence
                                                .ANNUAL
                                        )
                                        .itemId("item_id")
                                        .modelType(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .ModelType
                                                .UNIT
                                        )
                                        .name("Annual fee")
                                        .unitConfig(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .UnitConfig
                                                .builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .billableMetricId("billable_metric_id")
                                        .billedInAdvance(true)
                                        .billingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .BillingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams
                                                        .ReplacePrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .BillingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .conversionRate(42.23)
                                        .currency("currency")
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(42.23)
                                        .invoiceGroupingKey("invoice_grouping_key")
                                        .invoicingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .InvoicingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams
                                                        .ReplacePrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .InvoicingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .referenceId("reference_id")
                                        .build()
                                )
                        )
                        .priceId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
            .build()
    }

    @Test
    fun getBody() {
        val params =
            SubscriptionSchedulePlanChangeParams.builder()
                .subscriptionId("subscription_id")
                .changeOption(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
                .addAdjustments(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.AddAdjustment.builder()
                            .adjustment(
                                SubscriptionSchedulePlanChangeParams.AddAdjustment.Adjustment
                                    .ofNewPercentageDiscount(
                                        SubscriptionSchedulePlanChangeParams.AddAdjustment
                                            .Adjustment
                                            .NewPercentageDiscount
                                            .builder()
                                            .adjustmentType(
                                                SubscriptionSchedulePlanChangeParams.AddAdjustment
                                                    .Adjustment
                                                    .NewPercentageDiscount
                                                    .AdjustmentType
                                                    .PERCENTAGE_DISCOUNT
                                            )
                                            .appliesToPriceIds(listOf("string"))
                                            .percentageDiscount(42.23)
                                            .build()
                                    )
                            )
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .planPhaseOrder(123L)
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                )
                .addPrices(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.AddPrice.builder()
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .externalPriceId("external_price_id")
                            .planPhaseOrder(123L)
                            .price(
                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                    .ofNewSubscriptionUnitPrice(
                                        SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                            .NewSubscriptionUnitPrice
                                            .builder()
                                            .cadence(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .Cadence
                                                    .ANNUAL
                                            )
                                            .itemId("item_id")
                                            .modelType(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .ModelType
                                                    .UNIT
                                            )
                                            .name("Annual fee")
                                            .unitConfig(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .UnitConfig
                                                    .builder()
                                                    .unitAmount("unit_amount")
                                                    .build()
                                            )
                                            .billableMetricId("billable_metric_id")
                                            .billedInAdvance(true)
                                            .billingCycleConfiguration(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .BillingCycleConfiguration
                                                    .builder()
                                                    .duration(123L)
                                                    .durationUnit(
                                                        SubscriptionSchedulePlanChangeParams
                                                            .AddPrice
                                                            .Price
                                                            .NewSubscriptionUnitPrice
                                                            .BillingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .conversionRate(42.23)
                                            .currency("currency")
                                            .externalPriceId("external_price_id")
                                            .fixedPriceQuantity(42.23)
                                            .invoiceGroupingKey("invoice_grouping_key")
                                            .invoicingCycleConfiguration(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .InvoicingCycleConfiguration
                                                    .builder()
                                                    .duration(123L)
                                                    .durationUnit(
                                                        SubscriptionSchedulePlanChangeParams
                                                            .AddPrice
                                                            .Price
                                                            .NewSubscriptionUnitPrice
                                                            .InvoicingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .metadata(
                                                SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                    .NewSubscriptionUnitPrice
                                                    .Metadata
                                                    .builder()
                                                    .build()
                                            )
                                            .referenceId("reference_id")
                                            .build()
                                    )
                            )
                            .priceId("h74gfhdjvn7ujokd")
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                )
                .alignBillingWithPlanChangeDate(true)
                .autoCollection(true)
                .billingCycleAlignment(
                    SubscriptionSchedulePlanChangeParams.BillingCycleAlignment.UNCHANGED
                )
                .changeDate(OffsetDateTime.parse("2017-07-21T17:32:28Z"))
                .couponRedemptionCode("coupon_redemption_code")
                .creditsOverageRate(42.23)
                .defaultInvoiceMemo("default_invoice_memo")
                .externalPlanId("ZMwNQefe7J3ecf7W")
                .initialPhaseOrder(123L)
                .invoicingThreshold("10.00")
                .netTerms(123L)
                .perCreditOverageAmount(42.23)
                .planId("ZMwNQefe7J3ecf7W")
                .priceOverrides(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.PriceOverride.ofOverrideUnitPrice(
                            SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                .builder()
                                .id("id")
                                .modelType(
                                    SubscriptionSchedulePlanChangeParams.PriceOverride
                                        .OverrideUnitPrice
                                        .ModelType
                                        .UNIT
                                )
                                .unitConfig(
                                    SubscriptionSchedulePlanChangeParams.PriceOverride
                                        .OverrideUnitPrice
                                        .UnitConfig
                                        .builder()
                                        .unitAmount("unit_amount")
                                        .build()
                                )
                                .conversionRate(42.23)
                                .currency("currency")
                                .discount(
                                    SubscriptionSchedulePlanChangeParams.PriceOverride
                                        .OverrideUnitPrice
                                        .Discount
                                        .builder()
                                        .discountType(
                                            SubscriptionSchedulePlanChangeParams.PriceOverride
                                                .OverrideUnitPrice
                                                .Discount
                                                .DiscountType
                                                .PERCENTAGE
                                        )
                                        .amountDiscount("amount_discount")
                                        .appliesToPriceIds(listOf("string"))
                                        .percentageDiscount(42.23)
                                        .trialAmountDiscount("trial_amount_discount")
                                        .usageDiscount(42.23)
                                        .build()
                                )
                                .fixedPriceQuantity(42.23)
                                .maximumAmount("1.23")
                                .minimumAmount("1.23")
                                .build()
                        )
                    )
                )
                .removeAdjustments(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.RemoveAdjustment.builder()
                            .adjustmentId("h74gfhdjvn7ujokd")
                            .build()
                    )
                )
                .removePrices(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.RemovePrice.builder()
                            .externalPriceId("external_price_id")
                            .priceId("h74gfhdjvn7ujokd")
                            .build()
                    )
                )
                .replaceAdjustments(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.builder()
                            .adjustment(
                                SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.Adjustment
                                    .ofNewPercentageDiscount(
                                        SubscriptionSchedulePlanChangeParams.ReplaceAdjustment
                                            .Adjustment
                                            .NewPercentageDiscount
                                            .builder()
                                            .adjustmentType(
                                                SubscriptionSchedulePlanChangeParams
                                                    .ReplaceAdjustment
                                                    .Adjustment
                                                    .NewPercentageDiscount
                                                    .AdjustmentType
                                                    .PERCENTAGE_DISCOUNT
                                            )
                                            .appliesToPriceIds(listOf("string"))
                                            .percentageDiscount(42.23)
                                            .build()
                                    )
                            )
                            .replacesAdjustmentId("replaces_adjustment_id")
                            .build()
                    )
                )
                .replacePrices(
                    listOf(
                        SubscriptionSchedulePlanChangeParams.ReplacePrice.builder()
                            .replacesPriceId("replaces_price_id")
                            .externalPriceId("external_price_id")
                            .fixedPriceQuantity(42.23)
                            .price(
                                SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                    .ofNewSubscriptionUnitPrice(
                                        SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                            .NewSubscriptionUnitPrice
                                            .builder()
                                            .cadence(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .Cadence
                                                    .ANNUAL
                                            )
                                            .itemId("item_id")
                                            .modelType(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .ModelType
                                                    .UNIT
                                            )
                                            .name("Annual fee")
                                            .unitConfig(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .UnitConfig
                                                    .builder()
                                                    .unitAmount("unit_amount")
                                                    .build()
                                            )
                                            .billableMetricId("billable_metric_id")
                                            .billedInAdvance(true)
                                            .billingCycleConfiguration(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .BillingCycleConfiguration
                                                    .builder()
                                                    .duration(123L)
                                                    .durationUnit(
                                                        SubscriptionSchedulePlanChangeParams
                                                            .ReplacePrice
                                                            .Price
                                                            .NewSubscriptionUnitPrice
                                                            .BillingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .conversionRate(42.23)
                                            .currency("currency")
                                            .externalPriceId("external_price_id")
                                            .fixedPriceQuantity(42.23)
                                            .invoiceGroupingKey("invoice_grouping_key")
                                            .invoicingCycleConfiguration(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .InvoicingCycleConfiguration
                                                    .builder()
                                                    .duration(123L)
                                                    .durationUnit(
                                                        SubscriptionSchedulePlanChangeParams
                                                            .ReplacePrice
                                                            .Price
                                                            .NewSubscriptionUnitPrice
                                                            .InvoicingCycleConfiguration
                                                            .DurationUnit
                                                            .DAY
                                                    )
                                                    .build()
                                            )
                                            .metadata(
                                                SubscriptionSchedulePlanChangeParams.ReplacePrice
                                                    .Price
                                                    .NewSubscriptionUnitPrice
                                                    .Metadata
                                                    .builder()
                                                    .build()
                                            )
                                            .referenceId("reference_id")
                                            .build()
                                    )
                            )
                            .priceId("h74gfhdjvn7ujokd")
                            .build()
                    )
                )
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.changeOption())
            .isEqualTo(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
        assertThat(body.addAdjustments())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.AddAdjustment.builder()
                        .adjustment(
                            SubscriptionSchedulePlanChangeParams.AddAdjustment.Adjustment
                                .ofNewPercentageDiscount(
                                    SubscriptionSchedulePlanChangeParams.AddAdjustment.Adjustment
                                        .NewPercentageDiscount
                                        .builder()
                                        .adjustmentType(
                                            SubscriptionSchedulePlanChangeParams.AddAdjustment
                                                .Adjustment
                                                .NewPercentageDiscount
                                                .AdjustmentType
                                                .PERCENTAGE_DISCOUNT
                                        )
                                        .appliesToPriceIds(listOf("string"))
                                        .percentageDiscount(42.23)
                                        .build()
                                )
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .planPhaseOrder(123L)
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
        assertThat(body.addPrices())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.AddPrice.builder()
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .externalPriceId("external_price_id")
                        .planPhaseOrder(123L)
                        .price(
                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                .ofNewSubscriptionUnitPrice(
                                    SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                        .NewSubscriptionUnitPrice
                                        .builder()
                                        .cadence(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Cadence
                                                .ANNUAL
                                        )
                                        .itemId("item_id")
                                        .modelType(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .ModelType
                                                .UNIT
                                        )
                                        .name("Annual fee")
                                        .unitConfig(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .UnitConfig
                                                .builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .billableMetricId("billable_metric_id")
                                        .billedInAdvance(true)
                                        .billingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .BillingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams.AddPrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .BillingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .conversionRate(42.23)
                                        .currency("currency")
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(42.23)
                                        .invoiceGroupingKey("invoice_grouping_key")
                                        .invoicingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .InvoicingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams.AddPrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .InvoicingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            SubscriptionSchedulePlanChangeParams.AddPrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .referenceId("reference_id")
                                        .build()
                                )
                        )
                        .priceId("h74gfhdjvn7ujokd")
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
            )
        assertThat(body.alignBillingWithPlanChangeDate()).isEqualTo(true)
        assertThat(body.autoCollection()).isEqualTo(true)
        assertThat(body.billingCycleAlignment())
            .isEqualTo(SubscriptionSchedulePlanChangeParams.BillingCycleAlignment.UNCHANGED)
        assertThat(body.changeDate()).isEqualTo(OffsetDateTime.parse("2017-07-21T17:32:28Z"))
        assertThat(body.couponRedemptionCode()).isEqualTo("coupon_redemption_code")
        assertThat(body.creditsOverageRate()).isEqualTo(42.23)
        assertThat(body.defaultInvoiceMemo()).isEqualTo("default_invoice_memo")
        assertThat(body.externalPlanId()).isEqualTo("ZMwNQefe7J3ecf7W")
        assertThat(body.initialPhaseOrder()).isEqualTo(123L)
        assertThat(body.invoicingThreshold()).isEqualTo("10.00")
        assertThat(body.netTerms()).isEqualTo(123L)
        assertThat(body.perCreditOverageAmount()).isEqualTo(42.23)
        assertThat(body.planId()).isEqualTo("ZMwNQefe7J3ecf7W")
        assertThat(body.priceOverrides())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.PriceOverride.ofOverrideUnitPrice(
                        SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                            .builder()
                            .id("id")
                            .modelType(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .ModelType
                                    .UNIT
                            )
                            .unitConfig(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .UnitConfig
                                    .builder()
                                    .unitAmount("unit_amount")
                                    .build()
                            )
                            .conversionRate(42.23)
                            .currency("currency")
                            .discount(
                                SubscriptionSchedulePlanChangeParams.PriceOverride.OverrideUnitPrice
                                    .Discount
                                    .builder()
                                    .discountType(
                                        SubscriptionSchedulePlanChangeParams.PriceOverride
                                            .OverrideUnitPrice
                                            .Discount
                                            .DiscountType
                                            .PERCENTAGE
                                    )
                                    .amountDiscount("amount_discount")
                                    .appliesToPriceIds(listOf("string"))
                                    .percentageDiscount(42.23)
                                    .trialAmountDiscount("trial_amount_discount")
                                    .usageDiscount(42.23)
                                    .build()
                            )
                            .fixedPriceQuantity(42.23)
                            .maximumAmount("1.23")
                            .minimumAmount("1.23")
                            .build()
                    )
                )
            )
        assertThat(body.removeAdjustments())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.RemoveAdjustment.builder()
                        .adjustmentId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
        assertThat(body.removePrices())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.RemovePrice.builder()
                        .externalPriceId("external_price_id")
                        .priceId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
        assertThat(body.replaceAdjustments())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.builder()
                        .adjustment(
                            SubscriptionSchedulePlanChangeParams.ReplaceAdjustment.Adjustment
                                .ofNewPercentageDiscount(
                                    SubscriptionSchedulePlanChangeParams.ReplaceAdjustment
                                        .Adjustment
                                        .NewPercentageDiscount
                                        .builder()
                                        .adjustmentType(
                                            SubscriptionSchedulePlanChangeParams.ReplaceAdjustment
                                                .Adjustment
                                                .NewPercentageDiscount
                                                .AdjustmentType
                                                .PERCENTAGE_DISCOUNT
                                        )
                                        .appliesToPriceIds(listOf("string"))
                                        .percentageDiscount(42.23)
                                        .build()
                                )
                        )
                        .replacesAdjustmentId("replaces_adjustment_id")
                        .build()
                )
            )
        assertThat(body.replacePrices())
            .isEqualTo(
                listOf(
                    SubscriptionSchedulePlanChangeParams.ReplacePrice.builder()
                        .replacesPriceId("replaces_price_id")
                        .externalPriceId("external_price_id")
                        .fixedPriceQuantity(42.23)
                        .price(
                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                .ofNewSubscriptionUnitPrice(
                                    SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                        .NewSubscriptionUnitPrice
                                        .builder()
                                        .cadence(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Cadence
                                                .ANNUAL
                                        )
                                        .itemId("item_id")
                                        .modelType(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .ModelType
                                                .UNIT
                                        )
                                        .name("Annual fee")
                                        .unitConfig(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .UnitConfig
                                                .builder()
                                                .unitAmount("unit_amount")
                                                .build()
                                        )
                                        .billableMetricId("billable_metric_id")
                                        .billedInAdvance(true)
                                        .billingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .BillingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams
                                                        .ReplacePrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .BillingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .conversionRate(42.23)
                                        .currency("currency")
                                        .externalPriceId("external_price_id")
                                        .fixedPriceQuantity(42.23)
                                        .invoiceGroupingKey("invoice_grouping_key")
                                        .invoicingCycleConfiguration(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .InvoicingCycleConfiguration
                                                .builder()
                                                .duration(123L)
                                                .durationUnit(
                                                    SubscriptionSchedulePlanChangeParams
                                                        .ReplacePrice
                                                        .Price
                                                        .NewSubscriptionUnitPrice
                                                        .InvoicingCycleConfiguration
                                                        .DurationUnit
                                                        .DAY
                                                )
                                                .build()
                                        )
                                        .metadata(
                                            SubscriptionSchedulePlanChangeParams.ReplacePrice.Price
                                                .NewSubscriptionUnitPrice
                                                .Metadata
                                                .builder()
                                                .build()
                                        )
                                        .referenceId("reference_id")
                                        .build()
                                )
                        )
                        .priceId("h74gfhdjvn7ujokd")
                        .build()
                )
            )
    }

    @Test
    fun getBodyWithoutOptionalFields() {
        val params =
            SubscriptionSchedulePlanChangeParams.builder()
                .subscriptionId("subscription_id")
                .changeOption(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
                .build()
        val body = params.getBody()
        assertThat(body).isNotNull
        assertThat(body.changeOption())
            .isEqualTo(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
    }

    @Test
    fun getPathParam() {
        val params =
            SubscriptionSchedulePlanChangeParams.builder()
                .subscriptionId("subscription_id")
                .changeOption(SubscriptionSchedulePlanChangeParams.ChangeOption.REQUESTED_DATE)
                .build()
        assertThat(params).isNotNull
        // path param "subscriptionId"
        assertThat(params.getPathParam(0)).isEqualTo("subscription_id")
        // out-of-bound path param
        assertThat(params.getPathParam(1)).isEqualTo("")
    }
}
