// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.withorb.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionGroupedCostExceededWebhookEventTest {

    @Test
    fun create() {
        val subscriptionGroupedCostExceededWebhookEvent =
            SubscriptionGroupedCostExceededWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionGroupedCostExceededWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                .AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .addGroupingKey("string")
                        .addGroup(
                            SubscriptionGroupedCostExceededWebhookEvent.Properties.Group.builder()
                                .amountThreshold("amount_threshold")
                                .evaluatedAmount("evaluated_amount")
                                .addGroupValue("string")
                                .build()
                        )
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .subscription(
                    SubscriptionGroupedCostExceededWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionGroupedCostExceededWebhookEvent.Subscription.Plan.builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(
                            SubscriptionGroupedCostExceededWebhookEvent.Subscription.Status.ACTIVE
                        )
                        .build()
                )
                .type(
                    SubscriptionGroupedCostExceededWebhookEvent.Type
                        .SUBSCRIPTION_GROUPED_COST_EXCEEDED
                )
                .build()

        assertThat(subscriptionGroupedCostExceededWebhookEvent.id()).isEqualTo("id")
        assertThat(subscriptionGroupedCostExceededWebhookEvent.createdAt())
            .isEqualTo(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(subscriptionGroupedCostExceededWebhookEvent.properties())
            .isEqualTo(
                SubscriptionGroupedCostExceededWebhookEvent.Properties.builder()
                    .alertConfiguration(
                        SubscriptionGroupedCostExceededWebhookEvent.Properties.AlertConfiguration
                            .builder()
                            .id("XuxCbt7x9L82yyeF")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .currency("currency")
                            .customer(
                                CustomerMinified.builder()
                                    .id("id")
                                    .externalCustomerId("external_customer_id")
                                    .build()
                            )
                            .enabled(true)
                            .metric(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Metric
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .plan(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Plan
                                    .builder()
                                    .id("m2t5akQeh2obwxeU")
                                    .externalPlanId("m2t5akQeh2obwxeU")
                                    .name("Example plan")
                                    .planVersion("plan_version")
                                    .build()
                            )
                            .subscription(
                                SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                            )
                            .addThreshold(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Threshold
                                    .builder()
                                    .value("value")
                                    .build()
                            )
                            .type(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .Type
                                    .CREDIT_BALANCE_DEPLETED
                            )
                            .addBalanceAlertStatus(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .BalanceAlertStatus
                                    .builder()
                                    .inAlert(true)
                                    .thresholdValue("threshold_value")
                                    .build()
                            )
                            .addGroupingKey("string")
                            .licenseType(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .LicenseType
                                    .builder()
                                    .id("id")
                                    .build()
                            )
                            .addPriceFilter(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .PriceFilter
                                    .builder()
                                    .field(
                                        SubscriptionGroupedCostExceededWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Field
                                            .PRICE_ID
                                    )
                                    .operator(
                                        SubscriptionGroupedCostExceededWebhookEvent.Properties
                                            .AlertConfiguration
                                            .PriceFilter
                                            .Operator
                                            .INCLUDES
                                    )
                                    .addValue("string")
                                    .build()
                            )
                            .addThresholdOverride(
                                SubscriptionGroupedCostExceededWebhookEvent.Properties
                                    .AlertConfiguration
                                    .ThresholdOverride
                                    .builder()
                                    .addGroupValue("string")
                                    .addThreshold(
                                        SubscriptionGroupedCostExceededWebhookEvent.Properties
                                            .AlertConfiguration
                                            .ThresholdOverride
                                            .Threshold
                                            .builder()
                                            .value("value")
                                            .build()
                                    )
                                    .addGroupKey("string")
                                    .build()
                            )
                            .build()
                    )
                    .addGroupingKey("string")
                    .addGroup(
                        SubscriptionGroupedCostExceededWebhookEvent.Properties.Group.builder()
                            .amountThreshold("amount_threshold")
                            .evaluatedAmount("evaluated_amount")
                            .addGroupValue("string")
                            .build()
                    )
                    .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(subscriptionGroupedCostExceededWebhookEvent.subscription())
            .isEqualTo(
                SubscriptionGroupedCostExceededWebhookEvent.Subscription.builder()
                    .id("VDGsT23osdLb84KD")
                    .customer(
                        CustomerMinified.builder()
                            .id("id")
                            .externalCustomerId("external_customer_id")
                            .build()
                    )
                    .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .plan(
                        SubscriptionGroupedCostExceededWebhookEvent.Subscription.Plan.builder()
                            .id("m2t5akQeh2obwxeU")
                            .externalPlanId("m2t5akQeh2obwxeU")
                            .name("Example plan")
                            .build()
                    )
                    .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .status(SubscriptionGroupedCostExceededWebhookEvent.Subscription.Status.ACTIVE)
                    .build()
            )
        assertThat(subscriptionGroupedCostExceededWebhookEvent.type())
            .isEqualTo(
                SubscriptionGroupedCostExceededWebhookEvent.Type.SUBSCRIPTION_GROUPED_COST_EXCEEDED
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionGroupedCostExceededWebhookEvent =
            SubscriptionGroupedCostExceededWebhookEvent.builder()
                .id("id")
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .properties(
                    SubscriptionGroupedCostExceededWebhookEvent.Properties.builder()
                        .alertConfiguration(
                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                .AlertConfiguration
                                .builder()
                                .id("XuxCbt7x9L82yyeF")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .currency("currency")
                                .customer(
                                    CustomerMinified.builder()
                                        .id("id")
                                        .externalCustomerId("external_customer_id")
                                        .build()
                                )
                                .enabled(true)
                                .metric(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Metric
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .plan(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Plan
                                        .builder()
                                        .id("m2t5akQeh2obwxeU")
                                        .externalPlanId("m2t5akQeh2obwxeU")
                                        .name("Example plan")
                                        .planVersion("plan_version")
                                        .build()
                                )
                                .subscription(
                                    SubscriptionMinified.builder().id("VDGsT23osdLb84KD").build()
                                )
                                .addThreshold(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Threshold
                                        .builder()
                                        .value("value")
                                        .build()
                                )
                                .type(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .Type
                                        .CREDIT_BALANCE_DEPLETED
                                )
                                .addBalanceAlertStatus(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .BalanceAlertStatus
                                        .builder()
                                        .inAlert(true)
                                        .thresholdValue("threshold_value")
                                        .build()
                                )
                                .addGroupingKey("string")
                                .licenseType(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .LicenseType
                                        .builder()
                                        .id("id")
                                        .build()
                                )
                                .addPriceFilter(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .PriceFilter
                                        .builder()
                                        .field(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Field
                                                .PRICE_ID
                                        )
                                        .operator(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .PriceFilter
                                                .Operator
                                                .INCLUDES
                                        )
                                        .addValue("string")
                                        .build()
                                )
                                .addThresholdOverride(
                                    SubscriptionGroupedCostExceededWebhookEvent.Properties
                                        .AlertConfiguration
                                        .ThresholdOverride
                                        .builder()
                                        .addGroupValue("string")
                                        .addThreshold(
                                            SubscriptionGroupedCostExceededWebhookEvent.Properties
                                                .AlertConfiguration
                                                .ThresholdOverride
                                                .Threshold
                                                .builder()
                                                .value("value")
                                                .build()
                                        )
                                        .addGroupKey("string")
                                        .build()
                                )
                                .build()
                        )
                        .addGroupingKey("string")
                        .addGroup(
                            SubscriptionGroupedCostExceededWebhookEvent.Properties.Group.builder()
                                .amountThreshold("amount_threshold")
                                .evaluatedAmount("evaluated_amount")
                                .addGroupValue("string")
                                .build()
                        )
                        .timeframeEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .timeframeStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .subscription(
                    SubscriptionGroupedCostExceededWebhookEvent.Subscription.builder()
                        .id("VDGsT23osdLb84KD")
                        .customer(
                            CustomerMinified.builder()
                                .id("id")
                                .externalCustomerId("external_customer_id")
                                .build()
                        )
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .plan(
                            SubscriptionGroupedCostExceededWebhookEvent.Subscription.Plan.builder()
                                .id("m2t5akQeh2obwxeU")
                                .externalPlanId("m2t5akQeh2obwxeU")
                                .name("Example plan")
                                .build()
                        )
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(
                            SubscriptionGroupedCostExceededWebhookEvent.Subscription.Status.ACTIVE
                        )
                        .build()
                )
                .type(
                    SubscriptionGroupedCostExceededWebhookEvent.Type
                        .SUBSCRIPTION_GROUPED_COST_EXCEEDED
                )
                .build()

        val roundtrippedSubscriptionGroupedCostExceededWebhookEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionGroupedCostExceededWebhookEvent),
                jacksonTypeRef<SubscriptionGroupedCostExceededWebhookEvent>(),
            )

        assertThat(roundtrippedSubscriptionGroupedCostExceededWebhookEvent)
            .isEqualTo(subscriptionGroupedCostExceededWebhookEvent)
    }
}
