// File generated from our OpenAPI spec by Stainless.

package com.withorb.api.models

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.withorb.api.core.Enum
import com.withorb.api.core.ExcludeMissing
import com.withorb.api.core.JsonField
import com.withorb.api.core.JsonValue
import com.withorb.api.core.NoAutoDetect
import com.withorb.api.core.http.Headers
import com.withorb.api.core.http.QueryParams
import com.withorb.api.core.toImmutable
import com.withorb.api.errors.OrbInvalidDataException
import java.util.Objects
import java.util.Optional

class CustomerCreditTopUpCreateParams
constructor(
    private val customerId: String,
    private val amount: String,
    private val currency: String,
    private val invoiceSettings: InvoiceSettings,
    private val perUnitCostBasis: String,
    private val threshold: String,
    private val expiresAfter: Long?,
    private val expiresAfterUnit: ExpiresAfterUnit?,
    private val additionalHeaders: Headers,
    private val additionalQueryParams: QueryParams,
    private val additionalBodyProperties: Map<String, JsonValue>,
) {

    fun customerId(): String = customerId

    fun amount(): String = amount

    fun currency(): String = currency

    fun invoiceSettings(): InvoiceSettings = invoiceSettings

    fun perUnitCostBasis(): String = perUnitCostBasis

    fun threshold(): String = threshold

    fun expiresAfter(): Optional<Long> = Optional.ofNullable(expiresAfter)

    fun expiresAfterUnit(): Optional<ExpiresAfterUnit> = Optional.ofNullable(expiresAfterUnit)

    fun _additionalHeaders(): Headers = additionalHeaders

    fun _additionalQueryParams(): QueryParams = additionalQueryParams

    fun _additionalBodyProperties(): Map<String, JsonValue> = additionalBodyProperties

    @JvmSynthetic
    internal fun getBody(): CustomerCreditTopUpCreateBody {
        return CustomerCreditTopUpCreateBody(
            amount,
            currency,
            invoiceSettings,
            perUnitCostBasis,
            threshold,
            expiresAfter,
            expiresAfterUnit,
            additionalBodyProperties,
        )
    }

    @JvmSynthetic internal fun getHeaders(): Headers = additionalHeaders

    @JvmSynthetic internal fun getQueryParams(): QueryParams = additionalQueryParams

    fun getPathParam(index: Int): String {
        return when (index) {
            0 -> customerId
            else -> ""
        }
    }

    @JsonDeserialize(builder = CustomerCreditTopUpCreateBody.Builder::class)
    @NoAutoDetect
    class CustomerCreditTopUpCreateBody
    internal constructor(
        private val amount: String?,
        private val currency: String?,
        private val invoiceSettings: InvoiceSettings?,
        private val perUnitCostBasis: String?,
        private val threshold: String?,
        private val expiresAfter: Long?,
        private val expiresAfterUnit: ExpiresAfterUnit?,
        private val additionalProperties: Map<String, JsonValue>,
    ) {

        /** The amount to increment when the threshold is reached. */
        @JsonProperty("amount") fun amount(): String? = amount

        /**
         * The currency or custom pricing unit to use for this top-up. If this is a real-world
         * currency, it must match the customer's invoicing currency.
         */
        @JsonProperty("currency") fun currency(): String? = currency

        /** Settings for invoices generated by triggered top-ups. */
        @JsonProperty("invoice_settings") fun invoiceSettings(): InvoiceSettings? = invoiceSettings

        /** How much, in the customer's currency, to charge for each unit. */
        @JsonProperty("per_unit_cost_basis") fun perUnitCostBasis(): String? = perUnitCostBasis

        /**
         * The threshold at which to trigger the top-up. If the balance is at or below this
         * threshold, the top-up will be triggered.
         */
        @JsonProperty("threshold") fun threshold(): String? = threshold

        /**
         * The number of days or months after which the top-up expires. If unspecified, it does not
         * expire.
         */
        @JsonProperty("expires_after") fun expiresAfter(): Long? = expiresAfter

        /** The unit of expires_after. */
        @JsonProperty("expires_after_unit")
        fun expiresAfterUnit(): ExpiresAfterUnit? = expiresAfterUnit

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> = additionalProperties

        fun toBuilder() = Builder().from(this)

        companion object {

            @JvmStatic fun builder() = Builder()
        }

        class Builder {

            private var amount: String? = null
            private var currency: String? = null
            private var invoiceSettings: InvoiceSettings? = null
            private var perUnitCostBasis: String? = null
            private var threshold: String? = null
            private var expiresAfter: Long? = null
            private var expiresAfterUnit: ExpiresAfterUnit? = null
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            @JvmSynthetic
            internal fun from(customerCreditTopUpCreateBody: CustomerCreditTopUpCreateBody) =
                apply {
                    this.amount = customerCreditTopUpCreateBody.amount
                    this.currency = customerCreditTopUpCreateBody.currency
                    this.invoiceSettings = customerCreditTopUpCreateBody.invoiceSettings
                    this.perUnitCostBasis = customerCreditTopUpCreateBody.perUnitCostBasis
                    this.threshold = customerCreditTopUpCreateBody.threshold
                    this.expiresAfter = customerCreditTopUpCreateBody.expiresAfter
                    this.expiresAfterUnit = customerCreditTopUpCreateBody.expiresAfterUnit
                    additionalProperties(customerCreditTopUpCreateBody.additionalProperties)
                }

            /** The amount to increment when the threshold is reached. */
            @JsonProperty("amount") fun amount(amount: String) = apply { this.amount = amount }

            /**
             * The currency or custom pricing unit to use for this top-up. If this is a real-world
             * currency, it must match the customer's invoicing currency.
             */
            @JsonProperty("currency")
            fun currency(currency: String) = apply { this.currency = currency }

            /** Settings for invoices generated by triggered top-ups. */
            @JsonProperty("invoice_settings")
            fun invoiceSettings(invoiceSettings: InvoiceSettings) = apply {
                this.invoiceSettings = invoiceSettings
            }

            /** How much, in the customer's currency, to charge for each unit. */
            @JsonProperty("per_unit_cost_basis")
            fun perUnitCostBasis(perUnitCostBasis: String) = apply {
                this.perUnitCostBasis = perUnitCostBasis
            }

            /**
             * The threshold at which to trigger the top-up. If the balance is at or below this
             * threshold, the top-up will be triggered.
             */
            @JsonProperty("threshold")
            fun threshold(threshold: String) = apply { this.threshold = threshold }

            /**
             * The number of days or months after which the top-up expires. If unspecified, it does
             * not expire.
             */
            @JsonProperty("expires_after")
            fun expiresAfter(expiresAfter: Long) = apply { this.expiresAfter = expiresAfter }

            /** The unit of expires_after. */
            @JsonProperty("expires_after_unit")
            fun expiresAfterUnit(expiresAfterUnit: ExpiresAfterUnit) = apply {
                this.expiresAfterUnit = expiresAfterUnit
            }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                this.additionalProperties.putAll(additionalProperties)
            }

            @JsonAnySetter
            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                this.additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun build(): CustomerCreditTopUpCreateBody =
                CustomerCreditTopUpCreateBody(
                    checkNotNull(amount) { "`amount` is required but was not set" },
                    checkNotNull(currency) { "`currency` is required but was not set" },
                    checkNotNull(invoiceSettings) {
                        "`invoiceSettings` is required but was not set"
                    },
                    checkNotNull(perUnitCostBasis) {
                        "`perUnitCostBasis` is required but was not set"
                    },
                    checkNotNull(threshold) { "`threshold` is required but was not set" },
                    expiresAfter,
                    expiresAfterUnit,
                    additionalProperties.toImmutable(),
                )
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return /* spotless:off */ other is CustomerCreditTopUpCreateBody && amount == other.amount && currency == other.currency && invoiceSettings == other.invoiceSettings && perUnitCostBasis == other.perUnitCostBasis && threshold == other.threshold && expiresAfter == other.expiresAfter && expiresAfterUnit == other.expiresAfterUnit && additionalProperties == other.additionalProperties /* spotless:on */
        }

        /* spotless:off */
        private val hashCode: Int by lazy { Objects.hash(amount, currency, invoiceSettings, perUnitCostBasis, threshold, expiresAfter, expiresAfterUnit, additionalProperties) }
        /* spotless:on */

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "CustomerCreditTopUpCreateBody{amount=$amount, currency=$currency, invoiceSettings=$invoiceSettings, perUnitCostBasis=$perUnitCostBasis, threshold=$threshold, expiresAfter=$expiresAfter, expiresAfterUnit=$expiresAfterUnit, additionalProperties=$additionalProperties}"
    }

    fun toBuilder() = Builder().from(this)

    companion object {

        @JvmStatic fun builder() = Builder()
    }

    @NoAutoDetect
    class Builder {

        private var customerId: String? = null
        private var amount: String? = null
        private var currency: String? = null
        private var invoiceSettings: InvoiceSettings? = null
        private var perUnitCostBasis: String? = null
        private var threshold: String? = null
        private var expiresAfter: Long? = null
        private var expiresAfterUnit: ExpiresAfterUnit? = null
        private var additionalHeaders: Headers.Builder = Headers.builder()
        private var additionalQueryParams: QueryParams.Builder = QueryParams.builder()
        private var additionalBodyProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(customerCreditTopUpCreateParams: CustomerCreditTopUpCreateParams) =
            apply {
                customerId = customerCreditTopUpCreateParams.customerId
                amount = customerCreditTopUpCreateParams.amount
                currency = customerCreditTopUpCreateParams.currency
                invoiceSettings = customerCreditTopUpCreateParams.invoiceSettings
                perUnitCostBasis = customerCreditTopUpCreateParams.perUnitCostBasis
                threshold = customerCreditTopUpCreateParams.threshold
                expiresAfter = customerCreditTopUpCreateParams.expiresAfter
                expiresAfterUnit = customerCreditTopUpCreateParams.expiresAfterUnit
                additionalHeaders = customerCreditTopUpCreateParams.additionalHeaders.toBuilder()
                additionalQueryParams =
                    customerCreditTopUpCreateParams.additionalQueryParams.toBuilder()
                additionalBodyProperties =
                    customerCreditTopUpCreateParams.additionalBodyProperties.toMutableMap()
            }

        fun customerId(customerId: String) = apply { this.customerId = customerId }

        /** The amount to increment when the threshold is reached. */
        fun amount(amount: String) = apply { this.amount = amount }

        /**
         * The currency or custom pricing unit to use for this top-up. If this is a real-world
         * currency, it must match the customer's invoicing currency.
         */
        fun currency(currency: String) = apply { this.currency = currency }

        /** Settings for invoices generated by triggered top-ups. */
        fun invoiceSettings(invoiceSettings: InvoiceSettings) = apply {
            this.invoiceSettings = invoiceSettings
        }

        /** How much, in the customer's currency, to charge for each unit. */
        fun perUnitCostBasis(perUnitCostBasis: String) = apply {
            this.perUnitCostBasis = perUnitCostBasis
        }

        /**
         * The threshold at which to trigger the top-up. If the balance is at or below this
         * threshold, the top-up will be triggered.
         */
        fun threshold(threshold: String) = apply { this.threshold = threshold }

        /**
         * The number of days or months after which the top-up expires. If unspecified, it does not
         * expire.
         */
        fun expiresAfter(expiresAfter: Long) = apply { this.expiresAfter = expiresAfter }

        /** The unit of expires_after. */
        fun expiresAfterUnit(expiresAfterUnit: ExpiresAfterUnit) = apply {
            this.expiresAfterUnit = expiresAfterUnit
        }

        fun additionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun additionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.clear()
            putAllAdditionalHeaders(additionalHeaders)
        }

        fun putAdditionalHeader(name: String, value: String) = apply {
            additionalHeaders.put(name, value)
        }

        fun putAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.put(name, values)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun putAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.putAll(additionalHeaders)
        }

        fun replaceAdditionalHeaders(name: String, value: String) = apply {
            additionalHeaders.replace(name, value)
        }

        fun replaceAdditionalHeaders(name: String, values: Iterable<String>) = apply {
            additionalHeaders.replace(name, values)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Headers) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun replaceAllAdditionalHeaders(additionalHeaders: Map<String, Iterable<String>>) = apply {
            this.additionalHeaders.replaceAll(additionalHeaders)
        }

        fun removeAdditionalHeaders(name: String) = apply { additionalHeaders.remove(name) }

        fun removeAllAdditionalHeaders(names: Set<String>) = apply {
            additionalHeaders.removeAll(names)
        }

        fun additionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun additionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) = apply {
            this.additionalQueryParams.clear()
            putAllAdditionalQueryParams(additionalQueryParams)
        }

        fun putAdditionalQueryParam(key: String, value: String) = apply {
            additionalQueryParams.put(key, value)
        }

        fun putAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.put(key, values)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.putAll(additionalQueryParams)
        }

        fun putAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.putAll(additionalQueryParams)
            }

        fun replaceAdditionalQueryParams(key: String, value: String) = apply {
            additionalQueryParams.replace(key, value)
        }

        fun replaceAdditionalQueryParams(key: String, values: Iterable<String>) = apply {
            additionalQueryParams.replace(key, values)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: QueryParams) = apply {
            this.additionalQueryParams.replaceAll(additionalQueryParams)
        }

        fun replaceAllAdditionalQueryParams(additionalQueryParams: Map<String, Iterable<String>>) =
            apply {
                this.additionalQueryParams.replaceAll(additionalQueryParams)
            }

        fun removeAdditionalQueryParams(key: String) = apply { additionalQueryParams.remove(key) }

        fun removeAllAdditionalQueryParams(keys: Set<String>) = apply {
            additionalQueryParams.removeAll(keys)
        }

        fun additionalBodyProperties(additionalBodyProperties: Map<String, JsonValue>) = apply {
            this.additionalBodyProperties.clear()
            putAllAdditionalBodyProperties(additionalBodyProperties)
        }

        fun putAdditionalBodyProperty(key: String, value: JsonValue) = apply {
            additionalBodyProperties.put(key, value)
        }

        fun putAllAdditionalBodyProperties(additionalBodyProperties: Map<String, JsonValue>) =
            apply {
                this.additionalBodyProperties.putAll(additionalBodyProperties)
            }

        fun removeAdditionalBodyProperty(key: String) = apply {
            additionalBodyProperties.remove(key)
        }

        fun removeAllAdditionalBodyProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalBodyProperty)
        }

        fun build(): CustomerCreditTopUpCreateParams =
            CustomerCreditTopUpCreateParams(
                checkNotNull(customerId) { "`customerId` is required but was not set" },
                checkNotNull(amount) { "`amount` is required but was not set" },
                checkNotNull(currency) { "`currency` is required but was not set" },
                checkNotNull(invoiceSettings) { "`invoiceSettings` is required but was not set" },
                checkNotNull(perUnitCostBasis) { "`perUnitCostBasis` is required but was not set" },
                checkNotNull(threshold) { "`threshold` is required but was not set" },
                expiresAfter,
                expiresAfterUnit,
                additionalHeaders.build(),
                additionalQueryParams.build(),
                additionalBodyProperties.toImmutable(),
            )
    }

    /** Settings for invoices generated by triggered top-ups. */
    @JsonDeserialize(builder = InvoiceSettings.Builder::class)
    @NoAutoDetect
    class InvoiceSettings
    private constructor(
        private val autoCollection: Boolean?,
        private val netTerms: Long?,
        private val memo: String?,
        private val requireSuccessfulPayment: Boolean?,
        private val additionalProperties: Map<String, JsonValue>,
    ) {

        /**
         * Whether the credits purchase invoice should auto collect with the customer's saved
         * payment method.
         */
        @JsonProperty("auto_collection") fun autoCollection(): Boolean? = autoCollection

        /**
         * The net terms determines the difference between the invoice date and the issue date for
         * the invoice. If you intend the invoice to be due on issue, set this to 0.
         */
        @JsonProperty("net_terms") fun netTerms(): Long? = netTerms

        /** An optional memo to display on the invoice. */
        @JsonProperty("memo") fun memo(): String? = memo

        /**
         * If true, new credit blocks created by this top-up will require that the corresponding
         * invoice is paid before they can be drawn down from.
         */
        @JsonProperty("require_successful_payment")
        fun requireSuccessfulPayment(): Boolean? = requireSuccessfulPayment

        @JsonAnyGetter
        @ExcludeMissing
        fun _additionalProperties(): Map<String, JsonValue> = additionalProperties

        fun toBuilder() = Builder().from(this)

        companion object {

            @JvmStatic fun builder() = Builder()
        }

        class Builder {

            private var autoCollection: Boolean? = null
            private var netTerms: Long? = null
            private var memo: String? = null
            private var requireSuccessfulPayment: Boolean? = null
            private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

            @JvmSynthetic
            internal fun from(invoiceSettings: InvoiceSettings) = apply {
                this.autoCollection = invoiceSettings.autoCollection
                this.netTerms = invoiceSettings.netTerms
                this.memo = invoiceSettings.memo
                this.requireSuccessfulPayment = invoiceSettings.requireSuccessfulPayment
                additionalProperties(invoiceSettings.additionalProperties)
            }

            /**
             * Whether the credits purchase invoice should auto collect with the customer's saved
             * payment method.
             */
            @JsonProperty("auto_collection")
            fun autoCollection(autoCollection: Boolean) = apply {
                this.autoCollection = autoCollection
            }

            /**
             * The net terms determines the difference between the invoice date and the issue date
             * for the invoice. If you intend the invoice to be due on issue, set this to 0.
             */
            @JsonProperty("net_terms")
            fun netTerms(netTerms: Long) = apply { this.netTerms = netTerms }

            /** An optional memo to display on the invoice. */
            @JsonProperty("memo") fun memo(memo: String) = apply { this.memo = memo }

            /**
             * If true, new credit blocks created by this top-up will require that the corresponding
             * invoice is paid before they can be drawn down from.
             */
            @JsonProperty("require_successful_payment")
            fun requireSuccessfulPayment(requireSuccessfulPayment: Boolean) = apply {
                this.requireSuccessfulPayment = requireSuccessfulPayment
            }

            fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.clear()
                this.additionalProperties.putAll(additionalProperties)
            }

            @JsonAnySetter
            fun putAdditionalProperty(key: String, value: JsonValue) = apply {
                this.additionalProperties.put(key, value)
            }

            fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
                this.additionalProperties.putAll(additionalProperties)
            }

            fun build(): InvoiceSettings =
                InvoiceSettings(
                    checkNotNull(autoCollection) { "`autoCollection` is required but was not set" },
                    checkNotNull(netTerms) { "`netTerms` is required but was not set" },
                    memo,
                    requireSuccessfulPayment,
                    additionalProperties.toImmutable(),
                )
        }

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return /* spotless:off */ other is InvoiceSettings && autoCollection == other.autoCollection && netTerms == other.netTerms && memo == other.memo && requireSuccessfulPayment == other.requireSuccessfulPayment && additionalProperties == other.additionalProperties /* spotless:on */
        }

        /* spotless:off */
        private val hashCode: Int by lazy { Objects.hash(autoCollection, netTerms, memo, requireSuccessfulPayment, additionalProperties) }
        /* spotless:on */

        override fun hashCode(): Int = hashCode

        override fun toString() =
            "InvoiceSettings{autoCollection=$autoCollection, netTerms=$netTerms, memo=$memo, requireSuccessfulPayment=$requireSuccessfulPayment, additionalProperties=$additionalProperties}"
    }

    class ExpiresAfterUnit
    @JsonCreator
    private constructor(
        private val value: JsonField<String>,
    ) : Enum {

        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            @JvmField val DAY = of("day")

            @JvmField val MONTH = of("month")

            @JvmStatic fun of(value: String) = ExpiresAfterUnit(JsonField.of(value))
        }

        enum class Known {
            DAY,
            MONTH,
        }

        enum class Value {
            DAY,
            MONTH,
            _UNKNOWN,
        }

        fun value(): Value =
            when (this) {
                DAY -> Value.DAY
                MONTH -> Value.MONTH
                else -> Value._UNKNOWN
            }

        fun known(): Known =
            when (this) {
                DAY -> Known.DAY
                MONTH -> Known.MONTH
                else -> throw OrbInvalidDataException("Unknown ExpiresAfterUnit: $value")
            }

        fun asString(): String = _value().asStringOrThrow()

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return /* spotless:off */ other is ExpiresAfterUnit && value == other.value /* spotless:on */
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return /* spotless:off */ other is CustomerCreditTopUpCreateParams && customerId == other.customerId && amount == other.amount && currency == other.currency && invoiceSettings == other.invoiceSettings && perUnitCostBasis == other.perUnitCostBasis && threshold == other.threshold && expiresAfter == other.expiresAfter && expiresAfterUnit == other.expiresAfterUnit && additionalHeaders == other.additionalHeaders && additionalQueryParams == other.additionalQueryParams && additionalBodyProperties == other.additionalBodyProperties /* spotless:on */
    }

    override fun hashCode(): Int = /* spotless:off */ Objects.hash(customerId, amount, currency, invoiceSettings, perUnitCostBasis, threshold, expiresAfter, expiresAfterUnit, additionalHeaders, additionalQueryParams, additionalBodyProperties) /* spotless:on */

    override fun toString() =
        "CustomerCreditTopUpCreateParams{customerId=$customerId, amount=$amount, currency=$currency, invoiceSettings=$invoiceSettings, perUnitCostBasis=$perUnitCostBasis, threshold=$threshold, expiresAfter=$expiresAfter, expiresAfterUnit=$expiresAfterUnit, additionalHeaders=$additionalHeaders, additionalQueryParams=$additionalQueryParams, additionalBodyProperties=$additionalBodyProperties}"
}
